'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createPairingService}=require('../lib/device-pairing-service');
const key='b'.repeat(43),calls=[];const handler=createPairingService({env:{WPAY_PAIRING_SERVICE_KEY:key},pool:{query:async(sql,args)=>{calls.push({sql,args});return {rowCount:1,rows:[{id:'1'}]};}}});
async function run(path,body,auth='Bearer '+key){const res={statusCode:200,set(){return this},status(n){this.statusCode=n;return this},json(b){this.body=b;return this}};await handler({path,method:'POST',body,get:()=>auth},res);return res;}
test('24h issuance is explicit and persists actual expiry; legacy requests retain 10m',async()=>{calls.length=0;assert.equal((await run('/issue',{ttlSeconds:86400})).body.expiresInSeconds,86400);assert.match(calls[0].sql,/expires_at/);assert.equal(calls[0].args[1],86400);assert.equal((await run('/issue',{})).body.expiresInSeconds,600);for(const ttlSeconds of [0,86401,'86400'])assert.equal((await run('/issue',{ttlSeconds})).statusCode,400);});
test('revocation only updates pending digest-bound codes and rejects unauthenticated calls',async()=>{calls.length=0;assert.equal((await run('/revoke',{digest:'a'.repeat(64)},'wrong')).statusCode,401);assert.equal(calls.length,0);assert.equal((await run('/revoke',{digest:'a'.repeat(64)})).body.revoked,true);assert.match(calls[0].sql,/status='pending'/);assert.equal((await run('/revoke',{digest:'wrong'})).statusCode,400);});
test('diagnostics projection is limited to 48h, one point per 5m, and never returns raw SMS or credentials',async()=>{calls.length=0;await run('/diagnostics',{id:'device-test',from:'2026-09-25T00:00:00Z'});const sql=calls[0].sql;assert.match(sql,/48 hours/);assert.match(sql,/DISTINCT ON/);assert.doesNotMatch(sql,/sms|otp|credential|token|raw\s*[, ]/i);assert.equal((await run('/diagnostics',{id:'device-test',from:'invalid'})).statusCode,400);});
test('PostgreSQL: exact source expiry, revocation and bounded diagnostic history',async t=>{
 if(!process.env.TEST_DATABASE_URL){t.skip('Isolated PostgreSQL required');return;}const url=new URL(process.env.TEST_DATABASE_URL);assert.equal(url.hostname,'127.0.0.1');const {Pool}=require('pg'),{randomUUID,createHash}=require('node:crypto'),server=new Pool({connectionString:url.toString()}),name='pairing_'+randomUUID().replaceAll('-','');await server.query('CREATE DATABASE '+name);url.pathname='/'+name;const pool=new Pool({connectionString:url.toString()});t.after(async()=>{await pool.end();await server.query('DROP DATABASE '+name);await server.end();});
 await pool.query("CREATE TABLE device_pairings(id bigserial primary key,token_hash text unique,status text default 'pending',device_id text,created_at timestamptz default now(),expires_at timestamptz default now()+interval '10 minutes',claimed_at timestamptz); CREATE TABLE devices(id text primary key,status text,app_version text,last_seen_at timestamptz,phone_e164 text,sim_carrier text,sim_subscription_label text,manufacturer text,model text,android_version text); CREATE TABLE device_diagnostics(id bigserial primary key,device_id text,battery_level numeric,charging boolean,network_type text,carrier text,latitude numeric,longitude numeric,location_accuracy numeric,collected_at timestamptz,raw jsonb)");
 const h=createPairingService({env:{WPAY_PAIRING_SERVICE_KEY:key},pool});async function invoke(path,body){const res={statusCode:200,set(){return this},status(n){this.statusCode=n;return this},json(b){this.body=b;return this}};await h({path,method:'POST',body,get:()=>'Bearer '+key},res);return res;}
 const issued=await invoke('/issue',{ttlSeconds:86400});assert.equal(issued.statusCode,201);const digest=createHash('sha256').update(issued.body.pairingCode).digest('hex'),p=await invoke('/proof',{digest});assert.equal(+new Date(p.body.pairing.expires_at)-+new Date(p.body.pairing.created_at),86400000);assert.equal((await invoke('/revoke',{digest})).body.revoked,true);assert.equal((await invoke('/revoke',{digest})).body.revoked,true);assert.equal((await invoke('/proof',{digest})).body.pairing.status,'revoked');
 await pool.query("INSERT INTO device_diagnostics(device_id,battery_level,collected_at,raw) VALUES('device-test',50,now(),'{\"batteryHealth\":\"good\",\"locationEnabled\":true,\"otp\":\"MUST_NOT_LEAK\"}'),('device-test',20,now()-interval '49 hours','{}')");const d=await invoke('/diagnostics',{id:'device-test',from:new Date(Date.now()-72*3600000).toISOString()});assert.equal(d.body.diagnostics.length,1);assert.equal(d.body.diagnostics[0].battery_health,'good');assert.doesNotMatch(JSON.stringify(d.body),/MUST_NOT_LEAK|otp/);
});
