'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('dev/wpay-auth/web/user-burgundy-pages.js','utf8');
function button(classes,type='button',tabs=false){const values=new Set(classes.split(' ').filter(Boolean)),onclick=()=>{};return {type,onclick,parentElement:{classList:{contains:s=>tabs&&s==='tabs'}},classList:{add:(...v)=>v.forEach(x=>values.add(x)),remove:(...v)=>v.forEach(x=>values.delete(x)),contains:v=>values.has(v)},matches:selector=>selector.split(',').some(s=>values.has(s.slice(1))),values};}
function enhance(buttons){const context={};vm.runInNewContext(source,context);const host={querySelector:s=>s==='.page-hero'?{}:null,querySelectorAll:s=>s==='button'?buttons:[]};context.WPayUserBurgundyPages.enhance(host,{title:'Fixture'}, {name:'Fixture'},'bank-upi');}
test('Reference burgundy and danger buttons retain their visual variant and handlers',()=>{const primary=button('btn burg'),danger=button('btn danger'),generic=button(''),handler=primary.onclick;enhance([primary,danger,generic]);assert.equal(primary.values.has('ghost'),false);assert.equal(danger.values.has('ghost'),false);assert.equal(generic.values.has('ghost'),true);assert.equal(primary.onclick,handler);});
test('Reference currency tabs keep native reference styles on repeat presentation passes',()=>{const tab=button('active btn ghost','button',true),handler=tab.onclick;enhance([tab]);enhance([tab]);assert.deepEqual([...tab.values],['active']);assert.equal(tab.onclick,handler);});
test('Live page adaptation never serializes existing forms or injects demo finance',()=>{assert.doesNotMatch(source,/innerHTML\s*=|DEMO_TRC20|store\.balances|Math\.random/);assert.match(source,/formCard.append\(\.\.\.panels\)/);assert.match(source,/select.onchange\(\)/);assert.match(source,/result\);grid.append/);});
test('Reference line-chart geometry renders real minor-unit values, including zero series',async()=>{
 const context={WPayReferencePresentation:{bind(){}}};vm.runInNewContext(fs.readFileSync('dev/wpay-auth/web/user-burgundy-dashboard.js','utf8'),context);
 for(const value of ['0','123456']){let page;const container={replaceChildren:n=>{page=n;}},el=()=>({isConnected:true});await context.WPayUserBurgundyDashboard.render({container,title:{},account:{name:'Fixture'},el,request:async()=>({capacity:{available:'0',held:'0',reserved:'0'},commission:{},payins:{},payouts:{},banks:[],deposits:{},parking:{},recent:[],trend:[{day:'2026-09-29',payin:value,payout:'0'}]})});assert.match(page.innerHTML,/class="dash-line collection-line"/);assert.match(page.innerHTML,/class="dash-line payout-line"/);assert.doesNotMatch(page.innerHTML,/NaN|Infinity/);assert.match(page.innerHTML,new RegExp(value==='0'?'Collection ₹0\\.00':'Collection ₹1234\\.56'));}
});
