'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID,randomBytes}=require('node:crypto');
const {migrate,transaction}=require('../lib/wpay/db/migrations'),ledger=require('../lib/wpay/business/ledger'),late=require('../lib/wpay/reviews/late-payment'),{Payouts}=require('../lib/wpay/payouts/core'),{Parking}=require('../lib/wpay/parking/core'),{MfaCrypto}=require('../lib/wpay/auth/runtime/mfa'),uploads=require('../lib/wpay/payouts/uploads');
test('late requests require a 12-digit UTR, reason and proof together',()=>{const b={id:randomUUID(),utr:'123456789012',reason:'Late bank confirmation',proof:{}};assert.doesNotThrow(()=>late.validate(b));for(const change of [{utr:''},{utr:'123'},{reason:''},{ownerId:randomUUID()}])assert.throws(()=>late.validate({...b,...change}));});
test('PostgreSQL: late proof reserves only available work, preserves competing claims and credits once after scoped review',async t=>{
 if(!process.env.TEST_DATABASE_URL){t.skip('Requires isolated PostgreSQL');return;}
 const url=new URL(process.env.TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1','[::1]'].includes(url.hostname));const {Pool}=require('pg'),server=new Pool({connectionString:url.toString()}),name='late_'+randomUUID().replaceAll('-','');await server.query('CREATE DATABASE '+name);url.pathname='/'+name;const pool=new Pool({connectionString:url.toString()});t.after(async()=>{await pool.end();await server.query('DROP DATABASE '+name);await server.end();});await migrate(pool);
 const admin=randomUUID(),merchant=randomUUID(),user=randomUUID(),other=randomUUID();for(const [id,type]of [[admin,'super_admin'],[merchant,'merchant'],[user,'user'],[other,'user']]){await pool.query("INSERT INTO wpay_auth.accounts(id,subject_id,tenant_id,name,email,account_type,status,user_id,merchant_id) VALUES($1,$2,'late-test','Synthetic',$3,$4,'active',$5,$6)",[id,randomUUID(),id+'@example.invalid',type,type==='user'?id:null,type==='merchant'?id:null]);await pool.query("INSERT INTO wpay_auth.eligibility(account_id,approval_status) VALUES($1,'approved')",[id]);await pool.query('INSERT INTO wpay_auth.account_security(account_id,enabled) VALUES($1,false)',[id]);}
 for(const id of [user,other,merchant])await pool.query('INSERT INTO wpay_auth.commercial_versions(id,account_id,version,settings,actor_id) VALUES($1,$2,1,$3,$4)',[randomUUID(),id,id===merchant?{payoutFee:'1',fixedPayoutFee:'6',fixedFeeCurrency:'INR'}:{payoutCommission:'1',inrPerUsdt:'107'},admin]);
 const crypto=new MfaCrypto(randomBytes(32)),core=new Payouts({crypto,gateway:{merchant:async()=>{},emit:async()=>{}}}),parking=new Parking({crypto}),tx=fn=>transaction(pool,fn);await tx(c=>ledger.post(c,{key:'seed',referenceType:'test',referenceId:'test',entries:ledger.pair(merchant,'merchant_gross','1000000')}));
 let seq=0;const proof=await uploads.proof({name:'synthetic.pdf',data:Buffer.from('%PDF-1.4\nSynthetic late proof\n%%EOF').toString('base64')}),body=id=>({id,utr:String(123456789000+(++seq)),reason:'Delayed proof submission',proof:{}});
 async function expiredPayout(){const key=randomUUID(),p=await tx(c=>core.create(c,merchant,{reference:key,idempotencyKey:key,transferMode:'upi',upiId:'synthetic@test',beneficiaryName:'Synthetic Recipient',amountMinor:'10000',durationMinutes:90}));await tx(async c=>require('../lib/wpay/payouts/approval').decide(core,c,(await c.query('SELECT * FROM wpay_auth.payout_orders WHERE id=$1',[p.id])).rows,admin,'approve','Synthetic approval'));await pool.query("INSERT INTO wpay_auth.payout_claims(id,payout_id,user_id,state,created_at,expires_at,closed_at) VALUES($1,$2,$3,'expired',CURRENT_TIMESTAMP-interval '20 minutes',CURRENT_TIMESTAMP-interval '5 minutes',CURRENT_TIMESTAMP)",[randomUUID(),p.id,user]);return p;}
 const p=await expiredPayout(),b=body(p.id),opened=await Promise.all([tx(c=>late.open(core,c,user,'payout',b,proof)),tx(c=>late.open(core,c,user,'payout',b,proof))]);assert.equal(opened[0].id,opened[1].id);assert.equal(opened[0].heldMinor,'10000');assert.equal((await tx(c=>core.queue(c,other))).orders.some(o=>o.id===p.id),false);await assert.rejects(tx(c=>core.claim(c,other,{id:p.id})),{code:'CONFLICT'});assert.equal((await ledger.summary(pool,user)).available,'0');
 await tx(c=>late.decide(core,c,'payout',admin,{id:opened[0].id,action:'approve',reason:'Independently reviewed bank receipt'}));await tx(c=>late.decide(core,c,'payout',admin,{id:opened[0].id,action:'approve',reason:'Retry review'}));assert.equal((await ledger.summary(pool,user)).available,'10000');assert.equal((await pool.query('SELECT state FROM wpay_auth.payout_orders WHERE id=$1',[p.id])).rows[0].state,'successful');assert.equal((await pool.query("SELECT count(*)::int n FROM wpay_auth.payout_claims WHERE payout_id=$1 AND state='expired'",[p.id])).rows[0].n,1);
 const conflict=await expiredPayout();await tx(c=>core.claim(c,other,{id:conflict.id}));const conflictReview=await tx(c=>late.open(core,c,user,'payout',body(conflict.id),proof));assert.equal(conflictReview.heldMinor,'0');assert.ok(conflictReview.conflict);await assert.rejects(tx(c=>late.decide(core,c,'payout',admin,{id:conflictReview.id,action:'approve',reason:'Cannot replace another claim'})),{code:'CONFLICT'});assert.equal((await pool.query("SELECT user_id FROM wpay_auth.payout_claims WHERE payout_id=$1 AND state='active'",[conflict.id])).rows[0].user_id,other);
 const api=require('../lib/wpay/reviews/late-api');await assert.rejects(tx(c=>api.run(core,c,{id:other,account_type:'user'},{},'payout','payout/late/proof',{id:opened[0].id})),{code:'FORBIDDEN'});
 const beneficiary=await tx(c=>parking.createBeneficiary(c,admin,{requestId:randomUUID(),tenantId:'late-test',beneficiaryName:'Synthetic Recipient',bankName:'Test Bank',accountNumber:'123456789',ifsc:'ABCD0123456',upiId:'synthetic@test'}));for(const u of [user,other])await tx(c=>parking.confirm(c,u,'late-test',beneficiary.id));const order=await tx(c=>parking.createOrder(c,admin,{requestId:randomUUID(),tenantId:'late-test',beneficiaryId:beneficiary.id,reference:'parking-test',totalMinor:'50000',minMinor:'10000'}));
 async function expiredParking(){const id=randomUUID();await pool.query("INSERT INTO wpay_auth.parking_requests(id,owner_id,actor_id,request_id,amount_minor,currency,snapshot,payload_digest) VALUES($1,$2,$2,$3,'20000','INR',$4,$5)",[id,user,randomUUID(),{orderId:order.id},ledger.digest(id)]);await pool.query("INSERT INTO wpay_auth.parking_locks(id,order_id,user_id,amount_minor,state,created_at,expires_at,closed_at) VALUES($1,$2,$3,'20000','released',CURRENT_TIMESTAMP-interval '20 minutes',CURRENT_TIMESTAMP-interval '10 minutes',CURRENT_TIMESTAMP)",[id,order.id,user]);return id;}
 const lock=await expiredParking(),park=await tx(c=>late.open(parking,c,user,'parking',body(lock),proof));assert.equal(park.heldMinor,'20000');assert.equal((await tx(c=>parking.orders(c,{tenantId:'late-test',userId:other})))[0].remainingMinor,'30000');await tx(c=>late.decide(parking,c,'parking',admin,{id:park.id,action:'approve',reason:'Confirmed parking receipt'}));assert.equal((await ledger.summary(pool,user)).available,'30000');
 const second=await expiredParking();await tx(c=>parking.lock(c,other,'late-test',{requestId:randomUUID(),orderId:order.id,amountMinor:'20000'}));const partial=await tx(c=>late.open(parking,c,user,'parking',body(second),proof));assert.equal(partial.heldMinor,'10000');await assert.rejects(tx(c=>late.decide(parking,c,'parking',admin,{id:partial.id,action:'approve',reason:'Cannot overfill parking order'})),{code:'INSUFFICIENT_CAPACITY'});await tx(c=>late.decide(parking,c,'parking',admin,{id:partial.id,action:'reject',reason:'Payment not established'}));assert.equal((await tx(c=>parking.orders(c,{tenantId:'late-test',userId:user})))[0].remainingMinor,'10000');
});
