"use strict";
const {test}=require('node:test'),assert=require('node:assert/strict'),{providerFixture}=require('./helpers/wpay-funding-provider-fixture'),net=require('../lib/wpay/funding/networks'),{FundingProvider}=require('../lib/wpay/funding/provider');
for(const name of Object.keys(net.NETWORKS))test(name+' real receipt verifier with bounded synthetic provider responses',async t=>{
 const s={network:name,...net.network(name),address:name==='ETHEREUM-ERC20'?'0x'+'1'.repeat(40):'TJRabPrwbZy45sbavfcjinPJC18kjpRTv8',amountMinor:'2000000000'},c={tx_hash:(name==='ETHEREUM-ERC20'?'0x':'')+'a'.repeat(64),event_index:0};
 await t.test('successful exact token transfer requires canonical/solidified evidence',async()=>{const f=providerFixture(s,c),p=await f.provider.verify(s,c);assert.equal(p.state,'verified');assert.equal(p.amountMinor,s.amountMinor);assert.equal(p.transferKey,net.transferKey(name,c.tx_hash,0));assert.ok(f.requests.length<=5);assert.ok(f.requests.every(r=>r.redirect==='error'));});
 for(const [label,options,state]of [['wrong chain',{chainId:'0x2'},'review'],['wrong token',{log:{address:'0'.repeat(40)}},'review'],['wrong recipient',{log:{topics:['0x'+require('../lib/wpay/funding/provider').TOPIC,'0x'+'0'.repeat(64),'0x'+'0'.repeat(24)+'3'.repeat(40)]}},'review'],['failed receipt',{failed:true},'review'],['insufficient finality',{confirming:true},'confirming'],['pending',{pending:true},name==='ETHEREUM-ERC20'?'detected':'confirming']])await t.test(label,async()=>assert.equal((await providerFixture(s,c,options).provider.verify(s,c)).state,state));
 await t.test('reorg evidence is explicit',async()=>assert.equal((await providerFixture(s,c,{reorg:true}).provider.verify(s,c,name==='ETHEREUM-ERC20'?'0x'+'ab'.repeat(32):'ab'.repeat(32))).state,'reorg'));
 await t.test('separate log identities in one transaction',async()=>{const f=providerFixture(s,c),log2={...f.log,logIndex:'0x1'};const p=await providerFixture(s,{...c,event_index:1},{logs:[f.log,log2]}).provider.verify(s,{...c,event_index:1});assert.equal(p.state,'verified');assert.notEqual(p.transferKey,net.transferKey(name,c.tx_hash,0));});
});
test('funding exact conversion and provider fail-closed boundaries',async()=>{assert.equal(net.conversion('2000000000','85.75'),'17150000');assert.throws(()=>net.conversion('2000000001','85.75'),{code:'UNREPRESENTABLE_AMOUNT'});assert.equal(net.conversion('2000000000000000000000000000000','85.75'),'17150000000000000000000000000');assert.equal((await new FundingProvider().verify({network:'ETHEREUM-ERC20'},{})).reason,'Verification source not configured');assert.throws(()=>new FundingProvider({ethereumUrl:'http://127.0.0.1/'}));const p=new FundingProvider({ethereumUrl:'https://rpc.example.invalid',fetcher:async()=>{throw Error('secret provider details');}});assert.deepEqual(await p.verify({network:'ETHEREUM-ERC20',...net.network('ETHEREUM-ERC20')},{tx_hash:'0x'+'a'.repeat(64)}),{state:'waiting',reason:'Verification provider unavailable or invalid response'});});
test('funding translations have EN/RU/zh-CN parity',()=>{for(const values of Object.values(require('../dev/wpay-auth/web/funding-locales').labels)){assert.equal(values.length,3);assert.ok(values.every(v=>typeof v==='string'&&v.length));}});
