'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID,randomBytes}=require('node:crypto');
const {migrate,transaction}=require('../lib/wpay/db/migrations'),{Withdrawals}=require('../lib/wpay/payouts/withdrawals');
const ledger=require('../lib/wpay/business/ledger'),{entitlement}=require('../lib/wpay/payouts/accounting'),{MfaCrypto}=require('../lib/wpay/auth/runtime/mfa');
test('PostgreSQL: new-bank withdrawal fees, full release, FX rounding and concurrent reserves',async t=>{
 if(!process.env.TEST_DATABASE_URL){t.skip('Requires isolated PostgreSQL');return;}
 const url=new URL(process.env.TEST_DATABASE_URL);assert.ok(['localhost','127.0.0.1','[::1]'].includes(url.hostname));
 const {Pool}=require('pg'),server=new Pool({connectionString:url.toString()}),name='user_withdrawal_'+randomUUID().replaceAll('-','');
 await server.query('CREATE DATABASE '+name);url.pathname='/'+name;const pool=new Pool({connectionString:url.toString()});
 t.after(async()=>{await pool.end();await server.query('DROP DATABASE '+name);await server.end();});await migrate(pool);
 const admin=randomUUID(),user=randomUUID();
 for(const [id,type]of [[admin,'super_admin'],[user,'user']])await pool.query("INSERT INTO wpay_auth.accounts(id,subject_id,tenant_id,name,email,account_type,status,user_id) VALUES($1,$2,'withdrawal-test','Synthetic Test',$3,$4,'active',$5)",[id,randomUUID(),id+'@example.invalid',type,type==='user'?id:null]);
 await pool.query('INSERT INTO wpay_auth.commercial_versions(id,account_id,version,settings,actor_id) VALUES($1,$2,1,$3,$4)',[randomUUID(),user,{payinCommission:'1',payoutCommission:'1',inrPerUsdt:'107',depositNetwork:'ETHEREUM-ERC20'},admin]);
 const tx=fn=>transaction(pool,fn),w=new Withdrawals(new MfaCrypto(randomBytes(32))),request=body=>tx(c=>w.request(c,user,body));
 await tx(c=>ledger.post(c,{key:'synthetic-commission',referenceType:'test',referenceId:'test',entries:ledger.pair(user,'user_commission','100000')}));
 const body={idempotencyKey:'new-bank',currency:'INR',amountMinor:'100000',bankDetails:{bankName:'Synthetic Bank',beneficiaryName:'Synthetic Person',accountNumber:'1234567890',ifsc:'TEST0000001'}};
 const first=await request(body);assert.equal(first.feeMinor,'500');assert.equal(first.netMinor,'99500');assert.equal(first.entitlementMinor,'100000');assert.equal((await entitlement(pool,user)).available,'0');assert.equal((await request(body)).id,first.id);
 await assert.rejects(request({...body,bankDetails:{...body.bankDetails,accountNumber:'9999999999'}}),{code:'CONFLICT'});
 const change=(r,action,extra={})=>tx(c=>w.transition(c,r,admin,{id:r.id,action,reason:'Synthetic test decision',...extra}));
 await change(first,'reject');await change(first,'reject');assert.equal((await entitlement(pool,user)).available,'100000');
 const usd=await request({idempotencyKey:'maximum-usdt',currency:'USDT',amountMinor:'9345794',network:'ETHEREUM-ERC20',address:'0x'+'3'.repeat(40)});
 assert.equal(usd.entitlementMinor,'100000');assert.equal(usd.feeMinor,'0');await change(usd,'cancel');
 const results=await Promise.allSettled(['race-a','race-b'].map(idempotencyKey=>request({...body,idempotencyKey,amountMinor:'60000'})));
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'INSUFFICIENT_COMMISSION');
 const winner=results.find(r=>r.status==='fulfilled').value;await change(winner,'cancel');
 const complete=await request({...body,idempotencyKey:'complete-new-bank'});for(const action of ['approve','process'])await change(complete,action);
 await assert.rejects(change(complete,'complete',{completedAt:new Date().toISOString()}),{code:'INVALID_INPUT'});
 const completedAt=(await pool.query('SELECT CURRENT_TIMESTAMP AS now')).rows[0].now.toISOString();
 await change(complete,'complete',{reference:'123456789012',completedAt});await change(complete,'complete',{reference:'123456789012',completedAt});
 const dashboard=await require('../lib/wpay/business/user-dashboard').overview(pool,user);assert.equal(dashboard.commission.withdrawn,'100000');assert.equal(dashboard.totalVolumeMinor,'0');assert.equal(dashboard.payins.successful,0);
 assert.equal((await entitlement(pool,user)).withdrawn,'100000');assert.equal((await entitlement(pool,user)).reserved,'0');
});
