'use strict';
const money=require('./money');
const windows={
 '1d':"CURRENT_TIMESTAMP-interval '1 day'",
 '7d':"CURRENT_TIMESTAMP-interval '7 days'",
 '30d':"CURRENT_TIMESTAMP-interval '30 days'",
 all:null
};
class Source{
 constructor({pool,crypto=null}){this.pool=pool;this.crypto=crypto;}
 async accountByEmail(email,type){
  const types=type==='admin'?['admin','super_admin']:[type];
  const r=(await this.pool.query(`SELECT a.id,a.name,a.email,a.account_type,a.status,a.tenant_id,a.user_id,a.merchant_id,e.approval_status,g.admin_scope
   FROM wpay_auth.accounts a LEFT JOIN wpay_auth.eligibility e ON e.account_id=a.id LEFT JOIN wpay_auth.grants g ON g.account_id=a.id
   WHERE lower(a.email)=lower($1) AND a.account_type=ANY($2::text[]) LIMIT 2`,[email,types])).rows;
  if(r.length!==1)throw Error(r.length?'AMBIGUOUS_ACCOUNT':'ACCOUNT_NOT_FOUND');return r[0];
 }
 async account(id){const r=(await this.pool.query(`SELECT a.id,a.name,a.email,a.account_type,a.status,a.tenant_id,a.user_id,a.merchant_id,e.approval_status,g.admin_scope
  FROM wpay_auth.accounts a LEFT JOIN wpay_auth.eligibility e ON e.account_id=a.id LEFT JOIN wpay_auth.grants g ON g.account_id=a.id WHERE a.id=$1`,[id])).rows[0];if(!r)throw Error('ACCOUNT_NOT_FOUND');return r;}
 async adminTenants(account){
  if(!['admin','super_admin'].includes(account.account_type))throw Error('ADMIN_REQUIRED');
  const scope=account.admin_scope||{};
  if(scope.platform===true){return (await this.pool.query("SELECT DISTINCT tenant_id FROM wpay_auth.accounts ORDER BY tenant_id")).rows.map(r=>r.tenant_id);}
  const ids=Array.isArray(scope.tenantIds)?scope.tenantIds.filter(x=>typeof x==='string'&&x):[];
  if(!ids.length)throw Error('ADMIN_SCOPE_REQUIRED');return [...new Set(ids)];
 }
 async assertAdminTarget(admin,target){const tenants=await this.adminTenants(admin);if(!tenants.includes(target.tenant_id))throw Error('OUT_OF_SCOPE');return target;}
 async ledgerBalances(ownerId){const rows=(await this.pool.query("SELECT ledger_type,COALESCE(sum(CASE WHEN direction='credit' THEN amount_minor ELSE -amount_minor END),0)::text amount FROM wpay_auth.business_entries WHERE owner_id=$1 AND currency='INR' GROUP BY ledger_type",[ownerId])).rows;return Object.fromEntries(rows.map(r=>[r.ledger_type,BigInt(r.amount)]));}
 async ledgerSummary(ownerId){
  const b=await this.ledgerBalances(ownerId),active=BigInt((await this.pool.query("SELECT COALESCE(sum(amount_minor),0)::text amount FROM wpay_auth.business_reservations WHERE user_id=$1 AND state='active' AND expires_at>CURRENT_TIMESTAMP",[ownerId])).rows[0].amount||0);
  const g=k=>b[k]||0n,allocated=g('capacity_allocated'),consumed=g('capacity_consumed'),held=g('capacity_hold'),signed=allocated-consumed-active-held;
  const merchantAvailable=g('merchant_gross')+g('merchant_adjustment')-g('merchant_platform_fee')-g('merchant_payout_fee')-g('merchant_hold')-g('merchant_payout_reserved')-g('merchant_payout_principal')-g('merchant_settlement_reserved')-g('merchant_settlement_principal');
  return {allocated:String(allocated),consumed:String(consumed),reserved:String(active),held:String(held),available:String(signed>0n?signed:0n),signedAvailable:String(signed),deficit:String(signed<0n?-signed:0n),commission:String(g('user_commission')),gross:String(g('merchant_gross')),fees:String(g('merchant_platform_fee')),payoutFees:String(g('merchant_payout_fee')),merchantHeld:String(g('merchant_hold')),merchantPayoutReserved:String(g('merchant_payout_reserved')),merchantPayoutPrincipal:String(g('merchant_payout_principal')),merchantSettlementReserved:String(g('merchant_settlement_reserved')),merchantSettlementPrincipal:String(g('merchant_settlement_principal')),merchantAvailable:String(merchantAvailable)};
 }
 async commercial(id){return (await this.pool.query('SELECT id,version,settings,effective_at FROM wpay_auth.commercial_versions WHERE account_id=$1 AND effective_at<=CURRENT_TIMESTAMP ORDER BY effective_at DESC,version DESC LIMIT 1',[id])).rows[0]||null;}
 async commission(id){
  const b=await this.ledgerBalances(id),g=k=>b[k]||0n,payin=g('user_commission'),payout=g('user_payout_commission'),adjustments=g('user_commission_adjustment'),held=g('user_commission_hold'),reserved=g('user_commission_reserved'),withdrawn=g('user_commission_withdrawn'),gross=payin+payout+adjustments,available=gross-held-reserved-withdrawn,terms=await this.commercial(id);
  // USDT conversion mirrors repo semantics: INR paise * 1e10 / rate scaled to 1e6.
  const rateScaled=terms?.settings?.inrPerUsdt?money.fromDecimal(terms.settings.inrPerUsdt,6):0n;
  return {payin:String(payin),payout:String(payout),adjustments:String(adjustments),gross:String(gross),held:String(held),reserved:String(reserved),withdrawn:String(withdrawn),available:String(available>0n?available:0n),signedAvailable:String(available),inrPerUsdt:terms?.settings?.inrPerUsdt||null,rateVersion:terms?.version||null,network:terms?.settings?.depositNetwork||null,usdtEquivalentMinor:rateScaled>0n?String((available>0n?available:0n)*10000000000n/rateScaled):'0'};
 }
 async userSummary(account){
  const [capacity,commission,terms,payins,payouts,parking,deposits,banks,access]=await Promise.all([
   this.ledgerSummary(account.id),this.commission(account.id),this.commercial(account.id),
   this.pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE o.state='successful')::int successful,count(*) FILTER(WHERE o.state='failed')::int failed,count(*) FILTER(WHERE o.state IN('pending_payment','verification_pending'))::int pending,count(*) FILTER(WHERE (o.created_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date)::int today_orders,COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful'),0)::text volume,COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful' AND (o.paid_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date),0)::text today_volume FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations r ON r.id=o.reservation_id WHERE r.user_id=$1`,[account.id]),
   this.pool.query(`SELECT count(*) FILTER(WHERE cl.state='consumed')::int successful,count(*) FILTER(WHERE cl.state='submitted')::int review,COALESCE(sum(p.amount_minor) FILTER(WHERE cl.state='consumed'),0)::text volume FROM wpay_auth.payout_claims cl JOIN wpay_auth.payout_orders p ON p.id=cl.payout_id WHERE cl.user_id=$1 AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')`,[account.id]),
   this.pool.query("SELECT COALESCE(sum(amount_minor) FILTER(WHERE state='completed'),0)::text volume,COALESCE(sum(amount_minor) FILTER(WHERE state IN('active','cooldown','submitted','review','disputed')),0)::text locked,count(*) FILTER(WHERE state IN('active','cooldown','submitted','review','disputed'))::int active FROM wpay_auth.parking_locks WHERE user_id=$1",[account.id]),
   this.pool.query("SELECT COALESCE(sum(floor(credit_minor*10000000000/((snapshot->>'rate')::numeric*1000000))) FILTER(WHERE state='confirmed'),0)::text usdt_minor,count(*) FILTER(WHERE state='confirmed')::int confirmed,count(*) FILTER(WHERE state IN('requested','detected','confirming','review'))::int pending FROM wpay_auth.funding_requests WHERE owner_id=$1",[account.id]),
   this.pool.query("SELECT count(*) FILTER(WHERE status='running' AND NOT frozen AND NOT deactivated)::int running,count(*)::int total FROM wpay_auth.business_bank_accounts WHERE owner_id=$1",[account.id]),
   this.pool.query("SELECT COALESCE(free_setup,false) free_setup,COALESCE(unlimited_collection,false) unlimited_collection FROM wpay_auth.user_collection_permissions WHERE user_id=$1",[account.id])
  ]);
  const payin=payins.rows[0],payout=payouts.rows[0],park=parking.rows[0],totalVolumeMinor=String(BigInt(payin.volume||0)+BigInt(payout.volume||0)+BigInt(park.volume||0));
  return {account,capacity,commission,terms,payins:payin,payouts:payout,parking:park,deposits:deposits.rows[0],runningUpi:banks.rows[0].running,totalUpi:banks.rows[0].total,totalVolumeMinor,collectionAccess:access.rows[0]||{free_setup:false,unlimited_collection:false}};
 }
 async merchantSummary(account){
  const [balance,terms,states,holds,payouts]=await Promise.all([
   this.ledgerSummary(account.id),this.commercial(account.id),
   this.pool.query("SELECT state,count(*)::int count,COALESCE(sum(amount_minor),0)::text volume FROM wpay_auth.gateway_orders WHERE merchant_id=$1 GROUP BY state",[account.id]),
   this.pool.query("SELECT COALESCE(sum(amount_minor) FILTER(WHERE category='frozen'),0)::text frozen,COALESCE(sum(amount_minor) FILTER(WHERE category='hold'),0)::text hold FROM wpay_auth.business_holds WHERE owner_id=$1 AND state='active'",[account.id]),
   this.pool.query(`SELECT CASE WHEN r.outcome='payment_invalid' THEN 'reversed' ELSE p.state END state,count(*)::int count,COALESCE(sum(p.amount_minor),0)::text volume FROM wpay_auth.payout_orders p LEFT JOIN wpay_auth.payout_disputes d ON d.payout_id=p.id LEFT JOIN wpay_auth.payout_dispute_resolutions r ON r.dispute_id=d.id WHERE p.merchant_id=$1 GROUP BY CASE WHEN r.outcome='payment_invalid' THEN 'reversed' ELSE p.state END`,[account.id])
  ]);
  const counts=Object.fromEntries(states.rows.map(r=>[r.state,r.count])),success=counts.successful||0,failed=counts.failed||0;
  const frozen=BigInt(holds.rows[0].frozen||0),totalHeld=BigInt(balance.merchantHeld||0),ordinaryHold=totalHeld>frozen?totalHeld-frozen:0n,payoutMap=Object.fromEntries(payouts.rows.map(r=>[r.state,{count:r.count,volume:r.volume}])),successfulCollectionVolume=states.rows.find(r=>r.state==='successful')?.volume||'0',successfulPayoutVolume=payoutMap.successful?.volume||'0';
  return {account,balance,terms,frozen:String(frozen),hold:String(ordinaryHold),gateway:{counts,successfulVolumeMinor:successfulCollectionVolume,successRate:success+failed?success/(success+failed):null},payouts:payoutMap,successfulPayoutVolumeMinor:successfulPayoutVolume,totalVolumeMinor:String(BigInt(successfulCollectionVolume)+BigInt(successfulPayoutVolume))};
 }
 async adminSummary(account){
  const tenants=await this.adminTenants(account),scopeLabel=account.admin_scope?.platform===true?'Platform':tenants.join(', ');
  const [balances,today,upi,deposits]=await Promise.all([
   this.pool.query(`SELECT a.account_type,e.ledger_type,COALESCE(sum(CASE WHEN e.direction='credit' THEN e.amount_minor ELSE -e.amount_minor END),0)::text amount FROM wpay_auth.business_entries e JOIN wpay_auth.accounts a ON a.id=e.owner_id WHERE a.tenant_id=ANY($1) AND e.currency='INR' GROUP BY a.account_type,e.ledger_type`,[tenants]),
   this.pool.query(`SELECT COALESCE(sum(g.amount_minor) FILTER(WHERE g.state='successful' AND (g.paid_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date),0)::text collection,COALESCE((SELECT sum(p.amount_minor) FROM wpay_auth.payout_orders p JOIN wpay_auth.accounts a2 ON a2.id=p.merchant_id WHERE a2.tenant_id=ANY($1) AND p.state='successful' AND (p.completed_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')),0)::text payout FROM wpay_auth.gateway_orders g JOIN wpay_auth.accounts a ON a.id=g.merchant_id WHERE a.tenant_id=ANY($1)`,[tenants]),
   this.pool.query(`SELECT count(*) FILTER(WHERE status='running' AND NOT frozen AND NOT deactivated)::int running,count(*) FILTER(WHERE status='running' AND NOT frozen AND NOT deactivated AND used_minor<limit_minor)::int available FROM (SELECT b.status,b.frozen,b.deactivated,COALESCE(dl.limit_minor,v.limit_minor) limit_minor,((SELECT COALESCE(sum(r.amount_minor),0) FROM wpay_auth.business_reservations r WHERE r.bank_id=b.id AND r.state='active' AND r.expires_at>CURRENT_TIMESTAMP)+(SELECT COALESCE(sum(f.amount_minor),0) FROM wpay_auth.business_financial_events f JOIN wpay_auth.business_reservations r ON r.id=f.reservation_id WHERE r.bank_id=b.id AND (f.created_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date)) used_minor FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.accounts a ON a.id=b.owner_id JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version LEFT JOIN wpay_auth.upi_daily_limits dl ON dl.bank_id=b.id WHERE a.tenant_id=ANY($1)) x`,[tenants]),
   this.pool.query("SELECT COALESCE(sum(credit_minor),0)::text inr,COALESCE(sum((snapshot->>'amountMinor')::numeric),0)::text usdt FROM wpay_auth.funding_requests WHERE tenant_id=ANY($1) AND state='confirmed'",[tenants])
  ]);
  const map=type=>Object.fromEntries(balances.rows.filter(r=>r.account_type===type).map(r=>[r.ledger_type,BigInt(r.amount)])),m=map('merchant'),u=map('user'),M=k=>m[k]||0n,U=k=>u[k]||0n;
  const merchantAvailable=M('merchant_gross')+M('merchant_adjustment')-M('merchant_platform_fee')-M('merchant_payout_fee')-M('merchant_hold')-M('merchant_payout_reserved')-M('merchant_payout_principal')-M('merchant_settlement_reserved')-M('merchant_settlement_principal');
  const totalVolume=(await this.pool.query(`SELECT COALESCE(sum(amount),0)::text amount FROM (SELECT g.amount_minor amount FROM wpay_auth.gateway_orders g JOIN wpay_auth.accounts a ON a.id=g.merchant_id WHERE a.tenant_id=ANY($1) AND g.state='successful' UNION ALL SELECT p.amount_minor FROM wpay_auth.payout_orders p JOIN wpay_auth.accounts a ON a.id=p.merchant_id WHERE a.tenant_id=ANY($1) AND p.state='successful' AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')) x`,[tenants])).rows[0].amount;
  const todayLedger=(await this.pool.query(`SELECT e.ledger_type,COALESCE(sum(CASE WHEN e.direction='credit' THEN e.amount_minor ELSE -e.amount_minor END),0)::text amount FROM wpay_auth.business_entries e JOIN wpay_auth.business_journals j ON j.id=e.journal_id JOIN wpay_auth.accounts a ON a.id=e.owner_id WHERE a.tenant_id=ANY($1) AND e.currency='INR' AND (j.created_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date AND e.ledger_type=ANY($2) GROUP BY e.ledger_type`,[tenants,['merchant_platform_fee','merchant_payout_fee','user_commission','user_payout_commission']])).rows,tm=Object.fromEntries(todayLedger.map(x=>[x.ledger_type,BigInt(x.amount)]));
  const gatewayHealth=(await this.pool.query(`SELECT count(*) FILTER(WHERE g.state='successful')::int successful,count(*) FILTER(WHERE g.state IN('pending_payment','verification_pending','recovery_review'))::int pending,count(*) FILTER(WHERE g.state='failed')::int failed FROM wpay_auth.gateway_orders g JOIN wpay_auth.accounts a ON a.id=g.merchant_id WHERE a.tenant_id=ANY($1)`,[tenants])).rows[0];
  const payoutSuccessful=(await this.pool.query(`SELECT count(*)::int n FROM wpay_auth.payout_orders p JOIN wpay_auth.accounts a ON a.id=p.merchant_id WHERE a.tenant_id=ANY($1) AND p.state='successful' AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')`,[tenants])).rows[0].n;
  const transactionHealth={successful:Number(gatewayHealth.successful||0)+Number(payoutSuccessful||0),pending:Number(gatewayHealth.pending||0),failed:Number(gatewayHealth.failed||0)},healthTotal=transactionHealth.successful+transactionHealth.pending+transactionHealth.failed,overallSuccessRate=healthTotal?transactionHealth.successful/healthTotal:null;
  return {account,tenants,scopeLabel,merchantAvailable:String(merchantAvailable),frozen:String(M('merchant_hold')+M('merchant_payout_reserved')+M('merchant_settlement_reserved')),settlement:String(M('merchant_settlement_principal')),totalUserCapacity:String(U('capacity_allocated')),userConsumedCapacity:String(U('capacity_consumed')),userReservedCapacity:String(U('capacity_reserved')),userHeldCapacity:String(U('capacity_hold')),userAvailableCapacity:String(U('capacity_allocated')-U('capacity_consumed')-U('capacity_reserved')-U('capacity_hold')),totalUserCommission:String(U('user_commission')+U('user_payout_commission')+U('user_commission_adjustment')),totalFees:String(M('merchant_platform_fee')+M('merchant_payout_fee')),todayFees:String((tm.merchant_platform_fee||0n)+(tm.merchant_payout_fee||0n)),todayUserCommission:String((tm.user_commission||0n)+(tm.user_payout_commission||0n)),todayCollection:today.rows[0].collection,todayPayoutVolume:today.rows[0].payout,totalVolume,runningUpi:upi.rows[0].running,availableUpi:upi.rows[0].available,totalUserDeposits:deposits.rows[0].inr,totalUserDepositsUsdt:deposits.rows[0].usdt,transactionHealth,overallSuccessRate};
 }
 async summary(account){if(account.account_type==='user')return this.userSummary(account);if(account.account_type==='merchant')return this.merchantSummary(account);return this.adminSummary(account);}
 windowClause(window,column){if(!windows[window])return {sql:'',args:[]};return {sql:` AND ${column}>=${windows[window]}`,args:[]};}
 async volume(account,window='all'){
  const since=windows[window];
  if(account.account_type==='user'){
   const q=await this.pool.query(`SELECT COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful' ${since?`AND o.paid_at>=${since}`:''}),0)::text payin,COALESCE((SELECT sum(p.amount_minor) FROM wpay_auth.payout_claims c JOIN wpay_auth.payout_orders p ON p.id=c.payout_id WHERE c.user_id=$1 AND c.state='consumed' ${since?`AND p.completed_at>=${since}`:''} AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')),0)::text payout,COALESCE((SELECT sum(amount_minor) FROM wpay_auth.parking_locks WHERE user_id=$1 AND state='completed' ${since?`AND COALESCE(closed_at,created_at)>=${since}`:''}),0)::text parking FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations r ON r.id=o.reservation_id WHERE r.user_id=$1`,[account.id]);return {...q.rows[0],window};
  }
  if(account.account_type==='merchant'){
   const q=await this.pool.query(`SELECT COALESCE(sum(amount_minor) FILTER(WHERE state='successful' ${since?`AND paid_at>=${since}`:''}),0)::text payin,COALESCE((SELECT sum(p.amount_minor) FROM wpay_auth.payout_orders p WHERE p.merchant_id=$1 AND p.state='successful' ${since?`AND p.completed_at>=${since}`:''} AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')),0)::text payout FROM wpay_auth.gateway_orders WHERE merchant_id=$1`,[account.id]);return {...q.rows[0],window};
  }
  const tenants=await this.adminTenants(account),q=await this.pool.query(`SELECT COALESCE(sum(amount),0)::text total FROM (SELECT g.amount_minor amount FROM wpay_auth.gateway_orders g JOIN wpay_auth.accounts a ON a.id=g.merchant_id WHERE a.tenant_id=ANY($1) AND g.state='successful' ${since?`AND g.paid_at>=${since}`:''} UNION ALL SELECT p.amount_minor FROM wpay_auth.payout_orders p JOIN wpay_auth.accounts a ON a.id=p.merchant_id WHERE a.tenant_id=ANY($1) AND p.state='successful' ${since?`AND p.completed_at>=${since}`:''} AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')) x`,[tenants]);return {total:q.rows[0].total,window};
 }
 async ledger(account,{limit=10,filter}={}){
  const clauses=[],args=[];let ownerSql='e.owner_id=$1';args.push(account.id);
  if(['admin','super_admin'].includes(account.account_type)){const tenants=await this.adminTenants(account);ownerSql='a.tenant_id=ANY($1)';args[0]=tenants;}
  const patterns={capacity:"e.ledger_type LIKE 'capacity_%'",commission:"e.ledger_type LIKE 'user_commission%'",fees:"e.ledger_type IN ('merchant_platform_fee','merchant_payout_fee')",holds:"e.ledger_type LIKE '%hold%'",payout:"(e.ledger_type LIKE '%payout%' OR e.ledger_type LIKE '%settlement%')"};if(filter)clauses.push(patterns[filter]);
  args.push(limit);
  return (await this.pool.query(`SELECT e.id,e.owner_id,e.ledger_type,e.direction,e.amount_minor::text,e.currency,j.reference_type,j.reference_id,j.created_at,a.name owner_name FROM wpay_auth.business_entries e JOIN wpay_auth.business_journals j ON j.id=e.journal_id JOIN wpay_auth.accounts a ON a.id=e.owner_id WHERE ${ownerSql} AND e.currency='INR' ${clauses.length?'AND '+clauses.join(' AND '):''} AND e.ledger_type<>'clearing' ORDER BY j.created_at DESC,j.id,e.id LIMIT $2`,args)).rows;
 }
 async holds(account,{category=null}={}){
  let ids=null,tenants=null;if(['admin','super_admin'].includes(account.account_type))tenants=await this.adminTenants(account);else ids=[account.id];
  const basic=(await this.pool.query(`SELECT h.id,h.owner_id,a.name owner_name,h.amount_minor::text,h.currency,h.state,h.category,h.reason,h.reference,h.created_at,h.released_at FROM wpay_auth.business_holds h JOIN wpay_auth.accounts a ON a.id=h.owner_id WHERE ($1::uuid[] IS NULL OR h.owner_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) AND ($3::text IS NULL OR h.category=$3) ORDER BY h.created_at DESC LIMIT 100`,[ids,tenants,category])).rows;
  if(account.account_type==='user'||['admin','super_admin'].includes(account.account_type)){
   const commission=(await this.pool.query(`SELECT h.id,h.user_id owner_id,a.name owner_name,h.amount_minor::text,'INR' currency,CASE WHEN h.released_at IS NULL THEN 'active' ELSE 'released' END state,'commission_hold' category,h.reason,h.reference,h.created_at,h.released_at FROM wpay_auth.commission_holds h JOIN wpay_auth.accounts a ON a.id=h.user_id WHERE ($1::uuid[] IS NULL OR h.user_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY h.created_at DESC LIMIT 100`,[ids,tenants])).rows;basic.push(...commission);
   const disputes=(await this.pool.query(`SELECT d.id,d.user_id owner_id,a.name owner_name,d.amount_minor::text,'INR' currency,CASE WHEN r.dispute_id IS NULL THEN 'active' ELSE 'released' END state,'payout_dispute_capacity' category,d.reason,p.reference,d.created_at,r.created_at released_at FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_orders p ON p.id=d.payout_id JOIN wpay_auth.accounts a ON a.id=d.user_id LEFT JOIN wpay_auth.payout_dispute_resolutions r ON r.dispute_id=d.id WHERE ($1::uuid[] IS NULL OR d.user_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY d.created_at DESC LIMIT 100`,[ids,tenants])).rows;basic.push(...disputes);
   const payoutCommission=(await this.pool.query(`SELECT d.id::text||':commission' id,d.user_id owner_id,a.name owner_name,d.commission_minor::text amount_minor,'INR' currency,CASE WHEN r.dispute_id IS NULL THEN 'active' ELSE 'released' END state,'payout_dispute_commission' category,d.reason,p.reference,d.created_at,r.created_at released_at FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_orders p ON p.id=d.payout_id JOIN wpay_auth.accounts a ON a.id=d.user_id LEFT JOIN wpay_auth.payout_dispute_resolutions r ON r.dispute_id=d.id WHERE d.commission_minor>0 AND ($1::uuid[] IS NULL OR d.user_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY d.created_at DESC LIMIT 100`,[ids,tenants])).rows;basic.push(...payoutCommission);
   const payinUser=(await this.pool.query(`SELECT d.id,d.user_id owner_id,a.name owner_name,d.amount_minor::text,'INR' currency,CASE WHEN r.dispute_id IS NULL THEN 'active' ELSE 'released' END state,'payin_dispute_capacity' category,d.reason,o.reference,d.created_at,r.created_at released_at FROM wpay_auth.payin_disputes d JOIN wpay_auth.gateway_orders o ON o.id=d.order_id JOIN wpay_auth.accounts a ON a.id=d.user_id LEFT JOIN wpay_auth.payin_dispute_resolutions r ON r.dispute_id=d.id WHERE ($1::uuid[] IS NULL OR d.user_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY d.created_at DESC LIMIT 100`,[ids,tenants])).rows;basic.push(...payinUser);
   const payinCommission=(await this.pool.query(`SELECT d.id::text||':commission' id,d.user_id owner_id,a.name owner_name,d.commission_minor::text amount_minor,'INR' currency,CASE WHEN r.dispute_id IS NULL THEN 'active' ELSE 'released' END state,'payin_dispute_commission' category,d.reason,o.reference,d.created_at,r.created_at released_at FROM wpay_auth.payin_disputes d JOIN wpay_auth.gateway_orders o ON o.id=d.order_id JOIN wpay_auth.accounts a ON a.id=d.user_id LEFT JOIN wpay_auth.payin_dispute_resolutions r ON r.dispute_id=d.id WHERE d.commission_minor>0 AND ($1::uuid[] IS NULL OR d.user_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY d.created_at DESC LIMIT 100`,[ids,tenants])).rows;basic.push(...payinCommission);
  }
  if(account.account_type==='merchant'||['admin','super_admin'].includes(account.account_type)){
   const merchantIds=account.account_type==='merchant'?[account.id]:null,merchantTenants=['admin','super_admin'].includes(account.account_type)?tenants:null;
   const payinMerchant=(await this.pool.query(`SELECT d.id::text||':merchant' id,d.merchant_id owner_id,a.name owner_name,d.merchant_net_minor::text amount_minor,'INR' currency,CASE WHEN r.dispute_id IS NULL THEN 'active' ELSE 'released' END state,'payin_dispute_merchant' category,d.reason,o.reference,d.created_at,r.created_at released_at FROM wpay_auth.payin_disputes d JOIN wpay_auth.gateway_orders o ON o.id=d.order_id JOIN wpay_auth.accounts a ON a.id=d.merchant_id LEFT JOIN wpay_auth.payin_dispute_resolutions r ON r.dispute_id=d.id WHERE d.merchant_net_minor>0 AND ($1::uuid[] IS NULL OR d.merchant_id=ANY($1)) AND ($2::text[] IS NULL OR a.tenant_id=ANY($2)) ORDER BY d.created_at DESC LIMIT 100`,[merchantIds,merchantTenants])).rows;basic.push(...payinMerchant);
  }
  return basic.filter(r=>!category||r.category===category).sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));
 }
 async upis(account,selected=null){
  let rows=[];
  if(account.account_type==='user')rows=(await this.pool.query(`SELECT b.id,b.owner_id,a.name owner_name,b.version,b.status,b.frozen,b.deactivated,v.details->>'upiId' upi_id,v.details->>'bankName' bank_name,COALESCE(dl.limit_minor,v.limit_minor)::text daily_limit_minor FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.accounts a ON a.id=b.owner_id JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version LEFT JOIN wpay_auth.upi_daily_limits dl ON dl.bank_id=b.id WHERE b.owner_id=$1 AND ($2::text IS NULL OR lower(v.details->>'upiId')=$2) ORDER BY b.created_at DESC LIMIT 100`,[account.id,selected])).rows;
  else if(account.account_type==='merchant')throw Error('MERCHANT_ROUTE_DETAILS_PRIVATE');
  else {const tenants=await this.adminTenants(account);rows=(await this.pool.query(`SELECT b.id,b.owner_id,a.name owner_name,b.version,b.status,b.frozen,b.deactivated,v.details->>'upiId' upi_id,v.details->>'bankName' bank_name,COALESCE(dl.limit_minor,v.limit_minor)::text daily_limit_minor FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.accounts a ON a.id=b.owner_id JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version LEFT JOIN wpay_auth.upi_daily_limits dl ON dl.bank_id=b.id WHERE a.tenant_id=ANY($1) AND ($2::text IS NULL OR lower(v.details->>'upiId')=$2) ORDER BY a.name,b.created_at DESC LIMIT 100`,[tenants,selected])).rows;}
  for(const r of rows){const vol=(await this.pool.query(`WITH identity AS (SELECT account_key FROM wpay_auth.business_bank_identities WHERE bank_id=$1 AND version=$2)
   SELECT ((SELECT COALESCE(sum(x.amount_minor),0) FROM wpay_auth.business_reservations x JOIN wpay_auth.business_bank_identities i ON i.bank_id=x.bank_id AND i.version=x.bank_version WHERE i.account_key=(SELECT account_key FROM identity) AND x.state='active' AND x.expires_at>CURRENT_TIMESTAMP)+
   (SELECT COALESCE(sum(f.amount_minor),0) FROM wpay_auth.business_financial_events f JOIN wpay_auth.business_reservations br ON br.id=f.reservation_id JOIN wpay_auth.business_bank_identities i ON i.bank_id=br.bank_id AND i.version=br.bank_version WHERE i.account_key=(SELECT account_key FROM identity) AND f.created_at>CURRENT_TIMESTAMP-interval '24 hours')+
   (SELECT COALESCE(sum(p.amount_minor),0) FROM wpay_auth.payout_claims c JOIN wpay_auth.payout_orders p ON p.id=c.payout_id WHERE c.account_key=(SELECT account_key FROM identity) AND ((c.state='active' AND c.expires_at>CURRENT_TIMESTAMP) OR c.state='submitted' OR (c.state='consumed' AND p.completed_at>CURRENT_TIMESTAMP-interval '24 hours'))))::text used,
   (SELECT min(v.limit_minor)::text FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version JOIN wpay_auth.business_bank_identities i ON i.bank_id=v.bank_id AND i.version=v.version WHERE i.account_key=(SELECT account_key FROM identity) AND NOT b.deactivated) shared_limit`,[r.id,r.version])).rows[0],stats=(await this.pool.query("SELECT count(*) FILTER(WHERE o.state='successful')::int successful,COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful'),0)::text volume FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations br ON br.id=o.reservation_id WHERE br.bank_id=$1",[r.id])).rows[0];r.used=vol.used||'0';r.shared_limit=vol.shared_limit||r.daily_limit_minor||'0';r.remaining=String(BigInt(r.shared_limit)>BigInt(r.used)?BigInt(r.shared_limit)-BigInt(r.used):0n);Object.assign(r,stats);}
  return rows;
 }
 async merchantUpiSummary(account){if(account.account_type!=='merchant')throw Error('MERCHANT_ONLY');const stats=(await this.pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE state='successful')::int successful,count(*) FILTER(WHERE state IN('pending_payment','verification_pending','recovery_review'))::int pending,count(*) FILTER(WHERE state='failed')::int failed,COALESCE(sum(amount_minor) FILTER(WHERE state='successful'),0)::text volume FROM wpay_auth.gateway_orders WHERE merchant_id=$1`,[account.id])).rows[0],routes=(await this.pool.query("SELECT count(*)::int n FROM wpay_auth.business_assignments WHERE merchant_id=$1 AND status='active'",[account.id])).rows[0].n;return {...stats,routeCount:routes,privacy:'User bank, UPI and device routing details are private'};}
 async upiVolume(account,selected,window='all'){const rows=await this.upis(account,selected);if(rows.length!==1)throw Error(rows.length?'AMBIGUOUS_UPI':'UPI_NOT_FOUND');const r=rows[0],since=windows[window];const q=(await this.pool.query(`SELECT count(*) FILTER(WHERE o.state='successful')::int successful,COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful'),0)::text volume FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations br ON br.id=o.reservation_id WHERE br.bank_id=$1 ${since?`AND o.paid_at>=${since}`:''}`,[r.id])).rows[0];return {...r,...q,window};}
 async rates(account){const t=await this.commercial(account.id);if(!t)return null;return {version:t.version,effectiveAt:t.effective_at,settings:t.settings};}
 async deposits(account){if(account.account_type!=='user')throw Error('USER_ONLY');return (await this.pool.query("SELECT id,state,credit_minor::text,snapshot,reason,created_at,updated_at FROM wpay_auth.funding_requests WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 50",[account.id])).rows;}
 async withdrawals(account){
  if(account.account_type==='user'){
   const rows=(await this.pool.query("SELECT id,currency,amount_minor::text,entitlement_minor::text,state,created_at,completed_at,snapshot,encrypted_destination FROM wpay_auth.commission_withdrawals WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50",[account.id])).rows;
   for(const r of rows)if(this.crypto&&r.encrypted_destination){try{r.destination=JSON.parse(this.crypto.open(r.encrypted_destination,'wpay-withdrawal-destination:'+r.id));}catch{r.destination=null;}}return rows;
  }
  if(account.account_type==='merchant'){
   const rows=(await this.pool.query("SELECT id,inr_minor::text,usdt_minor::text,state,created_at,completed_at,snapshot,encrypted_destination FROM wpay_auth.merchant_settlement_withdrawals WHERE merchant_id=$1 ORDER BY created_at DESC LIMIT 50",[account.id])).rows;
   for(const r of rows)if(this.crypto&&r.encrypted_destination){try{r.destination=JSON.parse(this.crypto.open(r.encrypted_destination,'wpay-merchant-settlement-destination:'+r.id));}catch{r.destination=null;}}return rows;
  }
  const tenants=await this.adminTenants(account),userRows=(await this.pool.query("SELECT w.id,'user_commission' kind,w.user_id owner_id,a.name owner_name,w.currency,w.amount_minor::text,w.entitlement_minor::text,w.state,w.created_at,w.completed_at,w.snapshot FROM wpay_auth.commission_withdrawals w JOIN wpay_auth.accounts a ON a.id=w.user_id WHERE a.tenant_id=ANY($1) ORDER BY w.created_at DESC LIMIT 50",[tenants])).rows,merchantRows=(await this.pool.query("SELECT w.id,'merchant_settlement' kind,w.merchant_id owner_id,a.name owner_name,w.inr_minor::text,w.usdt_minor::text,w.state,w.created_at,w.completed_at,w.snapshot FROM wpay_auth.merchant_settlement_withdrawals w JOIN wpay_auth.accounts a ON a.id=w.merchant_id WHERE a.tenant_id=ANY($1) ORDER BY w.created_at DESC LIMIT 50",[tenants])).rows;
  return [...userRows,...merchantRows].sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at)).slice(0,100);
 }
 async settlements(account){
  if(account.account_type==='merchant')return this.withdrawals(account);
  if(!['admin','super_admin'].includes(account.account_type))throw Error('MERCHANT_ONLY');
  const tenants=await this.adminTenants(account);return (await this.pool.query("SELECT w.id,w.merchant_id,a.name merchant_name,w.inr_minor::text,w.usdt_minor::text,w.state,w.created_at,w.completed_at,w.snapshot FROM wpay_auth.merchant_settlement_withdrawals w JOIN wpay_auth.accounts a ON a.id=w.merchant_id WHERE a.tenant_id=ANY($1) ORDER BY w.created_at DESC LIMIT 100",[tenants])).rows;
 }
 async payins(account){
  if(account.account_type==='user')return (await this.pool.query(`SELECT o.reference,o.amount_minor::text,o.state,v.details->>'upiId' upi_id,o.created_at,o.paid_at FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations r ON r.id=o.reservation_id JOIN wpay_auth.business_bank_versions v ON v.bank_id=r.bank_id AND v.version=r.bank_version WHERE r.user_id=$1 ORDER BY o.created_at DESC LIMIT 25`,[account.id])).rows;
  if(account.account_type==='merchant')return (await this.pool.query(`SELECT o.reference,o.amount_minor::text,o.state,o.origin,o.created_at,o.paid_at,(SELECT state FROM wpay_auth.gateway_outbox x WHERE x.order_id=o.id ORDER BY x.created_at DESC LIMIT 1) callback_status FROM wpay_auth.gateway_orders o WHERE o.merchant_id=$1 ORDER BY o.created_at DESC LIMIT 25`,[account.id])).rows;
  const tenants=await this.adminTenants(account);return (await this.pool.query(`SELECT o.reference,a.name merchant_name,o.amount_minor::text,o.state,o.origin,o.created_at,o.paid_at FROM wpay_auth.gateway_orders o JOIN wpay_auth.accounts a ON a.id=o.merchant_id WHERE a.tenant_id=ANY($1) ORDER BY o.created_at DESC LIMIT 25`,[tenants])).rows;
 }
 async payouts(account){
  if(account.account_type==='user')return (await this.pool.query(`SELECT p.reference,p.amount_minor::text,CASE WHEN dr.outcome='payment_invalid' THEN 'reversed' ELSE p.state END state,c.state claim_state,p.created_at,p.completed_at FROM wpay_auth.payout_claims c JOIN wpay_auth.payout_orders p ON p.id=c.payout_id LEFT JOIN wpay_auth.payout_disputes d ON d.payout_id=p.id LEFT JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE c.user_id=$1 ORDER BY p.created_at DESC LIMIT 25`,[account.id])).rows;
  if(account.account_type==='merchant')return (await this.pool.query(`SELECT p.reference,p.amount_minor::text,CASE WHEN dr.outcome='payment_invalid' THEN 'reversed' ELSE p.state END state,p.percentage_fee_minor::text,p.fixed_fee_minor::text,p.created_at,p.completed_at FROM wpay_auth.payout_orders p LEFT JOIN wpay_auth.payout_disputes d ON d.payout_id=p.id LEFT JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE p.merchant_id=$1 ORDER BY p.created_at DESC LIMIT 25`,[account.id])).rows;
  const tenants=await this.adminTenants(account);return (await this.pool.query(`SELECT p.reference,a.name merchant_name,p.amount_minor::text,CASE WHEN dr.outcome='payment_invalid' THEN 'reversed' ELSE p.state END state,p.created_at,p.completed_at FROM wpay_auth.payout_orders p JOIN wpay_auth.accounts a ON a.id=p.merchant_id LEFT JOIN wpay_auth.payout_disputes d ON d.payout_id=p.id LEFT JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE a.tenant_id=ANY($1) ORDER BY p.created_at DESC LIMIT 25`,[tenants])).rows;
 }
 async parking(account){if(account.account_type!=='user')throw Error('USER_ONLY');return (await this.pool.query("SELECT id,amount_minor::text,state,created_at,closed_at FROM wpay_auth.parking_locks WHERE user_id=$1 ORDER BY created_at DESC LIMIT 25",[account.id])).rows;}
 async recent(account){const [p,q]=await Promise.all([this.payins(account),this.payouts(account)]);return [...p.map(x=>({...x,kind:'payin',at:x.paid_at||x.created_at})),...q.map(x=>({...x,kind:'payout',at:x.completed_at||x.created_at}))].sort((a,b)=>+new Date(b.at)-+new Date(a.at)).slice(0,10);}
 async today(account){
  if(account.account_type==='user'){
   const r=(await this.pool.query(`SELECT COALESCE(sum(o.amount_minor) FILTER(WHERE o.state='successful' AND (o.paid_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date),0)::text payin,COALESCE((SELECT sum(p.amount_minor) FROM wpay_auth.payout_claims c JOIN wpay_auth.payout_orders p ON p.id=c.payout_id WHERE c.user_id=$1 AND c.state='consumed' AND (p.completed_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')),0)::text payout,COALESCE((SELECT sum(amount_minor) FROM wpay_auth.parking_locks WHERE user_id=$1 AND state='completed' AND (COALESCE(closed_at,created_at) AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date),0)::text parking FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations br ON br.id=o.reservation_id WHERE br.user_id=$1`,[account.id])).rows[0];
   const commission=(await this.pool.query(`SELECT COALESCE(sum(CASE WHEN e.direction='credit' THEN e.amount_minor ELSE -e.amount_minor END),0)::text amount FROM wpay_auth.business_entries e JOIN wpay_auth.business_journals j ON j.id=e.journal_id WHERE e.owner_id=$1 AND e.currency='INR' AND e.ledger_type IN('user_commission','user_payout_commission','user_commission_adjustment') AND (j.created_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date`,[account.id])).rows[0].amount;return {...r,commission,window:'today IST'};
  }
  if(account.account_type==='merchant'){
   const r=(await this.pool.query(`SELECT COALESCE(sum(amount_minor) FILTER(WHERE state='successful' AND (paid_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date),0)::text payin,COALESCE((SELECT sum(p.amount_minor) FROM wpay_auth.payout_orders p WHERE p.merchant_id=$1 AND p.state='successful' AND (p.completed_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date AND NOT EXISTS(SELECT 1 FROM wpay_auth.payout_disputes d JOIN wpay_auth.payout_dispute_resolutions dr ON dr.dispute_id=d.id WHERE d.payout_id=p.id AND dr.outcome='payment_invalid')),0)::text payout FROM wpay_auth.gateway_orders WHERE merchant_id=$1`,[account.id])).rows[0];
   const fees=(await this.pool.query(`SELECT COALESCE(sum(CASE WHEN e.direction='credit' THEN e.amount_minor ELSE -e.amount_minor END),0)::text amount FROM wpay_auth.business_entries e JOIN wpay_auth.business_journals j ON j.id=e.journal_id WHERE e.owner_id=$1 AND e.currency='INR' AND e.ledger_type IN('merchant_platform_fee','merchant_payout_fee') AND (j.created_at AT TIME ZONE 'Asia/Kolkata')::date=(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')::date`,[account.id])).rows[0].amount;return {...r,fees,window:'today IST'};
  }
  const d=await this.adminSummary(account);return {total:String(BigInt(d.todayCollection||0)+BigInt(d.todayPayoutVolume||0)),payin:d.todayCollection,payout:d.todayPayoutVolume,fees:d.todayFees,commission:d.todayUserCommission,window:'today IST'};
 }
 async analytics(account){if(account.account_type==='user'){const s=await this.userSummary(account);return {payins:s.payins,payouts:s.payouts,totalVolume:String(BigInt(s.payins.volume||0)+BigInt(s.payouts.volume||0)+BigInt(s.parking.volume||0))};}if(account.account_type==='merchant'){const s=await this.merchantSummary(account);return {gateway:s.gateway,payouts:s.payouts,successfulPayoutVolumeMinor:s.successfulPayoutVolumeMinor,totalVolumeMinor:s.totalVolumeMinor};}return this.adminSummary(account);}
 async health(account){const s=await this.summary(account);return {account,s};}
 async alerts(account){
  const out=[];if(account.status!=='active')out.push('Account status: '+account.status);if(account.approval_status&&account.approval_status!=='approved')out.push('Approval: '+account.approval_status);
  if(account.account_type==='user'){const s=await this.userSummary(account);if(BigInt(s.capacity.available)<=0n&&!s.collectionAccess.unlimited_collection)out.push('Available capacity is zero.');if(BigInt(s.capacity.held)>0n)out.push('Capacity hold: '+money.inr(s.capacity.held));if(BigInt(s.commission.held)>0n)out.push('Commission hold: '+money.inr(s.commission.held));if(!Number(s.runningUpi))out.push('No running UPI route.');if(Number(s.deposits.pending)>0)out.push('Pending USDT deposits: '+s.deposits.pending);}
  else if(account.account_type==='merchant'){const s=await this.merchantSummary(account);if(BigInt(s.balance.merchantAvailable)<=0n)out.push('Available balance is zero.');if(BigInt(s.frozen)>0n)out.push('Frozen balance: '+money.inr(s.frozen));if(BigInt(s.balance.merchantHeld)>0n)out.push('Held balance: '+money.inr(s.balance.merchantHeld));if(BigInt(s.balance.merchantPayoutReserved)+BigInt(s.balance.merchantSettlementReserved)>0n)out.push('Reserved funds are active.');}
  else {const s=await this.adminSummary(account);if(BigInt(s.frozen)>0n)out.push('Scoped merchant frozen/reserved: '+money.inr(s.frozen));if(!Number(s.runningUpi))out.push('No running UPI in scope.');}
  return out;
 }
 async top(account,type){if(!['admin','super_admin'].includes(account.account_type))throw Error('ADMIN_REQUIRED');const tenants=await this.adminTenants(account);if(type==='merchant')return (await this.pool.query(`SELECT a.name,a.email,sum(o.amount_minor)::text volume FROM wpay_auth.gateway_orders o JOIN wpay_auth.accounts a ON a.id=o.merchant_id WHERE a.tenant_id=ANY($1) AND o.state='successful' GROUP BY a.id,a.name,a.email ORDER BY sum(o.amount_minor) DESC LIMIT 10`,[tenants])).rows;return (await this.pool.query(`SELECT a.name,a.email,sum(o.amount_minor)::text volume FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations r ON r.id=o.reservation_id JOIN wpay_auth.accounts a ON a.id=r.user_id WHERE a.tenant_id=ANY($1) AND o.state='successful' GROUP BY a.id,a.name,a.email ORDER BY sum(o.amount_minor) DESC LIMIT 10`,[tenants])).rows;}
}
module.exports={Source};