"use strict";
const {randomUUID}=require('node:crypto'),{AuthError}=require('../auth/runtime/errors'),{transaction}=require('../db/migrations'),v=require('../business/validation'),money=require('../business/money'),ledger=require('../business/ledger'),net=require('./networks'),{FundingProvider}=require('./provider');
async function retry(pool,fn){for(let attempt=0;;attempt++)try{return await transaction(pool,fn);}catch(e){if(!['40001','40P01'].includes(e.code)||attempt>=2)throw e;}}
class FundingWorkflow {
 constructor({provider=new FundingProvider()}={}){this.provider=provider;}
 async request(client,id){const r=(await client.query('SELECT * FROM wpay_auth.funding_requests WHERE id=$1',[v.id(id)])).rows[0];if(!r)throw new AuthError('FORBIDDEN');return r;}
 async event(c,r,kind,reason,provenance={},actor=null,journal=null){await c.query('INSERT INTO wpay_auth.funding_events(id,request_id,actor_id,kind,reason,provenance,journal_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),r.id,actor,kind,reason,provenance,journal]);}
 async state(c,r,state,reason){await c.query('UPDATE wpay_auth.funding_requests SET state=$2,reason=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1',[r.id,state,reason]);}
 async minimum(c,owner){const prior=(await c.query("SELECT 1 FROM wpay_auth.funding_requests WHERE owner_id=$1 AND state='confirmed' LIMIT 1",[owner])).rowCount>0;return prior?'1':net.MINIMUM;}
 async create(c,row,input){v.exactFields(input,['idempotencyKey','amountUsdt']);v.reference(input.idempotencyKey);const amount=money.fromDecimal(input.amountUsdt,'USDT');money.minor(amount);await ledger.lock(c);
  const digest=ledger.digest({amount}),old=(await c.query('SELECT * FROM wpay_auth.funding_requests WHERE owner_id=$1 AND idempotency_key=$2',[row.id,input.idempotencyKey])).rows[0];if(old){if(old.payload_digest!==digest)throw new AuthError('CONFLICT');return old;}
  const terms=(await c.query('SELECT id,version,settings,effective_at FROM wpay_auth.commercial_versions WHERE account_id=$1 AND effective_at<=CURRENT_TIMESTAMP ORDER BY version DESC LIMIT 1',[row.id])).rows[0];if(!terms)throw new AuthError('UNAVAILABLE');const n=net.network(terms.settings.depositNetwork);
  const minimum=await this.minimum(c,row.id);
  const snapshot={network:terms.settings.depositNetwork,chainId:n.chainId,token:n.token,decimals:6,address:terms.settings.depositAddress,amountMinor:amount,rate:terms.settings.inrPerUsdt,commercialId:terms.id,commercialVersion:terms.version,effectiveAt:terms.effective_at,minimumMinor:minimum,initialPolicy:'first-confirmed-transfer-2000-usdt',topupMinimumMinor:'1',finality:n.finality,confirmations:n.confirmations};
  const below=BigInt(amount)<BigInt(minimum),r=(await c.query('INSERT INTO wpay_auth.funding_requests(id,owner_id,tenant_id,idempotency_key,snapshot,payload_digest,state,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[randomUUID(),row.id,row.tenant_id,input.idempotencyKey,snapshot,digest,below?'review':'requested',below?'Below 2000 USDT minimum; received transfers remain in review':''])).rows[0];await this.event(c,r,'requested',r.reason||'Deposit request created; no funding credited',{},row.id);return r;
 }
 async claim(c,r,input,actor){v.exactFields(input,['requestId','txHash','eventIndex']);const key=net.transferKey(r.snapshot.network,input.txHash,input.eventIndex);await ledger.lock(c);r=await this.request(c,r.id);
  const claim=(await c.query('INSERT INTO wpay_auth.funding_claims(id,request_id,transfer_key,tx_hash,event_index) VALUES($1,$2,$3,$4,$5) ON CONFLICT(request_id,transfer_key) DO NOTHING RETURNING *',[randomUUID(),r.id,key,input.txHash,input.eventIndex])).rows[0]||(await c.query('SELECT * FROM wpay_auth.funding_claims WHERE request_id=$1 AND transfer_key=$2',[r.id,key])).rows[0];
  await c.query("INSERT INTO wpay_auth.funding_jobs(id,claim_id,state) VALUES($1,$2,'queued') ON CONFLICT(claim_id) DO NOTHING",[randomUUID(),claim.id]);
  if(!['confirmed','reversed','rejected'].includes(r.state))await this.state(c,r,'detected','Submitted transaction reference is not confirmation');await this.event(c,r,'reference_submitted','Transaction reference queued for independent verification',{transferKey:key},actor);return {state:['confirmed','reversed','rejected'].includes(r.state)?r.state:'detected',verificationSourceConfigured:this.provider.configured(r.snapshot.network)};
 }
 async ambiguous(c,r){const addressOwners=await c.query("SELECT DISTINCT account_id FROM wpay_auth.commercial_versions WHERE settings->>'depositNetwork'=$1 AND settings->>'depositAddress'=$2 UNION SELECT owner_id FROM wpay_auth.funding_requests WHERE snapshot->>'network'=$1 AND snapshot->>'address'=$2",[r.snapshot.network,r.snapshot.address]);
  const requests=await c.query("SELECT id FROM wpay_auth.funding_requests WHERE snapshot->>'network'=$1 AND snapshot->>'address'=$2 AND snapshot->>'amountMinor'=$3 AND state NOT IN('rejected','reversed')",[r.snapshot.network,r.snapshot.address,r.snapshot.amountMinor]);return addressOwners.rowCount!==1||requests.rowCount!==1;
 }
 validateEvidence(r,p){const s=r.snapshot;if(p.network!==s.network||p.token!==s.token||p.recipient!==s.address||p.amountMinor!==s.amountMinor||p.transferKey!==net.transferKey(s.network,p.txHash,p.eventIndex))throw new AuthError('EVIDENCE_REVIEW');}
 async eligibility(c,owner){await c.query("UPDATE wpay_auth.eligibility SET initial_deposit_satisfied=EXISTS(SELECT 1 FROM wpay_auth.funding_requests WHERE owner_id=$1 AND state='confirmed' AND (snapshot->>'amountMinor')::numeric>=2000000000) WHERE account_id=$1",[owner]);}
 async credit(c,r,p,source,actor,reason,{restore=false}={}){this.validateEvidence(r,p);if(BigInt(p.amountMinor)<BigInt(r.snapshot.minimumMinor||net.MINIMUM))throw new AuthError('BELOW_MINIMUM');const amount=net.conversion(p.amountMinor,r.snapshot.rate);
  const duplicate=(await c.query('SELECT * FROM wpay_auth.funding_transfers WHERE transfer_key=$1 OR request_id=$2',[p.transferKey,r.id])).rows;
  if(duplicate.length&& (duplicate.length!==1||duplicate[0].request_id!==r.id||duplicate[0].transfer_key!==p.transferKey))throw new AuthError('DUPLICATE_TRANSFER');
  if(r.state==='confirmed')return {state:'confirmed',alreadyCredited:true};if(r.state==='reversed'&&!restore)throw new AuthError('EVIDENCE_REVIEW');
  const owner=(await c.query('SELECT a.status,e.approval_status FROM wpay_auth.accounts a JOIN wpay_auth.eligibility e ON e.account_id=a.id WHERE a.id=$1 AND a.tenant_id=$2',[r.owner_id,r.tenant_id])).rows[0];if(!owner||owner.status!=='active'||owner.approval_status!=='approved')throw new AuthError('FORBIDDEN');
  if(!duplicate.length)await c.query('INSERT INTO wpay_auth.funding_transfers(transfer_key,request_id,network,token,tx_hash,event_index,recipient,amount_minor) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[p.transferKey,r.id,p.network,p.token,p.txHash,p.eventIndex,p.recipient,p.amountMinor]);
  const before=await ledger.summary(c,r.owner_id),version=r.accounting_version+1,journal=await ledger.post(c,{key:'funding:'+r.id+':'+version,referenceType:restore?'deposit_restoration':'usdt_deposit',referenceId:r.id,actorId:actor,source,snapshot:{funding:r.snapshot},metadata:{transferKey:p.transferKey,reason,provenance:p},entries:ledger.pair(r.owner_id,'capacity_allocated',amount)});
  await c.query("UPDATE wpay_auth.funding_requests SET state='confirmed',reason=$2,source=$3,credit_minor=$4,transfer_key=$5,accounting_version=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[r.id,reason,source,amount,p.transferKey,version]);await this.eligibility(c,r.owner_id);const after=await ledger.summary(c,r.owner_id);
  await this.event(c,r,restore?'restored':'confirmed',reason,{...p,source,capacityBefore:before,capacityAfter:after},actor,journal);
  await c.query('INSERT INTO wpay_auth.funding_notifications(id,owner_id,request_id,journal_id,kind,payload) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),r.owner_id,r.id,journal,restore?'deposit_restored':'deposit_confirmed',{creditMinor:amount,currency:'INR',source}]);return {state:'confirmed',creditMinor:amount,capacity:after,source};
 }
 async reverse(c,r,actor,reason,reference,source='manual_reversal'){if(r.state==='reversed')return {state:'reversed',alreadyReversed:true};if(r.state!=='confirmed')throw new AuthError('CONFLICT');const version=r.accounting_version+1;
  const journal=await ledger.post(c,{key:'funding:'+r.id+':'+version,referenceType:'deposit_reversal',referenceId:r.id,actorId:actor,source,snapshot:{funding:r.snapshot},metadata:{reason,reference,transferKey:r.transfer_key},entries:ledger.pair(r.owner_id,'capacity_allocated',r.credit_minor,'INR','debit')});
  await c.query("UPDATE wpay_auth.funding_requests SET state='reversed',accounting_version=$2,reason=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[r.id,version,reason]);await this.eligibility(c,r.owner_id);const after=await ledger.summary(c,r.owner_id);
  await c.query('INSERT INTO wpay_auth.business_reconciliation(id,owner_id,journal_id,reference,reason,signed_remaining,deficit_minor) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),r.owner_id,journal,r.id,reason,after.signedAvailable,after.deficit]);await this.event(c,r,'reversed',reason,{reference,source,capacityAfter:after},actor,journal);
  await c.query('INSERT INTO wpay_auth.funding_notifications(id,owner_id,request_id,journal_id,kind,payload) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),r.owner_id,r.id,journal,'deposit_reversed',{debitMinor:r.credit_minor,currency:'INR'}]);return {state:'reversed',capacity:after};
 }
 async review(c,r,input,actor){v.exactFields(input,['requestId','action','reason','evidenceReference','attributionReference','network','token','address','amountUsdt','txHash','eventIndex','reviewedFinal']);v.reason(input.reason);v.reference(input.evidenceReference);await ledger.lock(c);r=await this.request(c,r.id);
  if(input.action==='reject'){if(['confirmed','reversed'].includes(r.state))throw new AuthError('CONFLICT');await this.state(c,r,'rejected',input.reason);await this.event(c,r,'rejected',input.reason,{evidenceReference:input.evidenceReference},actor);return {state:'rejected'};}
  if(input.action==='reverse')return this.reverse(c,r,actor,input.reason,input.evidenceReference);
  if(!['confirm','restore'].includes(input.action)||input.reviewedFinal!==true)throw new AuthError('EVIDENCE_REVIEW');v.reference(input.attributionReference);
  const proof={network:input.network,token:input.token,recipient:input.address,amountMinor:money.fromDecimal(input.amountUsdt,'USDT'),txHash:input.txHash,eventIndex:input.eventIndex,transferKey:net.transferKey(input.network,input.txHash,input.eventIndex),evidenceReference:input.evidenceReference,attributionReference:input.attributionReference,finality:'manually_reviewed',blockchainVerified:false};this.validateEvidence(r,proof);
  const known=(await c.query("SELECT provenance FROM wpay_auth.funding_events WHERE request_id=$1 AND kind='provider_observation' AND provenance->>'transferKey'=$2 ORDER BY created_at DESC,id DESC LIMIT 1",[r.id,proof.transferKey])).rows[0];
  if(known&&(['confirming','detected','reorg'].includes(known.provenance.state)||(known.provenance.state==='review'&&known.provenance.reason!=='Verification source not configured')))throw new AuthError('EVIDENCE_REVIEW');
  await this.event(c,r,'manual_review',input.reason,proof,actor);
  if(BigInt(proof.amountMinor)<BigInt(r.snapshot.minimumMinor||net.MINIMUM)){await this.state(c,r,'review','Below 2000 USDT minimum; transfer retained for review');return {state:'review',reason:'BELOW_MINIMUM'};}
  return this.credit(c,r,proof,'manually_reviewed',actor,input.reason,{restore:input.action==='restore'});
 }
 async applyVerification(c,r,claim,p){await ledger.lock(c);r=await this.request(c,r.id);await this.event(c,r,'provider_observation',p.reason,{...p,transferKey:claim.transfer_key});
  if(p.state==='reorg'&&r.state==='confirmed'&&r.transfer_key===claim.transfer_key)return this.reverse(c,r,null,'Provider observed a canonical-chain reversal',claim.transfer_key,'blockchain_reorg');
  if(p.state!=='verified'){if(r.state==='confirmed'||r.state==='reversed')return {state:r.state};const state=['detected','confirming'].includes(p.state)?p.state:'review';await this.state(c,r,state,p.reason);return {state};}
  try{this.validateEvidence(r,p);if(+new Date(p.blockTime)<+r.created_at)throw new AuthError('EVIDENCE_REVIEW');if(await this.ambiguous(c,r)&&r.state!=='confirmed')throw new AuthError('AMBIGUOUS_TRANSFER');if(['rejected','reversed'].includes(r.state))throw new AuthError('EVIDENCE_REVIEW');return await this.credit(c,r,p,'blockchain_verified',null,'Independently verified token transfer');}
  catch(error){if(!(error instanceof AuthError))throw error;if(!['confirmed','reversed','rejected'].includes(r.state))await this.state(c,r,'review',error.message);await this.event(c,r,'verification_review',error.message,{code:error.code,transferKey:claim.transfer_key});return {state:['confirmed','reversed','rejected'].includes(r.state)?r.state:'review',reason:error.code};}
 }
 async runBatch(pool,{limit=10}={}){if(!Number.isInteger(limit)||limit<1||limit>10)throw Error('Invalid batch size');const results=[];
  // A crash on the final attempt must not strand a permanent running lease.
  await retry(pool,c=>c.query("UPDATE wpay_auth.funding_jobs SET state='review',lease_until=NULL,last_result='Retry budget exhausted after interrupted attempt',updated_at=CURRENT_TIMESTAMP WHERE id IN(SELECT id FROM wpay_auth.funding_jobs WHERE state='running' AND attempts>=5 AND lease_until<CURRENT_TIMESTAMP ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 10)"));
  for(let i=0;i<limit;i++){const job=await retry(pool,async c=>{const found=(await c.query("SELECT * FROM wpay_auth.funding_jobs WHERE attempts<5 AND ((state IN('queued','waiting') AND next_attempt_at<=CURRENT_TIMESTAMP) OR (state='running' AND lease_until<CURRENT_TIMESTAMP)) ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT 1")).rows[0];if(!found)return null;const leased=(await c.query("UPDATE wpay_auth.funding_jobs SET state='running',attempts=attempts+1,lease_until=CURRENT_TIMESTAMP+interval '90 seconds',updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING lease_until",[found.id])).rows[0];return {...found,...leased,attempts:found.attempts+1};});if(!job)break;
   const claim=(await pool.query('SELECT * FROM wpay_auth.funding_claims WHERE id=$1',[job.claim_id])).rows[0],r=await this.request(pool,claim.request_id),snapshotDigest=net.binding(r.snapshot),last=(await pool.query("SELECT provenance->>'blockHash' block FROM wpay_auth.funding_events WHERE request_id=$1 AND kind IN('confirmed','restored') ORDER BY created_at DESC,id DESC LIMIT 1",[r.id])).rows[0];
   // No database transaction or business mutex is held while contacting a provider.
   const proof=await this.provider.verify(r.snapshot,claim,last?.block||null);
   const result=await retry(pool,async c=>{const current=await this.request(c,r.id);if(net.binding(current.snapshot)!==snapshotDigest)throw new AuthError('CONFLICT');const locked=(await c.query('SELECT * FROM wpay_auth.funding_jobs WHERE id=$1 FOR UPDATE',[job.id])).rows[0];if(locked.state!=='running'||locked.attempts!==job.attempts||+locked.lease_until!==+job.lease_until)return {state:'superseded'};
    const applied=await this.applyVerification(c,current,claim,proof),waiting=['waiting','confirming','detected'].includes(proof.state)&&job.attempts<5;await c.query("UPDATE wpay_auth.funding_jobs SET state=$2,last_result=$3,lease_until=NULL,next_attempt_at=CURRENT_TIMESTAMP+interval '1 minute',updated_at=CURRENT_TIMESTAMP WHERE id=$1",[job.id,waiting?'waiting':applied.state==='confirmed'?'done':'review',proof.reason]);return applied;});results.push(result);
  }return results;
 }
}
module.exports={FundingWorkflow,retry};
