'use strict';
const {parse}=require('./commands'),{isController}=require('./access'),format=require('./format');
class Bot{
 constructor({telegram,store,source,username}){Object.assign(this,{telegram,store,source,username});}
 async update(payload,updateId){if(payload.kind==='message')return this.message(payload.message,updateId);if(payload.kind==='callback')return this.callback(payload.callback,updateId);}
 async message(m,updateId){if(!m?.from||m.from.is_bot||!['group','supergroup'].includes(m.chat?.type))return;
  if(typeof m.text==='string'){let cmd;try{cmd=parse(m.text,this.username);}catch{if(isController(m.from.id))await this.telegram.text(m.chat.id,'Invalid /adduser email.');return;}if(cmd){if(!isController(m.from.id))return;return this.store.exclusive(m.chat.id,async()=>{const user=await this.source.user(cmd.email);if(!user||user.status!=='active'||user.approval_status!=='approved'){await this.telegram.text(m.chat.id,'WPay User not found or not active/approved.');return;}await this.store.bind(m.chat,user,m.from.id);await this.telegram.text(m.chat.id,format.binding(user));});}}
  if(m.document){const binding=await this.store.binding(m.chat.id);if(!binding)return;const user=await this.source.activeUser(binding.user_id);if(!user||user.status!=='active'||user.approval_status!=='approved'){await this.telegram.text(m.chat.id,format.error('USER_NOT_ACTIVE'));return;}if(!Number.isSafeInteger(m.document.file_size)||m.document.file_size<1){await this.telegram.text(m.chat.id,'Invalid statement attachment.');return;}const imp=await this.store.createImport({chatId:m.chat.id,userId:user.id,uploader:m.from.id,document:m.document});await this.telegram.text(m.chat.id,format.received(imp.file_name));}}
 async callback(q){if(!q?.from||q.from.is_bot||typeof q.data!=='string'||!q.data.startsWith('stmt:'))return;const token=q.data.slice(5);if(!/^[A-Za-z0-9_-]{16}$/.test(token))return;const choice=await this.store.choice(token);if(!choice)return this.telegram.call('answerCallbackQuery',{callback_query_id:q.id,text:'This selection is no longer available.'});const chatId=q.message?.chat?.id;if(Number(chatId)!==Number(choice.chat_id))return;const selected=await this.store.selectChoice(token,q.from.id,isController(q.from.id));if(selected?.denied)return this.telegram.call('answerCallbackQuery',{callback_query_id:q.id,text:'Only the statement uploader or an authorized controller can select the UPI.',show_alert:true});if(!selected)return this.telegram.call('answerCallbackQuery',{callback_query_id:q.id,text:'This statement is already selected or processed.'});await this.telegram.call('answerCallbackQuery',{callback_query_id:q.id,text:'UPI selected. Processing statement…'});await this.telegram.text(choice.chat_id,`UPI selected: ${selected.selected_upi}\nParsing statement and reconciling credit UTRs…`);}
}
module.exports={Bot};