'use strict';
const {createHash}=require('node:crypto'),parser=require('./parser'),format=require('./format');
const digest=b=>createHash('sha256').update(b).digest('hex');
const permanentProbe=new Set(['FILE_SIZE_INVALID','UNSUPPORTED_FILE','INVALID_PDF','PASSWORD_PROTECTED_PDF','PDF_NO_TEXT_LAYER','INVALID_XLS','INVALID_XLSX','INVALID_CSV','INVALID_WORKBOOK','EMPTY_STATEMENT','PDF_RUNTIME_UNAVAILABLE','PDF_WORKER_FAILED','PDF_OPEN_FAILED','PDF_TEXT_EXTRACTION_FAILED','PDF_CONVERTER_UNAVAILABLE','PDF_CONVERSION_TIMEOUT','PDF_CONVERSION_FAILED','PARSER_MEMORY_LIMIT','PARSER_WORKER_ERROR','PARSER_EXIT']);
const permanentParse=new Set([...permanentProbe,'FILE_CHANGED','USER_NOT_ACTIVE','UPI_NOT_RUNNING']);
function codeOf(e,fallback){const raw=String(e?.message||fallback);return /^[A-Z0-9_]{1,80}$/.test(raw)?raw:fallback;}
async function step(code,fn){try{return await fn();}catch(e){const known=codeOf(e,'');if(known)throw Error(known);throw Error(code);}}
async function processUpdate({job,bot,store,onError=()=>{}}){await store.attemptUpdate(job.update_id);try{await bot.update(job.payload,job.update_id);await store.markUpdate(job.update_id);}catch{onError('STATEMENT_BOT_UPDATE_FAILED');}}
async function processProbe({imp,telegram,store,source,onError=()=>{}}){const locked=await store.startAttempt(imp.id,'queued_probe');if(!locked)return;try{const bytes=await step('TELEGRAM_FILE_DOWNLOAD_FAILED',()=>telegram.file(locked.telegram_file_id,parser.MAX_BYTES)),probe=await step('STATEMENT_PARSER_PROBE_FAILED',()=>parser.run(bytes,'probe')),row=await step('STATEMENT_SET_PROBE_FAILED',()=>store.setProbe(locked.id,{format:probe.format,digest:digest(bytes)}));if(!row)return;const user=await step('STATEMENT_USER_LOOKUP_FAILED',()=>source.activeUser(row.user_id));if(!user||user.status!=='active'||user.approval_status!=='approved'){await store.failImport(row.id,'USER_NOT_ACTIVE','rejected');await telegram.text(row.chat_id,format.error('USER_NOT_ACTIVE'));return;}const upis=await step('STATEMENT_UPI_LOOKUP_FAILED',()=>source.upis(row.user_id));if(!upis.length){await store.failImport(row.id,'NO_RUNNING_UPI','rejected');await telegram.text(row.chat_id,format.error('NO_RUNNING_UPI'));return;}const choices=await step('STATEMENT_CHOICES_FAILED',()=>store.choices(row.id,upis)),keyboard=choices.map(x=>[{text:(x.upiId+(x.bankName?' · '+x.bankName:'')).slice(0,60),callback_data:'stmt:'+x.token}]);await step('STATEMENT_PROMPT_SEND_FAILED',()=>telegram.text(row.chat_id,format.upiPrompt(row),{reply_markup:{inline_keyboard:keyboard}}));}catch(e){const code=codeOf(e,'STATEMENT_PROBE_UNKNOWN');const final=permanentProbe.has(code)||locked.attempts>=4;await store.failImport(locked.id,code,final?'failed':'queued_probe');if(final)await telegram.text(locked.chat_id,format.error(code)).catch(()=>{});onError('STATEMENT_BOT_PROBE_FAILED_'+code);}}
async function processParse({imp,telegram,store,source,onError=()=>{}}){const locked=await store.startAttempt(imp.id,'queued_parse');if(!locked)return;try{const user=await step('STATEMENT_USER_LOOKUP_FAILED',()=>source.activeUser(locked.user_id));if(!user||user.status!=='active'||user.approval_status!=='approved')throw Error('USER_NOT_ACTIVE');const bytes=await step('TELEGRAM_FILE_DOWNLOAD_FAILED',()=>telegram.file(locked.telegram_file_id,parser.MAX_BYTES));if(digest(bytes)!==locked.file_digest)throw Error('FILE_CHANGED');const parsed=await step('STATEMENT_PARSER_PARSE_FAILED',()=>parser.run(bytes,'parse'));if(parsed.format!==locked.detected_format)throw Error('FILE_CHANGED');const result=await step('STATEMENT_RECONCILE_FAILED',()=>source.reconcile(locked,parsed)),done=await step('STATEMENT_COMPLETE_FAILED',()=>store.complete(locked.id,result));await step('STATEMENT_SUMMARY_SEND_FAILED',()=>telegram.text(done.chat_id,format.summary(done,result)));}catch(e){const code=codeOf(e,'STATEMENT_PARSE_UNKNOWN');const final=permanentParse.has(code)||locked.attempts>=4;await store.failImport(locked.id,code,final?'failed':'queued_parse');if(final)await telegram.text(locked.chat_id,format.error(code)).catch(()=>{});onError('STATEMENT_BOT_PARSE_FAILED_'+code);}}
module.exports={processUpdate,processProbe,processParse,permanentProbe,permanentParse,codeOf,step};