'use strict';
const {parentPort,workerData}=require('node:worker_threads');
const {spawnSync}=require('node:child_process');
const {createHash}=require('node:crypto');
const {detect}=require('./file-detect'),{parseRows}=require('./parser-core'),money=require('./money'),{csv}=require('./normalize');
let XLSX;
function xlsx(){return XLSX||(XLSX=require('../../../public/vendor/smart-upi-parser-runtime/xlsx.full.min.js'));}
function formatCell(value){if(value instanceof Date){const p=n=>String(n).padStart(2,'0');return `${p(value.getDate())}/${p(value.getMonth()+1)}/${value.getFullYear()}`;}return value==null?'':String(value).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();}
function readTabular(bytes){const lib=xlsx();let wb;try{wb=lib.read(new Uint8Array(bytes),{type:'array',cellDates:true,raw:false});}catch{throw Error('INVALID_WORKBOOK');}if(!wb.SheetNames?.length)throw Error('INVALID_WORKBOOK');const rows=[];let index=0;for(const name of wb.SheetNames){const sheet=wb.Sheets[name];if(!sheet)continue;const grid=lib.utils.sheet_to_json(sheet,{header:1,blankrows:false,defval:'',raw:false});for(const raw of grid){const cells=Array.from(raw||[]).map(formatCell);while(cells.length&&cells.at(-1)==='')cells.pop();const text=cells.join(' ').trim();if(text)rows.push({cells,text,source:name,index:index++});}}if(!rows.length)throw Error('EMPTY_STATEMENT');return rows;}
function classifyPdfFailure(result){const stderr=String(result?.stderr||'').slice(0,4000);if(result?.error?.code==='ENOENT')return'PDF_CONVERTER_UNAVAILABLE';if(result?.error?.code==='ETIMEDOUT'||result?.signal==='SIGTERM')return'PDF_CONVERSION_TIMEOUT';if(/password|encrypted|incorrect password/i.test(stderr))return'PASSWORD_PROTECTED_PDF';if(/syntax error|damaged|couldn.t find trailer|xref|not a pdf/i.test(stderr))return'INVALID_PDF';return'PDF_CONVERSION_FAILED';}
function convertPdfToText(bytes){const result=spawnSync('pdftotext',['-layout','-enc','UTF-8','-','-'],{input:Buffer.from(bytes),encoding:'utf8',timeout:45000,maxBuffer:24*1024*1024,windowsHide:true});if(result.error||result.status!==0)throw Error(classifyPdfFailure(result));const text=String(result.stdout||'').replace(/\u0000/g,'').replace(/\r\n?/g,'\n');if(!text.trim())throw Error('PDF_NO_TEXT_LAYER');return text;}
function splitColumns(line){const trimmed=line.replace(/\t/g,'    ').trimEnd();if(!trimmed.trim())return[];let cells=trimmed.trim().split(/\s{2,}/).map(x=>x.trim()).filter(Boolean);if(cells.length<2)cells=trimmed.trim().split(/\s+/).filter(Boolean);return cells;}
function textToRows(text){const rows=[];let index=0,page=1;for(const raw of String(text).split('\n')){if(raw.includes('\f'))page++;const clean=raw.replace(/\f/g,'').trimEnd();if(!clean.trim())continue;const cells=splitColumns(clean),joined=cells.join(' ').trim();if(joined)rows.push({cells,text:joined,source:`page ${page}`,index:index++});}if(!rows.length)throw Error('PDF_NO_TEXT_LAYER');return rows;}
function readPdf(bytes){return textToRows(convertPdfToText(bytes));}
async function probePdf(bytes){const text=convertPdfToText(bytes);return /\S/.test(text);}
async function probeWorkbook(bytes){try{return !!readTabular(bytes).length;}catch{return false;}}
async function parseBuffer(bytes){const format=await detect(bytes,{probePdf,probeWorkbook}),convertedText=format==='pdf'?convertPdfToText(bytes):null,rows=format==='pdf'?textToRows(convertedText):readTabular(bytes),parsed=parseRows(rows);let credit=0n,debit=0n,creditCount=0,debitCount=0;for(const t of parsed.transactions){const n=BigInt(money.fromDecimal(t.amount));if(t.direction==='credit'){credit+=n;creditCount++;}else{debit+=n;debitCount++;}}const seen=new Set(),creditUtrs=[];for(const t of parsed.transactions){if(t.direction!=='credit'||!t.isUpi||!/^[0-9]{12}$/.test(t.utr||''))continue;const key=`${t.date}|${t.utr}|${t.amount}`;if(seen.has(key))continue;seen.add(key);creditUtrs.push({date:t.date,utr:t.utr,amountMinor:money.fromDecimal(t.amount)});}const normalized=csv(parsed.transactions);return{format,rowsScanned:parsed.rowsScanned,creditCount,debitCount,totalCreditMinor:credit.toString(),totalDebitMinor:debit.toString(),creditUtrs,convertedTextDigest:convertedText?createHash('sha256').update(convertedText).digest('hex'):null,convertedTextBytes:convertedText?Buffer.byteLength(convertedText):0,normalizedCsvDigest:createHash('sha256').update(normalized).digest('hex'),normalizedCsvBytes:Buffer.byteLength(normalized)};}
async function main(){const bytes=Buffer.from(workerData.bytes);if(workerData.mode==='probe'){const format=await detect(bytes,{probePdf,probeWorkbook});return parentPort.postMessage({ok:true,format});}parentPort.postMessage({ok:true,...await parseBuffer(bytes)});}
if(parentPort)main().catch(e=>parentPort.postMessage({ok:false,error:String(e?.message||'PARSE_FAILED').slice(0,80)}));
module.exports={parseBuffer,probePdf,probeWorkbook,readTabular,readPdf,convertPdfToText,textToRows,classifyPdfFailure};