'use strict';
const {timingSafeEqual}=require('node:crypto'),{Telegram}=require('./transport'),{Store}=require('./store'),{Source}=require('./source'),{Bot}=require('./engine'),{parse}=require('./commands'),{isController}=require('./access'),{MENU}=require('./catalog'),parser=require('./parser'),jobs=require('./jobs');
const PATH='/integrations/wpay-statement-bot/webhook';
function secretOk(a,b){if(typeof a!=='string'||typeof b!=='string'||b.length<16)return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
function create({pool,gateway=null,operational=null,legacy=null,env=process.env,fetcher,onError=()=>{}}){const token=env.WPAY_STATEMENT_BOT_TOKEN;if(!token)return null;const secret=env.WPAY_STATEMENT_BOT_WEBHOOK_SECRET||env.TELEGRAM_WEBHOOK_SECRET,origin=env.WPAY_HOSTED_ORIGIN;if(!secretOk(secret,secret))throw Error('STATEMENT_BOT_SECRET_INVALID');const u=new URL(origin);if(u.protocol!=='https:'||u.origin!==origin)throw Error('STATEMENT_BOT_ORIGIN_INVALID');const telegram=new Telegram({token,fetcher}),store=new Store(pool),source=new Source({pool,gateway,operational,legacy});let bot,timer,inflight,running=false,stopped=false,starting=false;
 const schedule=d=>{clearTimeout(timer);timer=setTimeout(()=>{inflight=cycle();},d);timer.unref?.();};
 async function cycle(){if(stopped||running)return;running=true;try{for(const job of await store.pendingUpdates()){if(stopped)break;await jobs.processUpdate({job,bot,store,onError});}for(const imp of await store.imports('queued_probe')){if(stopped)break;await jobs.processProbe({imp,telegram,store,source,onError});}for(const imp of await store.imports('queued_parse')){if(stopped)break;await jobs.processParse({imp,telegram,store,source,onError});}}catch{onError('STATEMENT_BOT_WORKER_FAILED');}finally{running=false;if(!stopped)schedule(1500);}}
 async function initialize(){const me=await telegram.call('getMe');if(!me?.is_bot||!me.username)throw Error('STATEMENT_BOT_IDENTITY_INVALID');bot=new Bot({telegram,store,source,username:me.username});await telegram.call('setWebhook',{url:origin+PATH,secret_token:secret,allowed_updates:['message','callback_query'],max_connections:1});await telegram.call('setMyCommands',{commands:MENU});inflight=cycle();}
 async function start(){if(stopped||starting||bot)return;starting=true;try{await initialize();}catch{onError('STATEMENT_BOT_START_FAILED');if(!stopped)schedule(30000);}finally{starting=false;}}
 async function webhook(req,res,{readBody,send}){if(req.url===PATH+'/health'&&req.method==='GET'){send(res,bot?200:503,{ready:!!bot});return true;}if(req.url!==PATH)return false;if(req.method!=='POST'){send(res,405,{ok:false});return true;}if(!secretOk(req.headers['x-telegram-bot-api-secret-token'],secret)){send(res,403,{ok:false});return true;}if(!bot){send(res,503,{ok:false});return true;}const update=await readBody(req,65536);if(!Number.isSafeInteger(update.update_id)||update.update_id<0){send(res,400,{ok:false});return true;}const m=update.message,q=update.callback_query;let payload=null;if(m?.from&&!m.from.is_bot&&!m.sender_chat&&['group','supergroup'].includes(m.chat?.type)&&Number.isSafeInteger(m.chat.id)&&m.chat.id<0&&Number.isSafeInteger(m.from.id)){
   if(typeof m.text==='string'&&m.text.length<=340){let recognized=false;try{recognized=!!parse(m.text,bot.username);}catch{recognized=true;}if(recognized&&isController(m.from.id))payload={kind:'message',message:{text:m.text,from:{id:m.from.id,is_bot:false},chat:{id:m.chat.id,type:m.chat.type}}};}
   else if(m.document&&typeof m.document.file_id==='string'&&typeof m.document.file_unique_id==='string'&&Number.isSafeInteger(m.document.file_size)&&m.document.file_size>0&&m.document.file_size<=parser.MAX_BYTES){payload={kind:'message',message:{from:{id:m.from.id,is_bot:false},chat:{id:m.chat.id,type:m.chat.type},document:{file_id:m.document.file_id,file_unique_id:m.document.file_unique_id,file_name:String(m.document.file_name||'statement').slice(0,180),mime_type:String(m.document.mime_type||'').slice(0,100),file_size:m.document.file_size}}};}
  }else if(q?.from&&!q.from.is_bot&&typeof q.id==='string'&&typeof q.data==='string'&&q.data.length<=64&&['group','supergroup'].includes(q.message?.chat?.type)&&Number.isSafeInteger(q.message.chat.id)&&q.message.chat.id<0){payload={kind:'callback',callback:{id:q.id,data:q.data,from:{id:q.from.id,is_bot:false},message:{chat:{id:q.message.chat.id,type:q.message.chat.type}}}};}
  if(payload)await store.accept(update.update_id,payload);send(res,200,{ok:true});return true;}
 return {PATH,start,webhook,async stop(){stopped=true;clearTimeout(timer);await inflight;}};}
module.exports={create,PATH,secretOk};