'use strict';
const {createHash,randomUUID}=require('node:crypto');
const hash=value=>createHash('sha256').update(String(value)).digest('hex');
class Source{
 constructor({pool,gateway=null,operational=null,legacy=null}){this.pool=pool;this.gateway=gateway;this.operational=operational;this.legacy=legacy;}
 async user(email){return (await this.pool.query(`SELECT a.id,a.name,a.email,a.tenant_id,a.status,e.approval_status FROM wpay_auth.accounts a JOIN wpay_auth.eligibility e ON e.account_id=a.id WHERE lower(a.email)=lower($1) AND a.account_type='user' LIMIT 1`,[email])).rows[0]||null;}
 async activeUser(id){return (await this.pool.query(`SELECT a.id,a.name,a.email,a.tenant_id,a.status,e.approval_status FROM wpay_auth.accounts a JOIN wpay_auth.eligibility e ON e.account_id=a.id WHERE a.id=$1 AND a.account_type='user'`,[id])).rows[0]||null;}
 async upis(userId){return (await this.pool.query(`SELECT b.id,b.version,v.details->>'upiId' AS "upiId",v.details->>'bankName' AS "bankName" FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version WHERE b.owner_id=$1 AND b.status='running' AND NOT b.frozen AND NOT b.deactivated ORDER BY b.created_at,b.id`,[userId])).rows;}
 async selectedUpi(userId,bankId,version){return (await this.pool.query(`SELECT b.id,b.version,v.details->>'upiId' AS "upiId" FROM wpay_auth.business_bank_accounts b JOIN wpay_auth.business_bank_versions v ON v.bank_id=b.id AND v.version=b.version WHERE b.owner_id=$1 AND b.id=$2 AND b.version=$3 AND b.status='running' AND NOT b.frozen AND NOT b.deactivated`,[userId,bankId,version])).rows[0]||null;}
 async operationalLinks(userId){return (await this.pool.query(`SELECT device_ref,valid_from,valid_until,pairing_id,valid_from AS authority_at FROM wpay_auth.paired_devices WHERE owner_id=$1 AND revoked_at IS NULL AND valid_until>CURRENT_TIMESTAMP ORDER BY valid_from DESC LIMIT 100`,[userId])).rows;}
 async operationalHasUtr(utr,links){if(!this.operational?.transactions||!links.length)return false;try{const result=await this.operational.transactions(links,{utr});return Array.isArray(result?.rows)&&result.rows.some(r=>r.utr===utr);}catch{throw Error('OPERATIONAL_SOURCE_UNAVAILABLE');}}
 async legacyLinks(userId){return (await this.pool.query(`SELECT l.resource_id,l.resource_kind,GREATEST(l.valid_from,p.valid_from) AS valid_from,LEAST(l.valid_until,p.valid_until) AS valid_until FROM wpay_auth.resource_links l JOIN wpay_auth.resource_links p ON p.id=l.parent_id AND p.account_id=l.account_id AND p.source_id=l.source_id WHERE l.account_id=$1 AND l.source_id='legacy-primary' AND l.resource_kind IN('device','statement_import') AND p.resource_kind='receiving_account' AND l.status='verified' AND p.status='verified' AND l.revoked_at IS NULL AND p.revoked_at IS NULL AND l.consent_at<=CURRENT_TIMESTAMP AND p.consent_at<=CURRENT_TIMESTAMP AND l.verified_at<=CURRENT_TIMESTAMP AND p.verified_at<=CURRENT_TIMESTAMP AND l.valid_from<=CURRENT_TIMESTAMP AND p.valid_from<=CURRENT_TIMESTAMP AND l.valid_until>CURRENT_TIMESTAMP AND p.valid_until>CURRENT_TIMESTAMP ORDER BY l.id LIMIT 100`,[userId])).rows;}
 async legacyHasUtr(utr,links){if(!this.legacy?.read||!links.length)return false;try{for(const link of links){const view=link.resource_kind==='device'?'transactions':'statement',result=await this.legacy.read(link,view,'9223372036854775807',{utr});if(Array.isArray(result?.rows)&&result.rows.some(r=>String(r.utr)===utr))return true;}return false;}catch{throw Error('LEGACY_SOURCE_UNAVAILABLE');}}
 async existingUtr(c,utr,digest){const checks=await Promise.all([
  c.query('SELECT 1 FROM wpay_auth.statement_bot_credits WHERE utr=$1 LIMIT 1',[utr]),
  c.query('SELECT 1 FROM wpay_auth.bank_statement_credits WHERE utr=$1 LIMIT 1',[utr]),
  c.query('SELECT 1 FROM wpay_auth.business_financial_events WHERE utr_digest=$1 LIMIT 1',[digest]),
  c.query('SELECT 1 FROM wpay_auth.gateway_claims WHERE utr_digest=$1 LIMIT 1',[digest])
 ]);return checks.some(x=>x.rowCount>0);}
 async matchOrder(c,imp,tx,digest){const rows=(await c.query(`SELECT DISTINCT o.*,EXISTS(SELECT 1 FROM wpay_auth.business_financial_events f WHERE f.reservation_id=r.id AND f.utr_digest=$5) AS financial_match,EXISTS(SELECT 1 FROM wpay_auth.gateway_claims gc WHERE gc.order_id=o.id AND gc.utr_digest=$5) AS claim_match FROM wpay_auth.gateway_orders o JOIN wpay_auth.business_reservations r ON r.id=o.reservation_id WHERE r.user_id=$1 AND r.bank_id=$2 AND r.bank_version=$3 AND o.amount_minor=$4 AND (EXISTS(SELECT 1 FROM wpay_auth.business_financial_events f WHERE f.reservation_id=r.id AND f.utr_digest=$5) OR EXISTS(SELECT 1 FROM wpay_auth.gateway_claims gc WHERE gc.order_id=o.id AND gc.utr_digest=$5)) ORDER BY o.created_at DESC LIMIT 3`,[imp.user_id,imp.selected_bank_id,imp.selected_bank_version,tx.amountMinor,digest])).rows;return rows.length===1?rows[0]:null;}
 async callbackState(order){return (await this.pool.query('SELECT * FROM wpay_auth.gateway_outbox WHERE order_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1',[order.id])).rows[0]||null;}
 async ensureCallback(order){let event=await this.callbackState(order);if(event?.state==='delivered')return'already_delivered';if(event?.state==='leased')return'queued';if(event&&['pending','failed'].includes(event.state)&&Number(event.attempts)<8){await this.pool.query("UPDATE wpay_auth.gateway_outbox SET state='pending',next_attempt_at=CURRENT_TIMESTAMP,lease_id=NULL,lease_until=NULL WHERE id=$1",[event.id]);return'queued';}if(event?.state==='failed'&&Number(event.attempts)>=8)return'exhausted';if(event?.state==='unconfigured')return'pending';if(!event&&this.gateway?.emit){const c=await this.pool.connect();try{await c.query('BEGIN');await this.gateway.emit(c,order,'payment.recovered');await c.query('COMMIT');return'queued';}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}return'pending';}
 async verifyIfNeeded(order,tx){if(order.state==='successful')return order;if(!order.claim_match||!this.gateway?.verifyOrder)return order;try{const r=await this.gateway.verifyOrder(order.id,{expectedUtr:tx.utr});if(r?.status==='successful')return (await this.pool.query('SELECT * FROM wpay_auth.gateway_orders WHERE id=$1',[order.id])).rows[0]||order;}catch{}return order;}
 async reconcile(imp,parsed){const currentUpi=await this.selectedUpi(imp.user_id,imp.selected_bank_id,imp.selected_bank_version);if(!currentUpi||currentUpi.upiId!==imp.selected_upi)throw Error('UPI_NOT_RUNNING');const [operationalLinks,legacyLinks]=await Promise.all([this.operational?.transactions?this.operationalLinks(imp.user_id):Promise.resolve([]),this.legacy?.read?this.legacyLinks(imp.user_id):Promise.resolve([])]),queuedOrders=new Set(),result={...parsed,creditUtrCount:parsed.creditUtrs.length,newUtrCount:0,duplicateUtrCount:0,callbackDelivered:0,callbackAlreadyDelivered:0,callbackQueued:0,callbackPending:0,callbackExhausted:0};for(const tx of parsed.creditUtrs){const digest=hash(tx.utr),operationalDuplicate=await this.operationalHasUtr(tx.utr,operationalLinks),legacyDuplicate=await this.legacyHasUtr(tx.utr,legacyLinks),c=await this.pool.connect();let duplicate,order;try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,57415962))',['statement-utr:'+tx.utr]);duplicate=operationalDuplicate||legacyDuplicate||await this.existingUtr(c,tx.utr,digest);order=await this.matchOrder(c,imp,tx,digest);if(!duplicate){const inserted=await c.query(`INSERT INTO wpay_auth.statement_bot_credits(id,import_id,user_id,bank_id,bank_version,upi_id,txn_date,utr,amount_minor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(utr) DO NOTHING RETURNING id`,[randomUUID(),imp.id,imp.user_id,imp.selected_bank_id,imp.selected_bank_version,imp.selected_upi,tx.date,tx.utr,tx.amountMinor]);duplicate=!inserted.rowCount;}await c.query('COMMIT');}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}if(duplicate)result.duplicateUtrCount++;else result.newUtrCount++;if(!order){result.callbackPending++;continue;}order=await this.verifyIfNeeded(order,tx);if(order.state!=='successful'){result.callbackPending++;continue;}const state=await this.ensureCallback(order);if(state==='already_delivered')result.callbackAlreadyDelivered++;else if(state==='queued'){result.callbackQueued++;queuedOrders.add(order.id);}else if(state==='exhausted')result.callbackExhausted++;else result.callbackPending++;}
 if(result.callbackQueued&&this.gateway?.dispatch){for(let i=0;i<Math.min(result.callbackQueued,5);i++)try{await this.gateway.dispatch();}catch{}for(const id of queuedOrders){const e=await this.callbackState({id});if(e?.state==='delivered')result.callbackDelivered++;}result.callbackQueued=Math.max(0,result.callbackQueued-result.callbackDelivered);}
 return result;}
 async adminCredits({offset=0,limit=200}={}){return (await this.pool.query(`SELECT c.id,c.utr,c.amount_minor::text,c.txn_date,c.created_at,c.import_id,c.bank_id,c.bank_version,c.upi_id,c.user_id,a.name AS user_name,a.email AS user_email FROM wpay_auth.statement_bot_credits c JOIN wpay_auth.accounts a ON a.id=c.user_id ORDER BY c.created_at DESC,c.id LIMIT $1 OFFSET $2`,[limit,offset])).rows;}
}
module.exports={Source,hash};