'use strict';
const {AsyncLocalStorage}=require('node:async_hooks'),{randomUUID,randomBytes}=require('node:crypto');
class Store{
 constructor(pool){this.pool=pool;this.context=new AsyncLocalStorage();}
 db(){return this.context.getStore()||this.pool;}
 async exclusive(chatId,fn){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='2s'");await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,57415961))',['statement-bot:'+chatId]);const result=await this.context.run(c,fn);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async accept(updateId,payload){await this.pool.query('INSERT INTO wpay_auth.statement_bot_updates(update_id,payload) VALUES($1,$2) ON CONFLICT DO NOTHING',[updateId,payload]);}
 async pendingUpdates(){return (await this.pool.query('SELECT update_id,payload,attempts FROM wpay_auth.statement_bot_updates WHERE NOT processed AND attempts<5 ORDER BY update_id LIMIT 10')).rows;}
 async attemptUpdate(id){await this.pool.query('UPDATE wpay_auth.statement_bot_updates SET attempts=attempts+1 WHERE update_id=$1',[id]);}
 async markUpdate(id){await this.db().query('UPDATE wpay_auth.statement_bot_updates SET processed=true WHERE update_id=$1',[id]);}
 async bind(chat,user,actor){const db=this.db(),prior=(await db.query('SELECT user_id FROM wpay_auth.statement_bot_groups WHERE chat_id=$1',[chat.id])).rows[0];if(prior&&prior.user_id!==user.id){await db.query("UPDATE wpay_auth.statement_bot_imports SET state='rejected',last_error='GROUP_REBOUND',updated_at=CURRENT_TIMESTAMP WHERE chat_id=$1 AND state IN('queued_probe','probing','waiting_upi','queued_parse','processing')",[chat.id]);await db.query("UPDATE wpay_auth.statement_bot_choices SET consumed_at=COALESCE(consumed_at,CURRENT_TIMESTAMP) WHERE import_id IN(SELECT id FROM wpay_auth.statement_bot_imports WHERE chat_id=$1 AND last_error='GROUP_REBOUND')",[chat.id]);}return (await db.query(`INSERT INTO wpay_auth.statement_bot_groups(chat_id,chat_type,user_id,bound_by,updated_at)
  VALUES($1,$2,$3,$4,CURRENT_TIMESTAMP) ON CONFLICT(chat_id) DO UPDATE SET chat_type=EXCLUDED.chat_type,user_id=EXCLUDED.user_id,bound_by=EXCLUDED.bound_by,updated_at=CURRENT_TIMESTAMP RETURNING *`,[chat.id,chat.type,user.id,String(actor)])).rows[0];}
 async binding(chatId){return (await this.db().query('SELECT g.*,a.email,a.name,a.status FROM wpay_auth.statement_bot_groups g JOIN wpay_auth.accounts a ON a.id=g.user_id WHERE g.chat_id=$1',[chatId])).rows[0]||null;}
 async createImport({chatId,userId,uploader,document}){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query(`UPDATE wpay_auth.statement_bot_imports SET state='rejected',last_error='SUPERSEDED_REUPLOAD',updated_at=CURRENT_TIMESTAMP WHERE chat_id=$1 AND user_id=$2 AND telegram_file_unique_id=$3 AND state IN('queued_probe','probing','waiting_upi','queued_parse','processing')`,[chatId,userId,document.file_unique_id]);await c.query(`UPDATE wpay_auth.statement_bot_choices SET consumed_at=COALESCE(consumed_at,CURRENT_TIMESTAMP) WHERE import_id IN(SELECT id FROM wpay_auth.statement_bot_imports WHERE chat_id=$1 AND user_id=$2 AND telegram_file_unique_id=$3 AND last_error='SUPERSEDED_REUPLOAD')`,[chatId,userId,document.file_unique_id]);const row=(await c.query(`INSERT INTO wpay_auth.statement_bot_imports(id,chat_id,user_id,uploader_telegram_id,telegram_file_id,telegram_file_unique_id,file_name,mime_type,file_size,state)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'queued_probe') RETURNING *`,[randomUUID(),chatId,userId,String(uploader),document.file_id,document.file_unique_id,document.file_name||'statement',document.mime_type||null,document.file_size])).rows[0];await c.query('COMMIT');return row;}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async imports(state,limit=3){if(state==='queued_probe')await this.pool.query("UPDATE wpay_auth.statement_bot_imports SET state='queued_probe',updated_at=CURRENT_TIMESTAMP WHERE state='probing' AND attempts<5 AND updated_at<CURRENT_TIMESTAMP-interval '2 minutes'");if(state==='queued_parse')await this.pool.query("UPDATE wpay_auth.statement_bot_imports SET state='queued_parse',updated_at=CURRENT_TIMESTAMP WHERE state='processing' AND attempts<5 AND updated_at<CURRENT_TIMESTAMP-interval '2 minutes'");return (await this.pool.query('SELECT * FROM wpay_auth.statement_bot_imports WHERE state=$1 AND attempts<5 ORDER BY created_at,id LIMIT $2',[state,limit])).rows;}
 async startAttempt(id,expected){const next=expected==='queued_probe'?'probing':expected==='queued_parse'?'processing':null;if(!next)throw Error('INVALID_IMPORT_STATE');return (await this.pool.query('UPDATE wpay_auth.statement_bot_imports SET state=$3,attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND state=$2 RETURNING *',[id,expected,next])).rows[0]||null;}
 async setProbe(id,{format,digest}){const c=await this.pool.connect();try{await c.query('BEGIN');const row=(await c.query('SELECT * FROM wpay_auth.statement_bot_imports WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row||row.state!=='probing'){await c.query('ROLLBACK');return null;}const prior=(await c.query("SELECT id FROM wpay_auth.statement_bot_imports WHERE user_id=$1 AND file_digest=$2 AND id<>$3 AND state IN('waiting_upi','queued_parse','processing','completed','duplicate') ORDER BY created_at LIMIT 1",[row.user_id,digest,id])).rows[0];if(prior){const out=(await c.query("UPDATE wpay_auth.statement_bot_imports SET detected_format=$2,file_digest=$3,state='duplicate',duplicate_of=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *",[id,format,digest,prior.id])).rows[0];await c.query('COMMIT');return {...out,duplicate:true};}const out=(await c.query("UPDATE wpay_auth.statement_bot_imports SET detected_format=$2,file_digest=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *",[id,format,digest])).rows[0];await c.query('COMMIT');return {...out,duplicate:false};}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async choices(importId,upis){const c=await this.pool.connect();try{await c.query('BEGIN');const row=(await c.query('SELECT * FROM wpay_auth.statement_bot_imports WHERE id=$1 FOR UPDATE',[importId])).rows[0];if(!row||row.state!=='probing'){await c.query('ROLLBACK');return[];}await c.query('DELETE FROM wpay_auth.statement_bot_choices WHERE import_id=$1',[importId]);const result=[];for(const u of upis){const token=randomBytes(12).toString('base64url');await c.query('INSERT INTO wpay_auth.statement_bot_choices(token,import_id,bank_id,bank_version,upi_id) VALUES($1,$2,$3,$4,$5)',[token,importId,u.id,u.version,u.upiId]);result.push({token,...u});}await c.query("UPDATE wpay_auth.statement_bot_imports SET state='waiting_upi',updated_at=CURRENT_TIMESTAMP WHERE id=$1",[importId]);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async choice(token){return (await this.pool.query(`SELECT ch.*,i.chat_id,i.user_id,i.uploader_telegram_id,i.state,i.file_name FROM wpay_auth.statement_bot_choices ch JOIN wpay_auth.statement_bot_imports i ON i.id=ch.import_id WHERE ch.token=$1`,[token])).rows[0]||null;}
 async selectChoice(token,actor,isController){const c=await this.pool.connect();try{await c.query('BEGIN');const choice=(await c.query(`SELECT ch.*,i.chat_id,i.user_id,i.uploader_telegram_id,i.state FROM wpay_auth.statement_bot_choices ch JOIN wpay_auth.statement_bot_imports i ON i.id=ch.import_id WHERE ch.token=$1 FOR UPDATE OF ch,i`,[token])).rows[0];if(!choice||choice.state!=='waiting_upi'||choice.consumed_at){await c.query('ROLLBACK');return null;}if(String(actor)!==String(choice.uploader_telegram_id)&&!isController){await c.query('ROLLBACK');return {denied:true,chat_id:choice.chat_id};}const row=(await c.query(`UPDATE wpay_auth.statement_bot_imports SET selected_bank_id=$2,selected_bank_version=$3,selected_upi=$4,state='queued_parse',attempts=0,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *`,[choice.import_id,choice.bank_id,choice.bank_version,choice.upi_id])).rows[0];await c.query('UPDATE wpay_auth.statement_bot_choices SET consumed_at=CURRENT_TIMESTAMP WHERE import_id=$1',[choice.import_id]);await c.query('COMMIT');return row;}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
 async failImport(id,error,state='failed'){await this.pool.query('UPDATE wpay_auth.statement_bot_imports SET state=$2,last_error=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1',[id,state,String(error||'FAILED').slice(0,200)]);}
 async complete(id,result){return (await this.pool.query(`UPDATE wpay_auth.statement_bot_imports SET state='completed',rows_scanned=$2,credit_count=$3,debit_count=$4,total_credit_minor=$5,total_debit_minor=$6,credit_utr_count=$7,new_utr_count=$8,duplicate_utr_count=$9,callback_delivered_count=$10,callback_already_delivered_count=$11,callback_queued_count=$12,callback_pending_count=$13,callback_exhausted_count=$14,normalized_digest=$15,normalized_bytes=$16,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *`,[id,result.rowsScanned,result.creditCount,result.debitCount,result.totalCreditMinor,result.totalDebitMinor,result.creditUtrCount,result.newUtrCount,result.duplicateUtrCount,result.callbackDelivered,result.callbackAlreadyDelivered,result.callbackQueued,result.callbackPending,result.callbackExhausted,result.normalizedCsvDigest,result.normalizedCsvBytes])).rows[0];}
}
module.exports={Store};