"use strict";
(function(root){
 const labels={
  signedAvailable:["Signed remaining","Остаток с учётом дефицита","有符号剩余额度"],deficit:["Capacity deficit","Дефицит лимита","容量缺口"],device_required:["Required device is not eligible","Требуемое устройство недоступно","所需设备不符合条件"],
  reviewState:['Admin review','Проверка администратором','管理员审核中'],deactivated:['Deactivated','Деактивировано','已停用'],
  dashboard:['Business overview','Финансовый обзор','业务概览'],bank:['Bank & UPI','Банк и UPI','银行与 UPI'],assignments:['User Assignment','Назначение пользователей','用户分配'],routing:['Routing','Маршрутизация','路由'],ledger:['Ledger','Журнал операций','账本'],holds:['Holds / Frozen','Удержания / заморозка','冻结金额'],
  allocated:['Allocated','Выделено','已分配'],reserved:['Reserved','Зарезервировано','已预留'],consumed:['Consumed','Использовано','已消耗'],available:['Available','Доступно','可用'],held:['Held / Frozen','Удержано / заморожено','已冻结'],commission:['Commission entitlement','Начисленная комиссия','佣金权益'],gross:['Gross collection','Валовые поступления','收款总额'],fees:['Platform fees','Комиссии платформы','平台费用'],payoutFees:['Payout fees','Комиссии выплат','付款费用'],
  routingCapacity:['Available routing capacity','Доступная ёмкость маршрутизации','可用路由容量'],routingAvailable:['Assigned pool available','Назначенный пул доступен','已分配路由池可用'],noRoute:['No route available','Нет доступного маршрута','暂无可用路由'],foundation:['Business foundation. Live payment creation and payout execution are not connected.','Основа учёта. Создание реальных платежей и выполнение выплат не подключены.','业务基础功能。尚未连接真实付款创建或出款执行。'],
  empty:['No records yet','Записей пока нет','暂无记录'],noOrders:['No live orders yet','Реальных заказов пока нет','暂无真实订单'],noVerify:['Verification provider not connected. Approval alone does not verify or activate a UPI.','Провайдер проверки не подключён. Одобрение само по себе не подтверждает и не активирует UPI.','尚未连接验证服务。批准并不代表 UPI 已验证或启用。'],
  add:['Add Bank / UPI','Добавить банк / UPI','添加银行 / UPI'],edit:['Edit','Изменить','编辑'],save:['Save draft','Сохранить черновик','保存草稿'],cancel:['Cancel','Отмена','取消'],submit:['Submit for review','Отправить на проверку','提交审核'],review:['Start review','Начать проверку','开始审核'],approve:['Approve','Одобрить','批准'],reject:['Reject','Отклонить','拒绝'],freeze:['Freeze','Заморозить','冻结'],release_freeze:['Release to review','Вернуть на проверку','解除冻结并重新审核'],request_verification:['Request verification','Запросить проверку','申请验证'],enable:['Enable','Включить','启用'],run:['Mark running','Включить работу','标记为运行'],stop:['Stop','Остановить','停止'],deactivate:['Deactivate','Деактивировать','停用'],
  upiId:['UPI ID','UPI ID','UPI 账号'],bankName:['Bank name','Название банка','银行名称'],holderName:['Account holder name','Имя владельца счёта','账户持有人姓名'],accountNumber:['Account number','Номер счёта','银行账号'],ifsc:['IFSC','IFSC','IFSC'],mobile:['Registered mobile','Зарегистрированный телефон','预留手机号'],bankLimit:['Bank limit (INR, rolling 24 hours)','Лимит банка (INR, за 24 часа)','银行限额（INR，滚动24小时）'],accountType:['Account type','Тип счёта','账户类型'],personal:['Personal','Личный','个人'],business:['Business','Бизнес','企业'],providerName:['Business provider name (optional)','Название провайдера (необязательно)','企业服务商名称（可选）'],notes:['Business integration details / notes (no credentials)','Данные интеграции / заметки (без секретов)','业务集成详情 / 备注（勿填凭据）'],safeNotes:['Do not enter banking passwords, PINs, OTPs, recovery codes or private keys.','Не вводите банковские пароли, PIN, одноразовые коды, коды восстановления или приватные ключи.','请勿填写银行密码、PIN、一次性验证码、恢复码或私钥。'],
  reason:['Reason','Причина','原因'],version:['Version','Версия','版本'],status:['Status','Статус','状态'],all:['All','Все','全部'],pendingReviews:['Pending reviews','Ожидают проверки','待审核'],approved:['Approved','Одобрено','已批准'],rejectedFrozen:['Rejected / Frozen','Отклонённые / замороженные','已拒绝 / 已冻结'],details:['Review details','Данные для проверки','审核详情'],
  draft:['Draft','Черновик','草稿'],submitted:['Submitted','Отправлено','已提交'],verification_pending:['Verification pending','Ожидает верификации','待验证'],verified:['Verified','Проверено','已验证'],enabled:['Enabled','Включено','已启用'],running:['Running','Работает','运行中'],stopped:['Stopped','Остановлено','已停止'],frozen:['Frozen','Заморожено','已冻结'],rejected:['Rejected','Отклонено','已拒绝'],active:['Active','Активно','有效'],disabled:['Disabled','Отключено','已停用'],pending:['Pending','Ожидает','待处理'],released:['Released','Освобождено','已释放'],expired:['Expired','Истекло','已过期'],cancelled:['Cancelled','Отменено','已取消'],
  merchant:['Merchant','Мерчант','商户'],user:['User','Пользователь','用户'],priority:['Priority (lower first)','Приоритет (меньше — раньше)','优先级（越小越优先）'],weight:['Weight (reserved for future strategies)','Вес (для будущих стратегий)','权重（供后续策略使用）'],minTicket:['Minimum ticket (INR)','Минимальная сумма (INR)','最低金额（INR）'],maxTicket:['Maximum ticket (INR)','Максимальная сумма (INR)','最高金额（INR）'],assign:['Assign User','Назначить пользователя','分配用户'],disable:['Disable assignment','Отключить назначение','停用分配'],capacity:['Capacity','Лимит','容量'],internalRoute:['Internal route reference','Внутренний маршрут','内部路由编号'],eligible:['Eligible','Доступен','符合条件'],unavailable:['Unavailable','Недоступен','不可用'],reservations:['Reservations','Резервирования','预留记录'],reference:['Reference','Ссылка операции','业务编号'],amount:['Amount','Сумма','金额'],expires:['Expires','Истекает','到期时间'],
  owner:['Owner account ID (optional)','ID владельца (необязательно)','账户所有者ID（可选）'],type:['Ledger type','Тип проводки','账目类型'],search:['Apply filters','Применить фильтры','应用筛选'],next:['Next','Далее','下一页'],previous:['Previous','Назад','上一页'],created:['Created','Создано','创建时间'],direction:['Direction','Направление','方向'],credit:['Credit','Кредит','贷方'],debit:['Debit','Дебет','借方'],rateVersion:['Applied rate version','Применённая версия тарифа','采用的费率版本'],source:['Source','Источник','来源'],readOnly:['Read-only ledger; no withdrawals or payouts are executed here.','Журнал только для чтения; вывод средств и выплаты здесь не выполняются.','只读账本；此处不执行提现或出款。'],
  capacity_allocated:['Capacity allocation','Выделение лимита','容量分配'],capacity_consumed:['Capacity consumption','Использование лимита','容量消耗'],capacity_reserved:['Capacity reservation','Резервирование лимита','容量预留'],capacity_hold:['Capacity hold','Удержание лимита','容量冻结'],user_commission:['User commission','Комиссия пользователя','用户佣金'],merchant_gross:['Merchant gross collection','Валовые поступления мерчанта','商户收款总额'],merchant_platform_fee:['Merchant platform fee','Комиссия платформы','商户平台费'],merchant_payout_fee:['Merchant payout fee','Комиссия выплаты','商户付款费'],merchant_adjustment:['Administrative adjustment','Административная корректировка','管理调整'],merchant_hold:['Merchant hold','Удержание мерчанта','商户冻结'],
  account_unavailable:['Account inactive or not approved','Аккаунт неактивен или не одобрен','账户未启用或未获批准'],mfa_required:['Current MFA factor required','Требуется действующий фактор MFA','需要有效的双重验证因子'],operations_disabled:['Operational prerequisites incomplete','Операционные условия не выполнены','运营条件尚未满足'],funding_required:['Confirmed funding required','Требуется подтверждённое обеспечение','需要已确认的资金'],assignment_inactive:['Assignment inactive','Назначение неактивно','分配未启用'],bank_unavailable:['Approved, verified and enabled bank required','Нужен одобренный, проверенный и включённый счёт','需要已批准、验证并启用的银行账户'],ticket_limit:['Outside ticket limits','За пределами лимита суммы','超出金额限制'],bank_limit:['Bank limit reached','Достигнут лимит банка','已达银行限额'],capacity_insufficient:['Insufficient capacity','Недостаточно лимита','容量不足']
 };
 const locales=['en','ru','zh-CN'];
 const api={labels,translate(locale,key){return labels[key]?.[Math.max(0,locales.indexOf(locale))]||key;}};
 if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.WPayBusinessLocales=api;
})(globalThis);
