"use strict";
(function(root){
 const labels={
 title:['USDT Deposit','Депозит USDT','USDT 入金'],reviewTitle:['USDT Deposit Review','Проверка депозитов USDT','USDT 入金审核'],
 policy:['One confirmed deposit of at least 2,000 USDT is required. Each later top-up also requires at least 2,000 USDT. No maximum. Smaller received transfers are recorded for review and are not combined.','Нужен один подтверждённый депозит от 2 000 USDT. Каждое последующее пополнение — также от 2 000 USDT. Максимума нет. Меньшие переводы сохраняются для проверки и не суммируются.','首次须单笔确认至少 2,000 USDT。后续每笔充值也须至少 2,000 USDT，无上限。较小到账转账会保留供审核，不会合并。'],
 missing:['Verification source not configured','Источник проверки не настроен','未配置验证来源'],configured:['Verification source configured; each transfer still requires verification','Источник настроен; каждый перевод требует проверки','已配置验证来源；每笔转账仍须验证'],
 network:['Network','Сеть','网络'],address:['Assigned receiving address','Назначенный адрес получения','分配的收款地址'],token:['Exact token contract','Контракт токена','确切代币合约'],rate:['INR per USDT','INR за USDT','每 USDT 对应 INR'],version:['Commercial version','Версия условий','商业设置版本'],amount:['Amount (USDT)','Сумма (USDT)','金额（USDT）'],copy:['Copy address','Копировать адрес','复制地址'],copied:['Address copied','Адрес скопирован','地址已复制'],
 create:['Create deposit request','Создать запрос депозита','创建入金申请'],confirmRequest:['I confirm this amount and the assigned network/address. This request does not credit funds.','Подтверждаю сумму и назначенные сеть/адрес. Запрос не зачисляет средства.','我确认此金额及分配的网络和地址。申请不会入账。'],
 history:['Deposit history','История депозитов','入金历史'],empty:['No deposit requests','Нет запросов депозита','暂无入金申请'],all:['All states','Все статусы','全部状态'],filter:['Apply filter','Применить фильтр','应用筛选'],next:['Next','Далее','下一页'],previous:['Previous','Назад','上一页'],
 requested:['Requested','Запрошен','已申请'],detected:['Reference submitted / detected','Ссылка отправлена / обнаружен','已提交引用 / 已检测'],confirming:['Awaiting finality','Ожидает финальности','等待最终确认'],review:['Needs review','Требует проверки','待审核'],confirmed:['Confirmed','Подтверждён','已确认'],rejected:['Rejected','Отклонён','已拒绝'],reversed:['Reversed','Сторнирован','已冲正'],
 id:['Request ID','ID запроса','申请编号'],owner:['User account','Аккаунт пользователя','用户账户'],created:['Created','Создан','创建时间'],status:['State','Статус','状态'],reason:['Reason','Причина','原因'],source:['Verification provenance','Происхождение проверки','验证来源'],blockchain_verified:['Blockchain verified','Проверено по блокчейну','区块链验证'],manually_reviewed:['Manually reviewed; not blockchain confirmation','Проверено вручную; не подтверждение блокчейна','人工审核；非区块链确认'],none:['Not credited','Не зачислен','未入账'],credit:['Credited INR','Зачислено INR','已入账 INR'],capacity:['Available INR collateral capacity','Доступный обеспеченный лимит INR','可用 INR 抵押容量'],signed:['Signed remaining INR','Остаток INR с учётом дефицита','有符号 INR 剩余额度'],deficit:['Capacity deficit INR','Дефицит лимита INR','INR 容量缺口'],
 claim:['Submit transfer reference','Отправить ссылку перевода','提交转账引用'],hash:['Transaction hash','Хеш транзакции','交易哈希'],index:['Transfer event index (Ethereum logIndex; TRON receipt log position)','Индекс события (Ethereum logIndex; позиция лога TRON)','转账事件索引（Ethereum logIndex；TRON 回执日志位置）'],recheck:['Queue verification retry','Запросить повторную проверку','排队重试验证'],
 evidence:['Independent evidence reference (letters, digits, . _ : -)','Ссылка независимого доказательства (буквы, цифры, . _ : -)','独立证据编号（字母、数字、. _ : -）'],attribution:['Ownership / attribution evidence reference','Ссылка доказательства принадлежности','归属证据编号'],final:['I reviewed final evidence and the exact User, network, token, address and amount.','Я проверил окончательные доказательства, пользователя, сеть, токен, адрес и сумму.','我已审核最终证据及确切用户、网络、代币、地址和金额。'],confirm:['Confirm manual review','Подтвердить вручную','确认人工审核'],reject:['Reject request','Отклонить запрос','拒绝申请'],reverse:['Reverse with compensating entry','Сторнировать компенсирующей записью','通过补偿分录冲正'],restore:['Restore after independent review','Восстановить после независимой проверки','独立审核后恢复'],audit:['Audited evidence and capacity before / after','Аудит доказательств и лимита до / после','证据及前后容量审计'],
 warning:['A hash or screenshot alone is not confirmation. Duplicate and ambiguous transfers remain subject to independent review. No transfer is sent from this page.','Хеш или снимок экрана не является подтверждением. Дубликаты и неоднозначные переводы требуют независимой проверки. Эта страница не отправляет переводы.','仅哈希或截图不代表确认。重复或归属不明确的转账须独立审核。本页不发送转账。']
 };
 const api={labels,translate:(locale,key)=>labels[key]?.[['en','ru','zh-CN'].indexOf(locale)]||labels[key]?.[0]||key};
 if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.WPayFundingLocales=api;
})(globalThis);
