"use strict";
(function(root){
 const words={title:['Payment gateway','Платёжный шлюз','支付网关'],orders:['Transactions','Транзакции','交易'],create:['Create payment link','Создать платёжную ссылку','创建付款链接'],reference:['Merchant reference','Номер заказа продавца','商户订单号'],amount:['Amount in paise (INR)','Сумма в пайсах (INR)','金额（印度派士）'],description:['Description','Описание','描述'],search:['Search','Поиск','搜索'],next:['Next page','Следующая страница','下一页'],refresh:['Refresh','Обновить','刷新'],keys:['API credentials','Ключи API','API 凭据'],label:['Key label','Название ключа','密钥标签'],keyCreate:['Create API key','Создать ключ API','创建 API 密钥'],revoke:['Revoke','Отозвать','撤销'],webhooks:['Webhooks','Вебхуки','Webhook'],url:['HTTPS callback URL','HTTPS URL обратного вызова','HTTPS 回调网址'],rotate:['Save endpoint / rotate secret','Сохранить URL / сменить секрет','保存端点／轮换密钥'],retry:['Retry now','Повторить сейчас','立即重试'],once:['Copy this secret now. It will not be shown again.','Скопируйте секрет сейчас. Он больше не будет показан.','请立即复制此密钥。之后不会再次显示。'],hide:['Hide secret','Скрыть секрет','隐藏密钥'],empty:['No records','Нет записей','暂无记录'],notice:['TEST / DEV — synthetic acceptance. No real payment provider connected.','ТЕСТ — синтетическая проверка. Реальный платёжный провайдер не подключён.','测试／开发 — 模拟验收。未连接真实支付服务商。'],unavailable:['Payment verification source unavailable','Источник проверки платежей недоступен','付款验证来源不可用'],formula:['Success rate = successful ÷ (successful + failed). Pending, expired and cancelled are excluded.','Доля успеха = успешные ÷ (успешные + неуспешные). Ожидающие, истёкшие и отменённые исключены.','成功率＝成功÷（成功＋失败）。排除待处理、过期及取消订单。'],link:['Open customer payment page','Открыть страницу оплаты','打开客户付款页面'],status:['Status','Статус','状态'],all:['All','Все','全部'],pending_payment:['Pending payment','Ожидает оплаты','待付款'],verification_pending:['Verification pending','Ожидает проверки','待验证'],successful:['Successful','Успешно','成功'],failed:['Failed','Неуспешно','失败'],expired:['Expired','Истёк','已过期'],cancelled:['Cancelled','Отменён','已取消'],recovery_review:['Recovery review','Проверка восстановления','补款审核'],total:['Total orders','Всего заказов','订单总数'],volume:['Successful volume (paise)','Успешный объём (пайсы)','成功金额（派士）'],rate:['Success rate','Доля успеха','成功率'],gross:['Gross (paise)','Валовая сумма (пайсы)','总额（派士）'],fees:['Fees (paise)','Комиссии (пайсы)','费用（派士）'],held:['Held (paise)','Заблокировано (пайсы)','冻结（派士）'],available:['Available (paise)','Доступно (пайсы)','可用（派士）']};
 Object.assign(words,{manual:['Manual','Вручную','手动'],api:['API','API','API'],delivered:['Delivered','Доставлено','已送达'],pending:['Pending','Ожидает','待处理'],leased:['Delivering','Доставляется','发送中'],unconfigured:['Not configured','Не настроено','未配置'],none:['No event','Нет события','暂无事件'],paid:['Paid at','Время оплаты','付款时间'],revoked:['Revoked','Отозван','已撤销'],active:['Active','Активен','有效'],invalidated:['Invalidated','Недействителен','已失效'],readScope:['Read orders','Чтение заказов','读取订单'],writeScope:['Create orders','Создание заказов','创建订单'],copySecret:['Copy secret','Копировать секрет','复制密钥'],copied:['Copied','Скопировано','已复制']});
 Object.assign(words,{openCheckout:['Open Checkout','Открыть оплату','打开收银台'],copyLink:['Copy Link','Скопировать ссылку','复制链接'],expires:['Expires','Срок действия','到期时间']});
 Object.assign(words,{entry:['Create Payment Link','Создать платёжную ссылку','创建付款链接'],generate:['Generate Payment Link','Создать платёжную ссылку','生成付款链接'],amount:['Amount (INR rupees)','Сумма (индийские рупии, INR)','金额（印度卢比 INR）'],description:['Description (optional)','Описание (необязательно)','描述（可选）'],amountHelp:['Enter rupees with up to two decimal places, for example 1250.50 INR.','Введите рупии с точностью до двух знаков, например 1250.50 INR.','请输入卢比金额，最多两位小数，例如 1250.50 INR。'],noRoute:['No eligible route or sufficient capacity is available. No payment link was created.','Нет подходящего маршрута или достаточного лимита. Платёжная ссылка не создана.','没有符合条件的路由或足够额度。未创建付款链接。']});
 function toPaise(value){if(typeof value!=='string'||value.length>26||!/^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(value))throw Error('error.INVALID_INPUT');const [whole,fraction='']=value.split('.'),minor=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(minor<=0n||minor>10n**24n)throw Error('error.INVALID_INPUT');return minor.toString();}
 async function proofFile(input){const f=input.files[0];if(!f||f.size>1048576)throw Error('error.INVALID_INPUT');const bytes=new Uint8Array(await f.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name:f.name,data:btoa(raw)};}
 const text=(locale,key)=>(words[key]||[key,key,key])[Math.max(0,['en','ru','zh-CN'].indexOf(locale))];
 async function render(args){
  const {account,locale,request,post,action,el,container,title}=args,t=k=>text(locale,k);title.textContent=t('title');container.replaceChildren();const card=el('section',undefined,'card business-card');container.append(card);
  const button=(key,fn)=>{const b=el('button',t(key));b.type='button';b.onclick=()=>action(fn);return b;},field=(form,key,type='text')=>{const label=el('label',t(key)),i=el('input');i.type=type;i.setAttribute('aria-label',t(key));label.append(i);form.append(label);return i;};
  const showSecret=result=>{const dialog=el('dialog'),p=el('p',t('once')),secret=el('input'),row=el('div');secret.readOnly=true;secret.value=result.secret;secret.setAttribute('aria-label','One-time secret');secret.dataset.secret='true';secret.type='text';row.style.display='flex';row.style.alignItems='center';row.style.gap='6px';secret.style.flex='1';let timer;const close=()=>{clearTimeout(timer);secret.value='';dialog.close();dialog.remove();};const iconButton=(name,label,fn)=>{const b=el('button',undefined,'icon-btn');b.type='button';b.dataset.icon=name;b.setAttribute('aria-label',label);b.title=label;b.style.width='34px';b.style.height='34px';b.onclick=()=>action(fn);return b;};const copy=iconButton('copy','Copy API key',async()=>{await navigator.clipboard.writeText(secret.value);copy.title=t('copied');copy.setAttribute('aria-label',t('copied'));});let visible=true;const visibility=iconButton('eye-off','Hide API key',()=>{visible=!visible;secret.type=visible?'text':'password';visibility.dataset.icon=visible?'eye-off':'eye';visibility.title=visible?'Hide API key':'Show API key';visibility.setAttribute('aria-label',visibility.title);globalThis.WPayReferenceIcons?.hydrate(visibility);});row.append(secret,copy,visibility);dialog.append(p,row,button('hide',close));dialog.addEventListener('cancel',close);document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'&&dialog.open)close();},{once:true});container.append(dialog);globalThis.WPayReferenceIcons?.hydrate(dialog);dialog.showModal();timer=setTimeout(close,60000);};
  const merchant=account.accountType==='merchant',view=args.view,split=merchant&&['links','orders','transactions','api','webhooks','logs'].includes(view);
  if(split)title.textContent=view==='links'?t('entry'):view==='api'?t('keys'):view==='logs'?'API logs':view==='webhooks'?t('webhooks'):view==='transactions'?'Transactions':t('orders');
  const collection=!split||['links','orders','transactions'].includes(view);
  const disputeState=merchant&&['orders','transactions'].includes(view)?await post('payin-dispute/search',{offset:0,status:''}).catch(()=>({records:[]})):{records:[]},disputeByOrder=new Map((disputeState.records||[]).map(d=>[d.orderId,d]));
  if(collection){
  if(merchant&&(!split||view==='links')){const summary=await request('gateway/summary');card.append(el('p',summary.synthetic?t('notice'):summary.verificationConnected?'':t('unavailable'),'notice'));
   const facts=el('dl',undefined,'facts');for(const [key,value]of Object.entries({total:summary.total,volume:summary.successfulVolumeMinor,rate:summary.successRate===null?'—':(summary.successRate*100).toFixed(2)+'%',gross:summary.gross,fees:summary.fees,held:summary.held,available:summary.available})){facts.append(el('dt',t(key)),el('dd',String(value)));}facts.append(el('dt','Payment-link expiry'),el('dd',String(summary.linkTtlSeconds??300)+' seconds · Admin controlled'));card.append(facts,el('p',t('formula'),'hint'));
   const form=el('form'),ref=field(form,'reference'),amount=field(form,'amount'),description=field(form,'description');ref.maxLength=100;amount.inputMode='decimal';amount.maxLength=26;amount.pattern='(0|[1-9][0-9]*)([.][0-9]{1,2})?';ref.required=amount.required=true;description.required=false;description.maxLength=200;form.append(el('p',t('amountHelp'),'hint'));
   const submit=el('button',t('generate'));submit.type='submit';form.append(submit);let requestId=crypto.randomUUID(),previousPayload;const unavailable=el('p','', 'notice');unavailable.setAttribute('role','status');form.onsubmit=e=>{e.preventDefault();action(async()=>{if(!form.reportValidity())return;const payload={reference:ref.value,amountMinor:toPaise(amount.value),currency:'INR',description:description.value},signature=JSON.stringify(payload);if(previousPayload&&previousPayload!==signature)requestId=crypto.randomUUID();previousPayload=signature;unavailable.textContent='';try{const result=await post('gateway/create',{...payload,idempotencyKey:requestId});await render({...args,selectedOrderId:result.id});}catch(error){if(['error.NO_ROUTE','error.INSUFFICIENT_CAPACITY'].includes(error.message)){unavailable.textContent=t('noRoute');const diagnose=button('Check route availability',async()=>{try{const check=await post('gateway/route-status',{amountMinor:payload.amountMinor}),labels={no_assignment:'Admin has not assigned an eligible UPI route to this merchant.',account_unavailable:'The receiving account is not active and approved.',mfa_required:'The receiving account security setup needs attention.',device_required:'The receiving account requires an eligible paired device.',statement_required:'The receiving UPI requires an accepted statement.',operations_disabled:'Receiving operations are disabled.',funding_required:'The receiving user needs confirmed funding.',assignment_inactive:'The merchant assignment is disabled or not active yet.',bank_unavailable:'The assigned UPI is stopped, frozen, unapproved, or its approval is out of date.',ticket_limit:'The amount is outside the assigned transaction minimum/maximum.',bank_limit:'The UPI daily limit remaining is lower than this amount.',capacity_insufficient:'The receiving user has insufficient available collection capacity.'};unavailable.textContent=check.eligible?'A route is now available. Try generating the link again.':t('noRoute')+' '+check.reasons.map(r=>labels[r]||r).join(' ');}catch{}});unavailable.append(diagnose);return;}throw error;}});};card.append(el('h2',t('entry')),form,unavailable);
  }
  const filters=el('form'),search=field(filters,'search'),select=el('select');select.setAttribute('aria-label',t('status'));for(const state of ['','pending_payment','verification_pending','successful','failed','expired','cancelled','recovery_review']){const option=el('option',t(state||'all'));option.value=state;select.append(option);}filters.append(select,button('search',async()=>{offset=0;await refresh();}));filters.onsubmit=e=>{e.preventDefault();action(refresh);};let offset=0;
  const records=el('div'),linkBox=el('div');card.append(el('h2',t('orders')),filters,records,linkBox);
  async function open(id){const order=await post('gateway/get',{id}),link=el('a',text(locale,'openCheckout'));link.href=order.paymentUrl;link.target='_blank';link.rel='noopener noreferrer';const value=el('input');value.readOnly=true;value.value=order.paymentUrl;value.setAttribute('aria-label',t('link'));value.dataset.secret='true';const qr=el('img');qr.src=order.paymentQr;qr.alt=t('link')+' QR';qr.width=qr.height=256;qr.dataset.secret='true';linkBox.replaceChildren(el('p',t('status')+': '+t(order.status)),el('p',order.id),el('p',order.reference+' · INR '+(BigInt(order.amountMinor)/100n)+'.'+(BigInt(order.amountMinor)%100n).toString().padStart(2,'0')),el('p',t('expires')+': '+new Date(order.expiresAt).toLocaleString()),value,qr,button('copyLink',()=>navigator.clipboard.writeText(order.paymentUrl)),link);}
  async function openDispute(row){
   const d=el('dialog'),form=el('form'),reason=field(form,'Dispute reason'),from=field(form,'Statement coverage from','datetime-local'),through=field(form,'Statement coverage through','datetime-local'),statement=field(form,'Fresh statement proof','file');
   statement.accept='.pdf,.png,.jpg,.jpeg';reason.required=true;const paid=new Date(row.paidAt||row.createdAt),now=new Date();from.value=new Date(paid.getTime()-paid.getTimezoneOffset()*60000).toISOString().slice(0,16);through.value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);
   const submit=el('button','Open 48-hour dispute','primary');submit.type='submit';form.append(el('p','Upload a fresh statement covering the payment time through current review time. Opening the dispute temporarily holds the related User capacity, User commission and Merchant net exposure.','notice'),submit,button('cancel',()=>d.close()));
   form.onsubmit=e=>{e.preventDefault();action(async()=>{await post('payin-dispute/open',{id:row.id,reason:reason.value,statement:await proofFile(statement),coverageFrom:new Date(from.value).toISOString(),coverageThrough:new Date(through.value).toISOString()});d.close();await render(args);});};d.append(el('h2','Open pay-in dispute · '+row.reference),form);container.append(d);d.showModal();
  }
  async function refresh(){const data=await post('gateway/search',{search:search.value,status:select.value,offset});records.replaceChildren();if(!data.orders.length)records.append(el('p',t('empty')));for(const row of data.orders){const item=el('article',undefined,'card'),dispute=disputeByOrder.get(row.id);item.append(el('h3',row.reference),el('p',row.id),el('p','INR '+(BigInt(row.amountMinor)/100n)+'.'+(BigInt(row.amountMinor)%100n).toString().padStart(2,'0')+' · '+t(row.status)),el('p',t(row.origin)+' · '+row.createdAt),el('p',t('webhooks')+': '+t(row.callbackStatus)));if(row.paidAt)item.append(el('p',t('paid')+': '+row.paidAt));if(merchant){item.append(button('link',()=>open(row.id)));if(dispute)item.append(el('p','Pay-in dispute: '+dispute.status+' · '+dispute.reason,'notice'));else if(row.status==='successful')item.append(button('Open pay-in dispute',()=>openDispute(row)));}records.append(item);}if(data.hasMore)records.append(button('next',async()=>{offset+=50;await refresh();}));}
  await refresh();card.append(button('refresh',()=>render(args)));
  if(args.selectedOrderId)await open(args.selectedOrderId);
  }
  if(!merchant){try{const diagnostics=await request('gateway/diagnostics');card.append(el('h2',t('webhooks')));for(const event of diagnostics.events)card.append(el('p',event.event_type+' · '+event.state+' · '+event.attempts+' · '+event.created_at));}catch(error){if(error.message!=='FORBIDDEN')throw error;}return;}
  if(!split||view==='api'){
  const keys=await request('gateway/keys'),keyForm=el('form'),keyLabel=field(keyForm,'label');keyLabel.maxLength=60;keyLabel.required=true;
  const readLabel=el('label'),read=el('input');read.type='checkbox';read.checked=true;readLabel.append(read,el('span',' '+t('readScope')));
  const writeLabel=el('label'),write=el('input');write.type='checkbox';writeLabel.append(write,el('span',' '+t('writeScope')));
  const create=button('keyCreate',async()=>{if(!keyForm.reportValidity())return;const scopes=[read.checked?'orders:read':null,write.checked?'orders:write':null].filter(Boolean);if(!scopes.length)throw Error('error.INVALID_INPUT');const result=await post('gateway/keys/create',{label:keyLabel.value.trim(),scopes});await render(args);showSecret(result);});
  keyForm.append(readLabel,writeLabel,create);card.append(el('h2',t('keys')),el('p','Create the minimum scopes your server needs. Read-only keys cannot create orders.','hint'),keyForm);
  for(const key of keys.keys){const status=key.status||(key.revoked_at?'revoked':'active'),item=el('article',undefined,'card');item.append(el('strong',key.label||'—'),el('p',key.prefix+' · '+key.scopes.join(', ')),el('p',t(status)+(key.last_used_at?' · Last used '+new Date(key.last_used_at).toLocaleString():'')));if(status!=='revoked')item.append(button('revoke',async()=>{await post('gateway/keys/revoke',{id:key.id});await render(args);}));card.append(item);}
  }
  if(!split||view==='webhooks'){
  const hooks=await request('gateway/webhooks'),hookForm=el('form'),url=field(hookForm,'url','url');url.value=hooks.endpoint?.url||'';hookForm.append(button('rotate',async()=>{const result=await post('gateway/webhooks/configure',{url:url.value});await render(args);showSecret(result);}));card.append(el('h2',t('webhooks')),hookForm);
  for(const event of hooks.events){const item=el('p',event.event_type+' · '+t(event.state)+' · '+event.attempts+' · '+event.created_at);if(event.state==='pending'&&event.attempts<8)item.append(button('retry',async()=>{await post('gateway/webhooks/retry',{id:event.id});await render(args);}));card.append(item);}
  }
  if(!split||view==='logs'){const logs=await request('gateway/logs');card.append(el('h2','API logs'),el('p','Secrets and request bodies are never shown.','hint'));if(!logs.rows?.length)card.append(el('p',t('empty')));for(const row of logs.rows||[]){const item=el('article',undefined,'card');item.append(el('strong',(row.method||'')+' '+(row.path||row.operation)),el('p',(row.key_prefix||'Unknown key')+' · '+new Date(row.created_at).toLocaleString()),el('p','Audit ID: '+row.id,'hint'));card.append(item);}}
 }
 function docs({locale,el,container,title}){const i=Math.max(0,['en','ru','zh-CN'].indexOf(locale));title.textContent=['Merchant API','API мерчанта','商户 API'][i];const card=el('section',undefined,'card');
  const para=text=>card.append(el('p',text));
  para(['Server-to-server only. Authenticate with Authorization: Bearer <API_KEY>. Browser requests carrying Cookie or Origin are rejected. API keys are separate from webhook signing secrets.','Только server-to-server. Используйте Authorization: Bearer <API_KEY>. Запросы браузера с Cookie или Origin отклоняются. API-ключ и секрет подписи webhook — разные секреты.','仅限服务器到服务器。使用 Authorization: Bearer <API_KEY>。带 Cookie 或 Origin 的浏览器请求会被拒绝。API 密钥与 Webhook 签名密钥彼此独立。'][i]);
  card.append(el('pre','Base path: /wpay-api/v1\n\nScopes:\norders:write  POST /orders\norders:read   GET /orders/:orderId\n\nRate limit: 60 authenticated requests per API key per minute\nMaximum active API keys: 10'));
  card.append(el('h3','Create order'),el('pre','POST /wpay-api/v1/orders\nAuthorization: Bearer YOUR_API_KEY\nIdempotency-Key: shop-order-001\nContent-Type: application/json\n\n{"reference":"shop-order-001","amountMinor":"125050","currency":"INR","description":"Example order","metadata":{"cartId":"CART_123"}}'));
  para(['reference and Idempotency-Key must each match [A-Za-z0-9][A-Za-z0-9_.:-]{0,99}. amountMinor is a positive integer string in paise. currency must be INR. description is optional up to 200 characters. metadata is optional: up to 12 flat string fields, key names start with a letter and use letters/numbers/underscore, values up to 200 characters, total JSON size up to 2048 bytes.','reference и Idempotency-Key имеют ограниченный формат. amountMinor — положительная целая строка в пайсах, currency только INR. description необязателен, максимум 200 символов. metadata — до 12 плоских строковых полей.','reference 与 Idempotency-Key 使用受限格式。amountMinor 为正整数字符串（派士），currency 必须为 INR。description 可选，最多 200 字符。metadata 最多 12 个扁平字符串字段。'][i]);
  card.append(el('pre','HTTP 201\n{\n  "id": "ORDER_UUID",\n  "reference": "shop-order-001",\n  "amountMinor": "125050",\n  "currency": "INR",\n  "status": "pending_payment",\n  "evidenceStatus": "unavailable",\n  "paymentUrl": "https://YOUR_WPAY_HOST/wpay-pay/...",\n  "expiresAt": "..."\n}'));
  card.append(el('h3','Get order'),el('pre','GET /wpay-api/v1/orders/ORDER_UUID\nAuthorization: Bearer YOUR_API_KEY\n\nHTTP 200\n{ "id":"ORDER_UUID", "status":"successful|failed|expired|pending_payment|verification_pending|recovery_review|cancelled", "callbackStatus":"none|pending|delivered|failed|unconfigured" }'));
  para(['After a timeout, retry the exact same payload with the same reference and Idempotency-Key. Reusing either with a different payload returns CONFLICT. NO_ROUTE creates no order or payment link. A submitted UTR is never proof of success.','После тайм-аута повторяйте тот же payload с теми же reference и Idempotency-Key. Изменение payload даст CONFLICT. NO_ROUTE не создаёт заказ.','超时后使用完全相同的 payload、reference 和 Idempotency-Key 重试。不同 payload 会返回 CONFLICT。NO_ROUTE 不会创建订单。'][i]);
  card.append(el('h3','Errors'),el('pre','400 INVALID_INPUT\n401 AUTH_FAILED\n403 FORBIDDEN\n409 CONFLICT | NO_ROUTE | INSUFFICIENT_CAPACITY\n429 RATE_LIMITED\n503 UNAVAILABLE'));
  card.append(el('h3','Webhook verification'),el('pre','HMAC-SHA256(secret, timestamp + "." + eventId + "." + exactBodyBytes)\n\nx-wpay-timestamp: Unix seconds\nx-wpay-event-id: stable UUID\nx-wpay-signature: v1=hex\nx-wpay-secret-version: endpoint UUID'));
  para(['Verify against the exact raw UTF-8 body bytes in constant time. Allow at most five minutes of clock skew, persist eventId for deduplication, and return 2xx only after durable acceptance. Delivery retries up to eight attempts. Rotation applies to new orders; retain the previous signing secret for pending deliveries.','Проверяйте точные исходные UTF-8 байты тела, используйте постоянное время сравнения, максимум 5 минут рассинхронизации, сохраняйте eventId для дедупликации. До 8 попыток доставки.','使用精确的原始 UTF-8 正文字节进行恒定时间验证。允许最多 5 分钟时钟偏差，持久化 eventId 去重。最多 8 次投递尝试。'][i]);
  card.append(el('pre','Example event payload:\n{\n  "eventId":"UUID",\n  "eventType":"payment.successful",\n  "version":1,\n  "orderId":"ORDER_UUID",\n  "merchantReference":"shop-order-001",\n  "amountMinor":"125050",\n  "currency":"INR",\n  "status":"successful",\n  "createdAt":"...",\n  "paidAt":"...",\n  "expiresAt":"..."\n}\n\nManual/admin evidence may additionally include:\n"approvalMethod":"manual", "bankVerified": false'));
  container.replaceChildren(card);
}
 root.WPayGatewayPage={render,text,docs,toPaise};
})(globalThis);
