"use strict";
(function(root){
 const words={title:['Payment gateway','Платёжный шлюз','支付网关'],orders:['Transactions','Транзакции','交易'],create:['Create payment link','Создать платёжную ссылку','创建付款链接'],reference:['Merchant reference','Номер заказа продавца','商户订单号'],amount:['Amount in paise (INR)','Сумма в пайсах (INR)','金额（印度派士）'],description:['Description','Описание','描述'],search:['Search','Поиск','搜索'],next:['Next page','Следующая страница','下一页'],refresh:['Refresh','Обновить','刷新'],keys:['API credentials','Ключи API','API 凭据'],label:['Key label','Название ключа','密钥标签'],keyCreate:['Create API key','Создать ключ API','创建 API 密钥'],revoke:['Revoke','Отозвать','撤销'],webhooks:['Webhooks','Вебхуки','Webhook'],url:['HTTPS callback URL','HTTPS URL обратного вызова','HTTPS 回调网址'],rotate:['Save endpoint / rotate secret','Сохранить URL / сменить секрет','保存端点／轮换密钥'],retry:['Retry now','Повторить сейчас','立即重试'],once:['Copy this secret now. It will not be shown again.','Скопируйте секрет сейчас. Он больше не будет показан.','请立即复制此密钥。之后不会再次显示。'],hide:['Hide secret','Скрыть секрет','隐藏密钥'],empty:['No records','Нет записей','暂无记录'],notice:['TEST / DEV — synthetic acceptance. No real payment provider connected.','ТЕСТ — синтетическая проверка. Реальный платёжный провайдер не подключён.','测试／开发 — 模拟验收。未连接真实支付服务商。'],unavailable:['Payment verification source unavailable','Источник проверки платежей недоступен','付款验证来源不可用'],formula:['Success rate = successful ÷ (successful + failed). Pending, expired and cancelled are excluded.','Доля успеха = успешные ÷ (успешные + неуспешные). Ожидающие, истёкшие и отменённые исключены.','成功率＝成功÷（成功＋失败）。排除待处理、过期及取消订单。'],link:['Open customer payment page','Открыть страницу оплаты','打开客户付款页面'],status:['Status','Статус','状态'],all:['All','Все','全部'],pending_payment:['Pending payment','Ожидает оплаты','待付款'],verification_pending:['Verification pending','Ожидает проверки','待验证'],successful:['Successful','Успешно','成功'],failed:['Failed','Неуспешно','失败'],expired:['Expired','Истёк','已过期'],cancelled:['Cancelled','Отменён','已取消'],recovery_review:['Recovery review','Проверка восстановления','补款审核'],total:['Total orders','Всего заказов','订单总数'],volume:['Successful volume (paise)','Успешный объём (пайсы)','成功金额（派士）'],rate:['Success rate','Доля успеха','成功率'],gross:['Gross (paise)','Валовая сумма (пайсы)','总额（派士）'],fees:['Fees (paise)','Комиссии (пайсы)','费用（派士）'],held:['Held (paise)','Заблокировано (пайсы)','冻结（派士）'],available:['Available (paise)','Доступно (пайсы)','可用（派士）']};
 Object.assign(words,{manual:['Manual','Вручную','手动'],api:['API','API','API'],delivered:['Delivered','Доставлено','已送达'],pending:['Pending','Ожидает','待处理'],leased:['Delivering','Доставляется','发送中'],unconfigured:['Not configured','Не настроено','未配置'],none:['No event','Нет события','暂无事件'],paid:['Paid at','Время оплаты','付款时间'],revoked:['Revoked','Отозван','已撤销']});
 Object.assign(words,{openCheckout:['Open Checkout','Открыть оплату','打开收银台'],copyLink:['Copy Link','Скопировать ссылку','复制链接'],expires:['Expires','Срок действия','到期时间']});
 Object.assign(words,{entry:['Create Payment Link','Создать платёжную ссылку','创建付款链接'],generate:['Generate Payment Link','Создать платёжную ссылку','生成付款链接'],amount:['Amount (INR rupees)','Сумма (индийские рупии, INR)','金额（印度卢比 INR）'],description:['Description (optional)','Описание (необязательно)','描述（可选）'],amountHelp:['Enter rupees with up to two decimal places, for example 1250.50 INR.','Введите рупии с точностью до двух знаков, например 1250.50 INR.','请输入卢比金额，最多两位小数，例如 1250.50 INR。'],noRoute:['No eligible route or sufficient capacity is available. No payment link was created.','Нет подходящего маршрута или достаточного лимита. Платёжная ссылка не создана.','没有符合条件的路由或足够额度。未创建付款链接。']});
 function toPaise(value){if(typeof value!=='string'||value.length>26||!/^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$/.test(value))throw Error('error.INVALID_INPUT');const [whole,fraction='']=value.split('.'),minor=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(minor<=0n||minor>10n**24n)throw Error('error.INVALID_INPUT');return minor.toString();}
 const text=(locale,key)=>(words[key]||[key,key,key])[Math.max(0,['en','ru','zh-CN'].indexOf(locale))];
 async function render(args){
  const {account,locale,request,post,action,el,container,title}=args,t=k=>text(locale,k);title.textContent=t('title');container.replaceChildren();const card=el('section',undefined,'card business-card');container.append(card);
  const button=(key,fn)=>{const b=el('button',t(key));b.type='button';b.onclick=()=>action(fn);return b;},field=(form,key,type='text')=>{const label=el('label',t(key)),i=el('input');i.type=type;i.setAttribute('aria-label',t(key));label.append(i);form.append(label);return i;};
  const showSecret=result=>{const dialog=el('dialog'),p=el('p',t('once')),secret=el('input');secret.readOnly=true;secret.value=result.secret;secret.setAttribute('aria-label','One-time secret');const close=()=>{secret.value='';dialog.close();dialog.remove();};dialog.append(p,secret,button('hide',close));dialog.addEventListener('cancel',close);container.append(dialog);dialog.showModal();};
  const merchant=account.accountType==='merchant',view=args.view,split=merchant&&['links','orders','transactions','api','webhooks','logs'].includes(view);
  if(split)title.textContent=view==='links'?t('entry'):view==='api'?t('keys'):view==='logs'?'API logs':view==='webhooks'?t('webhooks'):view==='transactions'?'Transactions':t('orders');
  function adminAction(row,kind,refresh){
   const dialog=el('dialog'),form=el('form'),heading=el('h2',kind==='approve'?'Approve payment manually':'Resend payment callback');
   dialog.append(heading,el('p',row.reference+' · INR '+(BigInt(row.amountMinor)/100n)+'.'+(BigInt(row.amountMinor)%100n).toString().padStart(2,'0')));
   dialog.append(el('p',kind==='approve'?'Record your confirmation of receipt. This credits the merchant and consumes the receiving user limit once. No statement or UTR required. It will be labelled Admin approved.':'Resend the existing signed success event to the merchant callback URL. This does not credit balances again. No statement or UTR required.','notice'));
   const reason=field(form,'Reason');reason.required=true;reason.minLength=2;reason.maxLength=300;
   const amount=kind==='approve'?field(form,'Confirm amount (INR)'):null;if(amount){amount.required=true;amount.inputMode='decimal';}
   const status=el('p','','notice');status.setAttribute('role','alert');const submit=el('button',kind==='approve'?'Confirm approval':'Queue callback','primary');submit.type='submit';
   const close=el('button','Cancel');close.type='button';close.onclick=()=>dialog.close();form.append(status,submit,close);dialog.append(form);container.append(dialog);dialog.onclose=()=>dialog.remove();let password;const requestId=crypto.randomUUID();
   form.onsubmit=e=>{e.preventDefault();action(async()=>{if(!form.reportValidity())return;submit.disabled=true;try{if(password){const value=password.value;password.value='';await post('security/admin-reauth',{password:value});password.required=false;password.remove();password=null;}
    await post('gateway/admin/'+kind,{orderId:row.id,reason:reason.value.trim(),requestId,...(amount?{amountMinor:toPaise(amount.value)}:{})});dialog.close();await refresh();
   }catch(error){const code=error.message.replace(/^error\./,'');status.textContent=({RECENT_MFA_REQUIRED:'Confirm your Admin password below, then submit again.',CONFLICT:'Check the amount and current transaction status; an active callback delivery cannot be retried yet.',UNAVAILABLE:'No usable callback endpoint is configured, or the service is unavailable.',RATE_LIMITED:'Wait one minute before retrying this callback again.',FORBIDDEN:'You do not have permission for this transaction.',INVALID_INPUT:'Enter a valid amount and a reason of at least 2 characters.'})[code]||error.message;if(code==='RECENT_MFA_REQUIRED'&&!password){password=field(form,'Admin password','password');password.autocomplete='current-password';password.required=true;}}finally{submit.disabled=false;}});};dialog.showModal();
  }
  const collection=!split||['links','orders','transactions'].includes(view);
  if(collection){
  if(merchant&&(!split||view==='links')){const summary=await request('gateway/summary');card.append(el('p',summary.synthetic?t('notice'):summary.verificationConnected?'':t('unavailable'),'notice'));
   const facts=el('dl',undefined,'facts');for(const [key,value]of Object.entries({total:summary.total,volume:summary.successfulVolumeMinor,rate:summary.successRate===null?'—':(summary.successRate*100).toFixed(2)+'%',gross:summary.gross,fees:summary.fees,held:summary.held,available:summary.available})){facts.append(el('dt',t(key)),el('dd',String(value)));}facts.append(el('dt','Payment-link expiry'),el('dd',String(summary.linkTtlSeconds??300)+' seconds · Admin controlled'));card.append(facts,el('p',t('formula'),'hint'));
   const form=el('form'),ref=field(form,'reference'),amount=field(form,'amount'),description=field(form,'description');ref.maxLength=100;amount.inputMode='decimal';amount.maxLength=26;amount.pattern='(0|[1-9][0-9]*)([.][0-9]{1,2})?';ref.required=amount.required=true;description.required=false;description.maxLength=200;form.append(el('p',t('amountHelp'),'hint'));
   const submit=el('button',t('generate'));submit.type='submit';form.append(submit);let requestId=crypto.randomUUID(),previousPayload;const unavailable=el('p','', 'notice');unavailable.setAttribute('role','status');form.onsubmit=e=>{e.preventDefault();action(async()=>{if(!form.reportValidity())return;const payload={reference:ref.value,amountMinor:toPaise(amount.value),currency:'INR',description:description.value},signature=JSON.stringify(payload);if(previousPayload&&previousPayload!==signature)requestId=crypto.randomUUID();previousPayload=signature;unavailable.textContent='';try{const result=await post('gateway/create',{...payload,idempotencyKey:requestId});await render({...args,selectedOrderId:result.id});}catch(error){if(['error.NO_ROUTE','error.INSUFFICIENT_CAPACITY'].includes(error.message)){unavailable.textContent=t('noRoute');return;}throw error;}});};card.append(el('h2',t('entry')),form,unavailable);
  }
  const filters=el('form'),search=field(filters,'search'),select=el('select');select.setAttribute('aria-label',t('status'));for(const state of ['','pending_payment','verification_pending','successful','failed','expired','cancelled','recovery_review']){const option=el('option',t(state||'all'));option.value=state;select.append(option);}filters.append(select,button('search',async()=>{offset=0;await refresh();}));filters.onsubmit=e=>{e.preventDefault();action(refresh);};let offset=0;
  const records=el('div'),linkBox=el('div');card.append(el('h2',t('orders')),filters,records,linkBox);
  async function open(id){const order=await post('gateway/get',{id}),link=el('a',text(locale,'openCheckout'));link.href=order.paymentUrl;link.target='_blank';link.rel='noopener noreferrer';const value=el('input');value.readOnly=true;value.value=order.paymentUrl;value.setAttribute('aria-label',t('link'));value.dataset.secret='true';const qr=el('img');qr.src=order.paymentQr;qr.alt=t('link')+' QR';qr.width=qr.height=256;qr.dataset.secret='true';linkBox.replaceChildren(el('p',t('status')+': '+t(order.status)),el('p',order.id),el('p',order.reference+' · INR '+(BigInt(order.amountMinor)/100n)+'.'+(BigInt(order.amountMinor)%100n).toString().padStart(2,'0')),el('p',t('expires')+': '+new Date(order.expiresAt).toLocaleString()),value,qr,button('copyLink',()=>navigator.clipboard.writeText(order.paymentUrl)),link);}
  async function refresh(){const data=await post('gateway/search',{search:search.value,status:select.value,offset});records.replaceChildren();if(!data.orders.length)records.append(el('p',t('empty')));for(const row of data.orders){const item=el('article',undefined,'card');item.append(el('h3',row.reference),el('p',row.id),el('p','INR '+(BigInt(row.amountMinor)/100n)+'.'+(BigInt(row.amountMinor)%100n).toString().padStart(2,'0')+' · '+t(row.status)),el('p',t(row.origin)+' · '+row.createdAt),el('p',t('webhooks')+': '+t(row.callbackStatus)));if(row.paidAt)item.append(el('p',t('paid')+': '+row.paidAt));if(row.evidenceStatus==='admin_approved')item.append(el('p','Admin approved · no bank evidence','notice'));if(merchant)item.append(button('link',()=>open(row.id)));else {if(data.canApprove&&row.status!=='successful')item.append(button('Approve manually',()=>adminAction(row,'approve',refresh)));if(data.canCallback&&row.status==='successful')item.append(button('Resend callback',()=>adminAction(row,'callback',refresh)));}records.append(item);}if(data.hasMore)records.append(button('next',async()=>{offset+=50;await refresh();}));}
  await refresh();card.append(button('refresh',()=>render(args)));
  if(args.selectedOrderId)await open(args.selectedOrderId);
  }
  if(!merchant){try{const diagnostics=await request('gateway/diagnostics');card.append(el('h2',t('webhooks')));for(const event of diagnostics.events)card.append(el('p',event.event_type+' · '+event.state+' · '+event.attempts+' · '+event.created_at));}catch(error){if(error.message!=='FORBIDDEN')throw error;}return;}
  if(!split||view==='api'){
  const keys=await request('gateway/keys'),keyForm=el('form'),keyLabel=field(keyForm,'label');keyLabel.maxLength=60;keyForm.append(button('keyCreate',async()=>{const result=await post('gateway/keys/create',{label:keyLabel.value,scopes:['orders:read','orders:write']});await render(args);showSecret(result);}));card.append(el('h2',t('keys')),keyForm);
  for(const key of keys.keys){const item=el('p',key.label+' · '+key.prefix+' · '+(key.revoked_at?t('revoked'):key.scopes.join(', ')));if(!key.revoked_at)item.append(button('revoke',async()=>{await post('gateway/keys/revoke',{id:key.id});await render(args);}));card.append(item);}
  }
  if(!split||view==='webhooks'){
  const hooks=await request('gateway/webhooks'),hookForm=el('form'),url=field(hookForm,'url','url');url.value=hooks.endpoint?.url||'';hookForm.append(button('rotate',async()=>{const result=await post('gateway/webhooks/configure',{url:url.value});await render(args);showSecret(result);}));card.append(el('h2',t('webhooks')),hookForm);
  for(const event of hooks.events){const item=el('p',event.event_type+' · '+t(event.state)+' · '+event.attempts+' · '+event.created_at);if(event.state==='pending'&&event.attempts<8)item.append(button('retry',async()=>{await post('gateway/webhooks/retry',{id:event.id});await render(args);}));card.append(item);}
  }
  if(!split||view==='logs'){const logs=await request('gateway/logs');card.append(el('h2','API logs'));if(!logs.rows?.length)card.append(el('p',t('empty')));for(const row of logs.rows||[])card.append(el('p',row.operation+' · '+row.created_at+' · '+row.id));}
 }
 function docs({locale,el,container,title}){const i=Math.max(0,['en','ru','zh-CN'].indexOf(locale));title.textContent=['Merchant API','API мерчанта','商户 API'][i];const card=el('section',undefined,'card');card.append(el('p',['Send requests from your server using a scoped Bearer key. Never expose the key in a browser or URL. Amounts are integer paise, INR only.','Отправляйте запросы с вашего сервера с ключом Bearer. Не раскрывайте ключ в браузере или URL. Суммы — целые пайсы, только INR.','使用限定权限的 Bearer 密钥从服务器发送请求。不要在浏览器或网址中暴露密钥。金额为整数派士，仅支持 INR。'][i]),el('pre','POST /wpay-api/v1/orders\nAuthorization: Bearer YOUR_API_KEY\nIdempotency-Key: shop-order-001\nContent-Type: application/json\n\n{"reference":"shop-order-001","amountMinor":"125050","currency":"INR","description":"Example order"}\n\nGET /wpay-api/v1/orders/ORDER_ID\nAuthorization: Bearer YOUR_API_KEY'),el('p',['Repeat the same idempotency key and payload after a timeout. NO_ROUTE creates no order or payment link. Poll order status; a submitted UTR is never proof of success.','При тайм-ауте повторяйте тот же ключ идемпотентности и данные. NO_ROUTE не создаёт заказ или ссылку. Проверяйте статус: отправленный UTR не доказывает успех.','超时后使用相同幂等键和请求内容重试。NO_ROUTE 不会创建订单或付款链接。查询订单状态；提交 UTR 不代表付款成功。'][i]),el('pre','Webhook signature v1:\nHMAC-SHA256(secret, timestamp + "." + eventId + "." + exactBodyBytes)\n\nx-wpay-timestamp: Unix seconds\nx-wpay-event-id: stable UUID\nx-wpay-signature: v1=hex\nx-wpay-secret-version: endpoint UUID'),el('p',['Verify the signature in constant time, allow at most five minutes of clock difference, and persist event IDs to reject replays. Return 2xx only after durable acceptance. Eight delivery attempts maximum; duplicates never mean a second payment. Rotation applies to new orders; retain the previous secret for pending deliveries.','Проверяйте подпись за постоянное время, допустимый сдвиг часов — пять минут. Сохраняйте ID событий против повторов. Возвращайте 2xx после надёжного сохранения. Максимум восемь попыток. Новый секрет применяется к новым заказам; сохраняйте старый для ожидающих доставок.','使用恒定时间验证签名，时钟偏差最多五分钟，持久保存事件 ID 以拒绝重放。可靠接收后再返回 2xx。最多尝试八次。密钥轮换适用于新订单；保留旧密钥以验证待送达事件。'][i]));container.replaceChildren(card);}
 root.WPayGatewayPage={render,text,docs,toPaise};
})(globalThis);
