'use strict';
(function(root){
 const money=n=>{const s=BigInt(n).toString().padStart(3,'0');return '₹'+s.slice(0,-2)+'.'+s.slice(-2);};
 function controls(args){const {el,action}=args;return {button(label,fn){const b=el('button',label,'btn sm burg');b.type='button';b.onclick=()=>action(fn);return b;},field(form,label,type='text'){const l=el('label',label),input=el('input',undefined,'control');input.type=type;input.required=true;l.append(input);form.append(l);return input;}};}
 function openButton(args,kind,id,reload){const {el,container,post,action}=args,{button,field}=controls(args);return button('Submit late UTR & proof',()=>{
  const dialog=el('dialog',undefined,'modal'),form=el('form');dialog.append(el('h2','Late payment review'),el('p','Submit only if you paid. Capacity is added after approval. Any existing User claim stays with that User.'),form);const utr=field(form,'12-digit UTR'),reason=field(form,'Reason for late submission'),file=field(form,'Payment proof','file');utr.pattern='[0-9]{12}';utr.maxLength=12;reason.minLength=3;reason.maxLength=300;file.accept='.png,.jpg,.jpeg,.pdf';const send=el('button','Send to review','btn burg');send.type='submit';form.append(send,button('Close',()=>{dialog.close();dialog.remove();}));container.append(dialog);dialog.showModal();
  form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;action(async()=>{const f=file.files[0];if(!f||f.size>1048576)throw Error('Select a proof up to 1 MiB');send.disabled=true;try{const bytes=new Uint8Array(await f.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));await post(kind+'/late/open',{id,utr:utr.value.trim(),reason:reason.value.trim(),proof:{name:f.name,data:btoa(raw)}});dialog.close();dialog.remove();await reload();}finally{send.disabled=false;}});};
 });}
 async function render(args,kind,host,offset=0){const {el,post,account}=args,{button,field}=controls(args),user=account.accountType==='user',section=el('section',undefined,'card pad');host.append(section);section.append(el('h2',user?'My late-payment reviews':'Late UTR & proof review'));const data=await post(kind+'/late/search',{offset}),table=el('table'),head=el('tr');for(const h of ['Order / User','Amount','Held','Status','Reason / Conflict','Actions'])head.append(el('th',h));table.append(head);
  const reload=async()=>{section.remove();await render(args,kind,host,offset);};
  for(const r of data.requests){const tr=el('tr');for(const value of [r.resource_id+' / '+r.user_name,money(r.amount_minor),r.status==='pending'?money(r.held_minor):'Released',r.status,[r.reason,r.conflict,r.resolution_reason].filter(Boolean).join(' · ')])tr.append(el('td',value));const cell=el('td');cell.append(button('View UTR / proof',async()=>{const p=await post(kind+'/late/proof',{id:r.id}),box=el('div');box.append(el('p','UTR: '+p.utr+' · Scan: '+p.scanState));const bytes=Uint8Array.from(atob(p.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),link=el('a','Download payment proof');link.href=url;link.download=p.name;box.append(link,button('Close proof',()=>{URL.revokeObjectURL(url);box.remove();}));cell.append(box);setTimeout(()=>URL.revokeObjectURL(url),60000);}));
   if(!user&&r.status==='pending'){const form=el('form'),reason=field(form,'Decision reason');reason.minLength=3;reason.maxLength=300;for(const act of ['approve','reject'])form.append(button(act==='approve'?'Approve payment':'Reject request',async()=>{if(!form.reportValidity())return;await post(kind+'/late/decide',{id:r.id,action:act,reason:reason.value});await reload();}));cell.append(form);}tr.append(cell);table.append(tr);
  }const wrap=el('div',undefined,'table-wrap');wrap.append(table);section.append(wrap);if(!data.requests.length)section.append(el('p','No late-payment requests.','muted'));if(offset)section.append(button('Previous',async()=>{section.remove();await render(args,kind,host,offset-50);}));if(data.hasMore)section.append(button('Next',async()=>{section.remove();await render(args,kind,host,offset+50);}));
 }
 root.WPayLateReview={render,openButton};
})(globalThis);
