'use strict';
/* Merchant-only presentation. All permissions, routing, balances and posting stay server-owned. */
globalThis.WPayMerchantPremium = { start() {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], root='/wpay-auth/roles/merchant/';
const state={account:null,page:'dashboard',csrf:null,cache:new Map(),pending:new Map(),epoch:0,offsets:{},bulk:null,security:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST':'—';
function decimal(v,scale=2){if(v===null||v===undefined)return '—';const b=BigInt(v),s=(b<0n?-b:b).toString().padStart(scale+1,'0');return (b<0n?'-':'')+s.slice(0,-scale)+'.'+s.slice(-scale);}
const money=(v,c='INR')=>v===undefined||v===null?'—':(c==='INR'?globalThis.WPayRoleDashboard.money(v):decimal(v,c==='USDT'?6:2)+' '+c);
function minor(v,scale=2){if(!new RegExp('^(0|[1-9][0-9]*)(\\.[0-9]{1,'+scale+'})?$').test(String(v)))throw Error('Enter a valid amount with up to '+scale+' decimal places.');const [a,b='']=String(v).split('.');return (BigInt(a)*10n**BigInt(scale)+BigInt(b.padEnd(scale,'0'))).toString();}
const human=v=>String(v??'—').replaceAll('_',' ');
const pill=v=>'<span class="pill '+(['successful','completed','delivered','approved','active'].includes(v)?'ok':['failed','rejected','expired','cancelled'].includes(v)?'bad':'info')+'">'+esc(human(v))+'</span>';
const button=(label,action,id='',extra='')=>'<button type="button" class="btn sm ghost" data-action="'+esc(action)+'" data-id="'+esc(id)+'" '+extra+'>'+esc(label)+'</button>';
const cells=a=>'<tr>'+a.map(v=>'<td>'+v+'</td>').join('')+'</tr>';
function rows(id,data,render){$('#'+id).innerHTML=data.length?data.map(render).join(''):'<tr><td colspan="12"><div class="empty">No records found</div></td></tr>';}
function text(s,v){const n=$(s);if(n)n.textContent=v??'—';}
function facts(obj){return '<div class="facts">'+Object.entries(obj).map(([k,v])=>'<div class="fact"><label>'+esc(k)+'</label><strong>'+esc(v??'—')+'</strong></div>').join('')+'</div>';}
function toast(v){text('#toast',v);$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),5000);}
const errors={AUTH_FAILED:'Your session expired or the sign-in details are incorrect. Please sign in again.',FORBIDDEN:'This action is not available for your account. Check approval and permissions with Admin.',UNAVAILABLE:'The service is temporarily unavailable. Please retry.',RATE_LIMITED:'Too many attempts. Please wait before retrying.',MFA_FAILED:'Authenticator code was not accepted. Use a fresh code.',INVALID_INPUT:'Check the form values and try again.',CONFLICT:'The record changed or the reference is already used. Refresh and check before retrying.',INSUFFICIENT_BALANCE:'Available balance is insufficient, including fees and reserved funds.',NO_ROUTE:'No eligible assigned route is available for this amount. No payment link was created.',RECENT_MFA_REQUIRED:'Please confirm your identity to continue.',MERCHANT_FX_UNCONFIGURED:'Admin has not configured your USDT rate.',TIMEOUT:'The response timed out. Retry the same form to safely check the original request.'};
function message(e){return errors[e.code]||e.message||'Request failed. Please retry.';}
async function request(route,method='GET',body,token){const owner=state.account?.id,abort=new AbortController(),timer=setTimeout(()=>abort.abort(),20000);try{const r=await fetch(root+route,{method,credentials:'same-origin',cache:'no-store',signal:abort.signal,headers:method==='POST'?{'Content-Type':'application/json',...(token?{'X-WPay-CSRF-Token':token}:{})}:{},...(body===undefined?{}:{body:JSON.stringify(body)})});let d;try{d=await r.json();}catch{throw Object.assign(Error('Service returned an invalid response.'),{code:'UNAVAILABLE'});}if(owner&&state.account?.id!==owner)throw Object.assign(Error('Account changed; response discarded.'),{code:'STALE_RESPONSE'});if(!r.ok||d.failure||d.error)throw Object.assign(Error(d.error||d.failure||'UNAVAILABLE'),{code:d.error||d.failure||'UNAVAILABLE'});return d;}catch(e){if(e.name==='AbortError')throw Object.assign(Error('TIMEOUT'),{code:'TIMEOUT'});throw e;}finally{clearTimeout(timer);}}
async function post(route,body={}){for(let attempt=0;attempt<2;attempt++){if(!state.csrf)state.csrf=request('csrf','POST',{});try{const token=await state.csrf,d=await request(route,'POST',body,token.csrfToken);if(d.stage||/^(login|register|logout|refresh|mfa\/|password\/)/.test(route))state.csrf=null;return d;}catch(e){state.csrf=null;if(e.code!=='CSRF_FAILED'||attempt)throw e;}}}
function cached(route){let p=state.cache.get(route);if(!p){p=request(route).catch(e=>{state.cache.delete(route);throw e;});state.cache.set(route,p);p.finally(()=>{if(state.cache.get(route)===p)state.cache.delete(route);}).catch(()=>{});}return p;}
function invalidate(){state.cache.clear();}
async function mutate(route,body){try{const d=await post(route,body);invalidate();return d;}catch(e){if(e.code!=='RECENT_MFA_REQUIRED')throw e;await reauthenticate();const d=await post(route,body);invalidate();return d;}}
// Retain a key after errors/timeouts; replace only on success or changed payload.
async function idempotent(route,body,key='idempotencyKey'){const signature=JSON.stringify(body),previous=state.pending.get(route);const entry=previous?.signature===signature?previous:{signature,id:crypto.randomUUID()};state.pending.set(route,entry);const d=await mutate(route,{...body,[key]:entry.id});state.pending.delete(route);return d;}
async function run(node,fn){if(node?.dataset.busy)return;const controls=node?.matches('form')?[...node.querySelectorAll('button')]:node?[node]:[];const before=controls.map(x=>x.disabled);if(node)node.dataset.busy='true';controls.forEach(x=>x.disabled=true);let errorBox=node?.matches('form')?node.querySelector('.form-error'):null;if(node?.matches('form')&&!errorBox){errorBox=document.createElement('p');errorBox.className='form-error';errorBox.setAttribute('role','alert');node.append(errorBox);}if(errorBox)errorBox.textContent='';try{return await fn();}catch(e){if(errorBox)errorBox.textContent=message(e);toast(message(e));if(e.code==='AUTH_FAILED'&&state.account)showLogin();}finally{controls.forEach((x,i)=>x.disabled=before[i]);if(node)delete node.dataset.busy;}}
function bindForm(id,fn){$('#'+id).addEventListener('submit',e=>{e.preventDefault();run(e.currentTarget,fn);});}
let modalResolve=null,previousFocus=null;
function closeModal(){if(modalResolve){modalResolve.reject(Error('Confirmation cancelled.'));modalResolve=null;}$('#modalBg').classList.remove('open');$('#modalBody').replaceChildren();previousFocus?.focus();}
function modal(title,subtitle,body){previousFocus=document.activeElement;text('#modalTitle',title);text('#modalSubtitle',subtitle);$('#modalBody').innerHTML=body;$('#modalBg').classList.add('open');$('#modalBody input, #modalBody button, #modalClose')?.focus();}
function field(id,label,type='text',required=true,value=''){return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><input class="control" id="'+id+'" type="'+type+'" '+(required?'required':'')+' value="'+esc(value)+'" autocomplete="'+(type==='password'?'current-password':'off')+'"></div>';}
function promptForm(title,body,fn,label='Confirm'){modal(title,'', '<form id="modalForm">'+body+'<p class="form-error" role="alert"></p><button class="btn primary" style="margin-top:14px">'+esc(label)+'</button></form>');bindForm('modalForm',fn);}
async function reauthenticate(){const s=await request('security');return new Promise((resolve,reject)=>{promptForm('Confirm your identity',field('stepPassword','Current password','password')+(s.enabled?field('stepCode','Authenticator code'):''),async()=>{await post('security/stepup',{password:$('#stepPassword').value,...(s.enabled?{code:$('#stepCode').value}:{})});modalResolve=null;closeModal();resolve();});modalResolve={reject};});}
function download(name,data,type='text/csv;charset=utf-8'){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const csvCell=v=>'"'+String(v??'').replace(/^[\s]*[=+\-@]/,m=>"'"+m).replaceAll('"','""')+'"';
function csv(data){if(!data.length)return 'No records\r\n';const keys=Object.keys(data[0]);return [keys,...data.map(r=>keys.map(k=>r[k]))].map(r=>r.map(csvCell).join(',')).join('\r\n');}
function showLogin(){state.account=null;state.csrf=null;state.security=null;state.bulk=null;state.pending.clear();state.offsets={};invalidate();state.epoch++;$$('#workspace tbody').forEach(n=>n.innerHTML='<tr><td colspan="12">Loading…</td></tr>');for(const id of ['linkPreview','reviewDetail','ticketThread','notificationList','ticketList','sessionList'])$('#'+id).replaceChildren();$$('#workspace input').forEach(n=>{if(n.type!=='checkbox')n.value='';});$('#workspace').hidden=true;$('#workspace').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#authStage').classList.add('hidden');$('#authStage').replaceChildren();$('#loginForm').classList.remove('hidden');$('#loginPassword').value='';closeModal();}
async function authStage(d){if(d.stage==='authenticated'){closeModal();return start();}$('#workspace').hidden=true;$('#workspace').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginForm').classList.add('hidden');const host=$('#authStage');host.classList.remove('hidden');host.replaceChildren();if(d.stage==='enroll'){const setup=await post('mfa/setup');host.innerHTML='<h3>Set up authenticator</h3><img alt="Authenticator setup QR" src="'+esc(setup.qrDataUrl)+'"><p class="secret">'+esc(setup.setupKey)+'</p>';}if(['save-recovery','recovery-codes'].includes(d.stage)){host.innerHTML='<h3>Save your recovery codes</h3><p>Each code can be used once. Store them securely.</p><pre class="secret">'+esc((d.recoveryCodes||[]).join('\n'))+'</pre><form id="recoveryAck"><label><input type="checkbox" required> I saved these codes securely</label><button class="btn primary">Continue</button></form>';bindForm('recoveryAck',async()=>d.stage==='save-recovery'?authStage(await post('mfa/complete',{saved:true})):start());return;}
if(d.stage==='password-reset'){host.innerHTML='<h3>Set your new password</h3><form id="resetForm">'+field('resetPassword','New password','password')+field('resetConfirm','Confirm new password','password')+'<button class="btn primary">Save password</button></form>';bindForm('resetForm',async()=>{checkPassword($('#resetPassword').value,$('#resetConfirm').value);await authStage(await post('password/reset',{password:$('#resetPassword').value}));});return;}
host.insertAdjacentHTML('beforeend','<form id="factorForm">'+field('factorCode',d.stage==='recover'?'Recovery code':'Authenticator code')+'<button class="btn primary">Verify</button></form><div class="actions">'+button('Use recovery code','recovery')+button('Back to sign in','back-login')+'</div>');bindForm('factorForm',async()=>authStage(await post(d.stage==='recover'?'mfa/recover':'mfa/verify',d.stage==='recover'?{recoveryCode:$('#factorCode').value}:{code:$('#factorCode').value})));
}
function checkPassword(p,confirmation=p){if(p!==confirmation)throw Error('Passwords must match.');if(!globalThis.WPayPasswordPolicy.valid(p,'establish'))throw Error(globalThis.WPayPasswordPolicy.text('en','establish'));}
async function start(){const account=await request('me');if(account.accountType!=='merchant')throw Error('Please sign in with a Merchant account.');state.account=account;invalidate();$('#loginPassword').value='';$('#authStage').replaceChildren();$('#loginView').classList.add('hidden');$('#workspace').hidden=false;$('#workspace').classList.remove('hidden');const initials=account.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();text('.sidebar-foot strong',account.name);text('.sidebar-foot small','Merchant · '+human(account.approvalStatus));text('.sidebar-foot .avatar',initials);text('.merchant-chip strong',account.name);text('.merchant-chip-avatar',initials);text('.hero-kicker','Welcome, '+account.name);const page=location.hash.slice(1);await navigate($('#page-'+page)?page:'dashboard');}
async function navigate(page,force=false){if(!state.account)return;if(!$('#page-'+page))return;state.page=page;const epoch=++state.epoch;if(force)invalidate();$$('.page').forEach(n=>n.classList.toggle('active',n.id==='page-'+page));$$('.nav-item').forEach(n=>{n.classList.toggle('active',n.dataset.page===page);n.setAttribute('aria-current',n.dataset.page===page?'page':'false');});$('#sidebar').classList.remove('open');history.replaceState(null,'','#'+page);const host=$('#page-'+page);host.setAttribute('aria-busy','true');text('#pageStatus','Loading…');$('#pageStatus').classList.remove('error');try{await loaders[page]();if(epoch===state.epoch)text('#pageStatus','Updated '+date(new Date())+(state.account.approvalStatus!=='approved'?' · Account '+human(state.account.approvalStatus):''));}catch(e){if(epoch===state.epoch){text('#pageStatus',message(e));$('#pageStatus').classList.add('error');}if(e.code==='AUTH_FAILED')showLogin();}finally{host.removeAttribute('aria-busy');}}
function pager(id,offset,more,fn,step=50){let p=$('#'+id+'Pager');if(!p){p=document.createElement('div');p.id=id+'Pager';p.className='pager';$('#'+id).closest('.table-card')?.append(p);}p.replaceChildren();for(const [label,next,enabled]of [['Previous',Math.max(0,offset-step),offset>0],['Next',offset+step,more]]){const b=document.createElement('button');b.className='btn sm ghost';b.textContent=label;b.disabled=!enabled;b.onclick=()=>run(b,()=>fn(next));p.append(b);}}
function metrics(page,values,notes=[]){$$('#page-'+page+' .metric-value').forEach((n,i)=>n.textContent=values[i]??'—');$$('#page-'+page+' .metric-foot').forEach((n,i)=>n.textContent=notes[i]||'');}
function chart(id,data){const svg=$('#'+id);if(!data.length){svg.innerHTML='<text x="380" y="140" text-anchor="middle" fill="currentColor">No successful payment volume in this period</text>';return;}const max=data.reduce((m,d)=>BigInt(d.volume)>m?BigInt(d.volume):m,1n),points=data.map((d,i)=>[50+(data.length===1?330:i*650/(data.length-1)),225-Number(BigInt(d.volume)*18000n/max)/100]);svg.innerHTML='<path d="M50 35V225H715" fill="none" stroke="currentColor" opacity=".2"/><polyline fill="none" stroke="#c982a2" stroke-width="3" points="'+points.map(p=>p.join(',')).join(' ')+'"/>'+points.map((p,i)=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="4" fill="#E8CA7D"><title>'+esc(data[i].day+' · '+money(data[i].volume))+'</title></circle>').join('')+'<text x="50" y="260" fill="currentColor" font-size="12">'+esc(data[0].day)+'</text><text x="715" y="260" text-anchor="end" fill="currentColor" font-size="12">'+esc(data.at(-1).day)+'</text><text x="50" y="24" fill="currentColor" font-size="12">Peak '+esc(money(max))+'</text>';}
async function dashboard(){const settled=await Promise.allSettled([cached('gateway/summary'),cached('payout/summary'),post('gateway/search',{offset:0}),post('payout/search',{offset:0,limit:5,state:'submitted'}),post('gateway/analytics',{days:30})]);const [g,p,o,q,a]=settled.map(r=>r.status==='fulfilled'?r.value:null);if(g){text('#dashAvailable',money(g.available));text('#dashVolume',money(g.successfulVolumeMinor));const strong=$$('.dashboard-primary-metrics strong');strong[2].textContent=String(g.counts.successful||0);strong[3].textContent=g.successRate===null?'—':(g.successRate*100).toFixed(1)+'%';text('#dashHold',money(g.held));}if(p){text('#dashPayoutOrders',p.orderCount);text('[data-page="payout-review"] .tag',p.counts.submitted||0);}if(g){const frozen=BigInt(g.frozenMinor||0);text('#dashFrozen',money(frozen));if(p)text('#dashHold',money(BigInt(g.held)-frozen+BigInt(p.reserved||0)+BigInt(p.merchantUsdt?.reserved||0)));}if(o)rows('dashOrders',o.orders.slice(0,5),r=>cells([button(r.reference,'order',r.id),money(r.amountMinor),pill(r.status),esc(r.origin)]));if(q)rows('dashPayoutReviews',q.orders,r=>cells([button(r.reference,'payout',r.id),money(r.amountMinor),'Submitted',pill(r.status)]));if(a)chart('dashChart',a.days);$('#healthList').innerHTML=[['Payments',g?'Connected to your payment gateway':'Unavailable'],['Payouts',p?String(p.openCount)+' open requests':'Unavailable'],['USDT withdrawal',p?.merchantUsdt?.rate?'Admin rate: ₹'+p.merchantUsdt.rate:'Admin rate not configured'],['Account',human(state.account.approvalStatus)+(state.account.operationsEnabled?' · Operations enabled':'')]].map(([title,description])=>'<div class="item"><div class="item-main"><strong>'+esc(title)+'</strong><small>'+esc(description)+'</small></div></div>').join('');const bad=settled.find(r=>r.status==='rejected');if(bad)throw bad.reason;}
async function analytics(){const days=[1,7,30][$('#analyticsWindow').selectedIndex],a=await post('gateway/analytics',{days});state.analytics=a;const totals=a.channels.reduce((t,c)=>{for(const k of ['successful','pending','failed','expired'])t[k]+=c[k];return t;},{successful:0,pending:0,failed:0,expired:0});const denominator=totals.successful+totals.failed;metrics('analytics',[denominator?(totals.successful/denominator*100).toFixed(1)+'%':'—',totals.pending,totals.failed,totals.expired],['Successful / successful + failed','Awaiting confirmation','Failed payments','Expired payment links']);text('#page-analytics .metrics .metric:last-child .metric-top','Expired');chart('analyticsChart',a.days);rows('channelRows',a.channels,c=>cells([esc(c.origin),c.total,c.successful,c.pending,c.failed,money(c.volume),c.successful+c.failed?(c.successful/(c.successful+c.failed)*100).toFixed(1)+'%':'—']));}
async function orderHistory(page,offset=state.offsets[page]||0){state.offsets[page]=offset;const d=await post('gateway/search',{search:page==='orders'?$('#orderSearch').value.trim():'',status:'',offset});if(page==='links')rows('linkRows',d.orders,r=>cells([esc(r.reference)+'<small class="muted"> · '+esc(r.origin)+'</small>',money(r.amountMinor),date(r.createdAt),date(r.expiresAt),pill(r.status),button('Open / QR','order',r.id)]));else rows('orderRows',d.orders,r=>cells([button(r.id,'order',r.id),esc(r.reference),money(r.amountMinor),esc(r.origin),pill(r.status),esc(human(r.evidenceStatus)),pill(r.callbackStatus)]));pager(page==='links'?'linkRows':'orderRows',offset,d.hasMore,n=>orderHistory(page,n));}
async function linkPage(){await Promise.all([orderHistory('links'),cached('gateway/summary').then(g=>text('#adminLinkTtlText',g.linkTtlSeconds+' seconds'))]);}
function linkDetails(r){let url;try{url=new URL(r.paymentUrl);if(url.origin!==location.origin||!url.pathname.startsWith('/wpay-pay/'))throw Error();}catch{throw Error('The gateway did not return a valid payment link.');}return facts({Reference:r.reference,Amount:money(r.amountMinor),Status:human(r.status),Created:date(r.createdAt),Expires:date(r.expiresAt),Origin:r.origin,Webhook:human(r.callbackStatus)})+'<p class="link-url">'+esc(url.href)+'</p>'+(r.paymentQr?.startsWith('data:image/png;base64,')?'<img class="live-qr" alt="Payment link QR" src="'+esc(r.paymentQr)+'">':'')+'<div class="actions" style="margin-top:14px"><a class="btn primary" href="'+esc(url.href)+'" target="_blank" rel="noopener noreferrer">Open checkout</a>'+button('Copy link','copy-link',url.href)+'</div>';}
async function orderDetail(id){const r=await post('gateway/get',{id});modal('Payment link',r.reference,linkDetails(r));}
async function ledger(page='ledger',offset=state.offsets[page]||0){state.offsets[page]=offset;const filter=$('#txFilter').value;const d=await post('business/ledger/search',{ownerId:null,reference:'',type:page==='transactions'?({Fee:'merchant_platform_fee',Payout:'merchant_payout_principal',Order:'merchant_gross'}[filter]||''):'',offset});rows(page==='ledger'?'ledgerRows':'txRows',d.entries,r=>page==='ledger'?cells([date(r.created_at),esc(r.reference_id),esc(human(r.ledger_type)),r.direction==='debit'?money(r.amount_minor,r.currency):'—',r.direction==='credit'?money(r.amount_minor,r.currency):'—','Posted']):cells([date(r.created_at),esc(human(r.ledger_type)),esc(r.reference_id),r.direction==='debit'?money(r.amount_minor,r.currency):'—',r.direction==='credit'?money(r.amount_minor,r.currency):'—',esc(r.currency),'Posted']));pager(page==='ledger'?'ledgerRows':'txRows',offset,d.nextOffset!==null,n=>ledger(page,n));if(page==='ledger'){const b=await cached('business/summary');metrics('ledger',[money(b.gross),money((BigInt(b.fees)+BigInt(b.payoutFees)).toString()),money(b.held),money(b.available)]);}}
async function payouts(offset=state.offsets.payouts||0){state.offsets.payouts=offset;const [s,d]=await Promise.all([cached('payout/summary'),post('payout/search',{offset,limit:25})]);text('#payoutAvailableBalance',money(s.available));text('#bulkAvailableBalance',money(s.available));rows('payoutRows',d.orders,r=>cells([button(r.id,'payout',r.id),button('View beneficiary','payout',r.id),money(r.amountMinor),esc(r.reference),pill(r.status),date(r.createdAt)]));pager('payoutRows',offset,d.hasMore,n=>payouts(n),25);}
async function reviewPage(offset=state.offsets.review||0){state.offsets.review=offset;const d=await post('payout/search',{offset,limit:25,state:'submitted'});text('#reviewCount',d.orders.length+(d.hasMore?'+':'')+' pending');$('#reviewList').innerHTML=d.orders.length?d.orders.map(r=>'<div class="item"><div class="item-main"><strong>'+esc(r.reference)+'</strong><small>'+money(r.amountMinor)+' · '+date(r.submittedAt)+'</small></div>'+button('Review','review',r.id)+'</div>').join(''):'<div class="empty">No payouts awaiting review</div>';if(offset||d.hasMore)$('#reviewList').insertAdjacentHTML('beforeend',button('Previous','review-prev','',offset?'':'disabled')+button('Next','review-next','',d.hasMore?'':'disabled'));}
async function payoutDetail(id,inline=false){const r=await post('payout/get',{id});const body=facts({Reference:r.reference,Amount:money(r.amountMinor),Fees:money(BigInt(r.percentageFeeMinor)+BigInt(r.fixedFeeMinor)),Reserved:money(r.reserveMinor),Status:human(r.status),Beneficiary:r.beneficiary?.beneficiaryName,Bank:r.beneficiary?.bankName,Account:r.beneficiary?.accountNumber,IFSC:r.beneficiary?.ifsc,UPI:r.beneficiary?.upiId,UTR:r.evidence?.utr,Proof:r.proof?r.proof.name+' · '+human(r.proof.scanState):'Not submitted',Created:date(r.createdAt),Completed:date(r.completedAt)})+(r.status==='submitted'?'<p class="notice">Review the submitted evidence. Approval is processed by the server under the existing verification rules.</p>'+button('Approve','payout-approve',id)+button('Reject','payout-reject',id):r.status==='open'?button('Cancel payout','payout-cancel',id):'');if(inline)$('#reviewDetail').innerHTML=body;else modal('Payout details',r.reference,body);}
async function fees(offset=state.offsets.fees||0){state.offsets.fees=offset;const d=await post('panel/fees',{offset,limit:25});if(offset===0){const r=d.rows[0];metrics('fees',r?[r.payinFee+'%',r.payoutFee+'%',String(r.fixedPayoutFee)+' '+r.fixedFeeCurrency,'v'+r.version]:['—','—','—','—'],['Current version','Current version','Per successful payout',r?date(r.effectiveAt):'Not configured']);}rows('feeRows',d.rows,(r,i)=>cells(['v'+r.version,esc(r.payinFee)+'%',esc(r.payoutFee)+'%',esc(r.fixedPayoutFee)+' '+esc(r.fixedFeeCurrency),date(r.effectiveAt),pill(offset===0&&i===0?'active':'historical')]));pager('feeRows',offset,d.nextOffset!==null,n=>fees(n),25);}
async function holds(){const h=await cached('business/holds');rows('holdRows',h.holds,r=>cells([esc(r.id),esc(r.reference),money(r.amount_minor,r.currency),esc(r.reason)+' · '+esc(human(r.category)),pill(r.state)]));}
async function settlement(){const d=await cached('payout/merchant-usdt');state.settlement=d;text('#usdtAvailableInr',money(d.available));text('#adminUsdtRate',d.rate?'₹'+d.rate+' / USDT':'Not configured');text('#maxUsdtQuote',money(d.maxUsdtMinor,'USDT'));text('#rateVersion',d.rateVersion?'Rate v'+d.rateVersion:'Not configured');const fs=$$('#page-settlement .facts .fact strong');fs[3].textContent=d.network||'—';fs[4].textContent=d.rate?'₹'+d.rate+' / USDT':'—';$('#merchantUsdtWithdrawForm button[type="submit"], #merchantUsdtWithdrawForm button:not([type])').disabled=!!d.creationDisabled;rows('merchantUsdtRows',d.requests||[],r=>cells([esc(r.id),money(r.inrMinor),esc(r.rate),money(r.usdtMinor,'USDT'),button('View destination','usdt-detail',r.id),pill(r.state)+(['requested','review'].includes(r.state)?button('Cancel','usdt-cancel',r.id):'')]));pager('merchantUsdtRows',d.offset||0,d.hasMore,n=>settlementHistory(n));quoteUsdt();}
async function settlementHistory(offset){const d=await post('payout/merchant-usdt/search',{offset,limit:50});rows('merchantUsdtRows',d.requests,r=>cells([esc(r.id),money(r.inrMinor),esc(r.rate),money(r.usdtMinor,'USDT'),button('View destination','usdt-detail',r.id),pill(r.state)+(['requested','review'].includes(r.state)?button('Cancel','usdt-cancel',r.id):'')]));pager('merchantUsdtRows',offset,d.hasMore,n=>settlementHistory(n));}
function quoteUsdt(){try{const d=state.settlement;if(!d?.rate)throw Error();const rate=BigInt(minor(String(d.rate),6));text('#merchantUsdtQuote',money(BigInt(minor($('#merchantUsdtInr').value||'0'))*10000000000n/rate,'USDT'));}catch{text('#merchantUsdtQuote','—');}}
async function keys(){const d=await cached('gateway/keys');rows('apiKeyRows',d.keys,r=>cells([esc(r.label),esc(r.prefix),esc(r.scopes.join(', ')),date(r.created_at),date(r.last_used_at),pill(r.revoked_at?'revoked':'active'),r.revoked_at?'—':button('Revoke','revoke-key',r.id)]));}
async function webhooks(){const d=await cached('gateway/webhooks');$('#webhookUrl').value=d.endpoint?.url||'';rows('webhookRows',d.events,r=>cells([esc(r.id),esc(r.event_type),esc(r.order_id||'—'),pill(r.state),r.attempts,r.last_code??'—',r.state==='pending'&&r.attempts<8?button('Retry now','retry-webhook',r.id):'—']));$('#deliveryList').innerHTML=d.events.length?d.events.slice(0,4).map(r=>'<div class="item"><div class="item-main"><strong>'+esc(r.event_type)+'</strong><small>'+date(r.created_at)+(r.last_code?' · HTTP '+esc(r.last_code):'')+'</small></div>'+pill(r.state)+'</div>').join(''):'<div class="empty">No webhook events</div>';}
async function logs(){const d=await cached('gateway/logs');rows('logRows',d.rows,r=>cells([date(r.created_at),esc(human(r.operation)),esc(r.id)]));}
async function notifications(offset=0){const d=await post('panel/notifications',{offset,limit:100});state.notifications=d.rows;let seen=0;try{seen=Number(localStorage.getItem('wpay:merchant:'+state.account.id+':read')||0);}catch{}$('#notificationList').innerHTML=d.rows.length?d.rows.map(r=>'<div class="item '+(+new Date(r.created_at)>seen?'unread':'')+'"><div class="item-main"><strong>'+esc(human(r.event))+'</strong><small>'+date(r.created_at)+'</small></div>'+pill(+new Date(r.created_at)>seen?'new':'read')+'</div>').join(''):'<div class="empty">'+(d.preferences.in_app_notifications?'No account notifications':'Notifications are disabled in Preferences')+'</div>';if(offset||d.nextOffset!==null)$('#notificationList').insertAdjacentHTML('beforeend',button('Previous','notifications-page',Math.max(0,offset-100),offset?'':'disabled')+button('Next','notifications-page',d.nextOffset??'',d.nextOffset===null?'disabled':''));}
async function support(offset=0){const d=await post('panel/support',{offset,limit:25});state.tickets=d.rows;$('#newTicket').disabled=!d.canWrite;$('#ticketList').innerHTML=d.rows.length?d.rows.map(r=>'<div class="item"><div class="item-main"><strong>'+esc(r.subject)+'</strong><small>'+date(r.created_at)+'</small></div>'+pill(r.status)+button('Open','ticket',r.id)+'</div>').join(''):'<div class="empty">No support tickets</div>';if(offset||d.nextOffset!==null)$('#ticketList').insertAdjacentHTML('beforeend',button('Previous','support-page',Math.max(0,offset-25),offset?'':'disabled')+button('Next','support-page',d.nextOffset??'',d.nextOffset===null?'disabled':''));}
async function security(){const s=await request('security');state.security=s;text('#mfaStatus',s.enabled?'Enabled':'Optional · Off');text('#mfaDescription',s.enabled?'Authenticator protects your account':'Sign in with email and password');$('#mfaActions').innerHTML=s.enabled?button('Disable','security-disable')+button('Replace authenticator','security-replace')+button('New recovery codes','security-regenerate'):button('Enable authenticator','security-enable');$('#sessionList').innerHTML=s.sessions.map(r=>'<div class="item"><div class="item-main"><strong>'+(r.current?'Current session':'Active session')+'</strong><small>Created '+date(r.createdAt)+' · Last active '+date(r.lastSeenAt)+' · Expires '+date(r.expiresAt)+'</small></div>'+pill(r.current?'current':'active')+'</div>').join('');let code=$('#passwordCodeField');if(s.enabled&&!code){$('#newPassword').closest('.field').insertAdjacentHTML('afterend','<div id="passwordCodeField">'+field('passwordCode','Authenticator code')+'</div>');}if(!s.enabled&&code)code.remove();}
async function profile(){const [p,n]=await Promise.all([request('panel/profile'),request('panel/notifications')]);$('#businessName').value=state.account.name;$('#profileEmail').value=state.account.email;$('#profileId').value=state.account.id;$('#profileForm button').disabled=!p.canEdit;$('#locale').value=state.account.locale;$('#inAppNotifications').checked=n.preferences.in_app_notifications;}
function range(){const from=$('#reportFrom').value,to=$('#reportTo').value;const start=new Date(from+'T00:00:00+05:30'),end=new Date(new Date(to+'T00:00:00+05:30').getTime()+86400000);if(!from||!to||!Number.isFinite(+start)||!Number.isFinite(+end)||end<=start||end-start>31*86400000)throw Error('Select a valid date range of up to 31 days.');return {from:start.toISOString(),to:end.toISOString()};}
async function exportReport(kind){const dates=range();if(kind==='ledger'||kind==='fees'){let offset=0,parts=[];do{const d=await post('panel/reports/export',{...dates,offset,limit:100});parts.push(offset?d.csv.split('\r\n').slice(1).join('\r\n'):d.csv);offset=d.nextOffset;if(offset>10000)throw Error('Too many records. Select a smaller date range.');}while(offset!==null);const all=parts.filter(Boolean).join('\r\n');if(kind==='fees'){// Use structured entries for safe filtering; CSV parsing is deliberately avoided.
let offset=0,entries=[];do{const d=await post('panel/reports',{...dates,offset,limit:100});entries.push(...d.rows.filter(r=>/fee/.test(r.ledger_type)));offset=d.nextOffset;if(offset>10000)throw Error('Select a smaller date range.');}while(offset!==null);download('wpay-fees.csv',csv(entries));}else download('wpay-ledger.csv',all);return;}
let offset=0,all=[],more=true;while(more){const d=kind==='orders'?await post('gateway/search',{offset}):await post('payout/search',{offset,limit:100});all.push(...d.orders.filter(r=>+new Date(r.createdAt)>=+new Date(dates.from)&&+new Date(r.createdAt)<+new Date(dates.to)));more=d.hasMore;offset+=kind==='orders'?50:100;if(offset>10000&&more)throw Error('Export exceeds 10,000 history records. Contact Admin for a larger export.');}download('wpay-'+kind+'.csv',csv(all));}
const loaders={dashboard,analytics,links:linkPage,orders:()=>orderHistory('orders'),transactions:()=>ledger('transactions'),payouts,'payout-review':reviewPage,api:keys,webhooks,logs,docs:async()=>{},fees,ledger,holds,settlement,reports:async()=>{},notifications,support,security,profile};
const actions={
 'usdt-detail':async id=>{const r=await post('payout/merchant-usdt/get',{id});modal('USDT withdrawal',r.id,facts({Amount:money(r.inrMinor),USDT:money(r.usdtMinor,'USDT'),Rate:r.rate,Network:r.network,Address:r.destination?.address,Status:human(r.state),Created:date(r.createdAt),Completed:date(r.completedAt)}));},
 'order':orderDetail,'payout':id=>payoutDetail(id),'review':id=>payoutDetail(id,true),
 'copy-link':async url=>{await navigator.clipboard.writeText(url);toast('Payment link copied.');},
 'recovery':()=>authStage({stage:'recover'}),'back-login':showLogin,
 'review-prev':()=>reviewPage(Math.max(0,(state.offsets.review||0)-25)), 'review-next':()=>reviewPage((state.offsets.review||0)+25),
 'notifications-page':id=>notifications(Number(id)),'support-page':id=>support(Number(id)),
 'ticket':id=>{const r=state.tickets.find(r=>r.id===id);if(!r)return;$('#ticketThread').innerHTML='<h3>'+esc(r.subject)+'</h3>'+pill(r.status)+'<p style="white-space:pre-wrap">'+esc(r.message)+'</p><small>'+date(r.created_at)+'</small>'+(r.reply?'<hr><strong>Support response</strong><p style="white-space:pre-wrap">'+esc(r.reply)+'</p><small>'+date(r.replied_at)+'</small>':'<p class="muted">Awaiting a support response.</p>');},
 'revoke-key':id=>promptForm('Revoke API credential','<p>This credential will stop accepting new API requests.</p>',async()=>{await mutate('gateway/keys/revoke',{id});closeModal();await keys();toast('API credential revoked.');},'Revoke'),
 'retry-webhook':async id=>{await mutate('gateway/webhooks/retry',{id});await webhooks();toast('Webhook retry queued.');},
 'usdt-cancel':id=>promptForm('Cancel USDT withdrawal',field('cancelReason','Reason'),async()=>{await mutate('payout/merchant-usdt/transition',{id,action:'cancel',reason:$('#cancelReason').value});closeModal();await settlement();toast('Withdrawal cancelled.');}),
};
for(const action of ['approve','reject','cancel'])actions['payout-'+action]=id=>promptForm(human(action)+' payout',field('reviewReason','Reason'),async()=>{await mutate('payout/review',{id,action,reason:$('#reviewReason').value});closeModal();text('#reviewDetail','Select a payout');await navigate(state.page,true);toast('Payout updated.');});
for(const action of ['enable','disable','replace','regenerate'])actions['security-'+action]=async()=>{const s=await request('security');promptForm(human(action)+' authenticator',field('securityPassword','Current password','password')+(s.enabled?field('securityCode','Authenticator code'):''),async()=>{const d=await post('security/'+action,{password:$('#securityPassword').value,...(s.enabled?{code:$('#securityCode').value}:{})});closeModal();invalidate();if(d.stage)await authStage(d);else await security();});};
document.addEventListener('click',e=>{const n=e.target.closest('[data-action],[data-page],[data-go],[data-report]');if(!n||n.disabled)return;if(n.dataset.action){e.preventDefault();if(actions[n.dataset.action])run(n,()=>actions[n.dataset.action](n.dataset.id));}else if(n.dataset.report)run(n,()=>exportReport(n.dataset.report));else if(state.account)navigate(n.dataset.page||n.dataset.go);else if(n.dataset.go==='support')modal('Merchant sign-in support','', '<p>Contact your WPay administrator for account approval or a temporary password reset. Sign in to access your support tickets.</p>');});
$$('.quick[data-go]').forEach(n=>{n.tabIndex=0;n.setAttribute('role','button');n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();n.click();}};});
$('#modalClose').onclick=closeModal;$('#modalBg').onclick=e=>{if(e.target.id==='modalBg')closeModal();};document.addEventListener('keydown',e=>{if(!$('#modalBg').classList.contains('open'))return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const nodes=[...$('#modalBg').querySelectorAll('button,a,input,select,textarea')].filter(n=>!n.disabled&&n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
bindForm('loginForm',async()=>{text('#loginMessage','Signing in…');try{await authStage(await post('login',{email:$('#loginEmail').value.trim(),password:$('#loginPassword').value}));text('#loginMessage','');}finally{$('#loginPassword').value='';}});
$('#forgotPassword').onclick=e=>{e.preventDefault();modal('Reset your password','', '<p>Contact your WPay administrator for a temporary password. Sign in with that password to securely set a new one.</p>');};
$('#registerMerchant').onclick=()=>promptForm('Create Merchant account',field('registerName','Business name')+field('registerEmail','Email address','email')+field('registerPassword','Password','password')+field('registerConfirm','Confirm password','password')+'<p class="muted">'+esc(globalThis.WPayPasswordPolicy.text('en','establish'))+'</p>',async()=>{checkPassword($('#registerPassword').value,$('#registerConfirm').value);await post('register',{accountType:'merchant',name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),password:$('#registerPassword').value});modal('Registration submitted','','<p>Your Merchant account is pending Admin approval. Sign in after approval.</p>');});
$('#logoutBtn').onclick=()=>run($('#logoutBtn'),async()=>{await post('logout');state.pending.clear();showLogin();});
$('#logoutAll').onclick=()=>promptForm('Logout all sessions','<p>This signs you out on all devices, including this one.</p>',async()=>{await post('logout-all');state.pending.clear();showLogin();},'Logout all');
$('#refreshPage').onclick=()=>navigate(state.page,true);
$('#mobileMenuBtn').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#mobileMenuBtn').setAttribute('aria-expanded',String(open));};
$('#themeBtn').onclick=()=>{const light=document.documentElement.classList.toggle('light');try{localStorage.setItem('merchant-theme',light?'light':'dark');}catch{}};
try{document.documentElement.classList.toggle('light',localStorage.getItem('merchant-theme')==='light');}catch{}
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#orderSearch').value=e.target.value.trim();state.offsets.orders=0;navigate('orders');}});
let searchTimer;$('#orderSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>run(null,()=>orderHistory('orders',0)),300);});
$('#analyticsWindow').onchange=()=>run(null,analytics);$('#analyticsCsv').onclick=()=>run($('#analyticsCsv'),async()=>{if(!state.analytics)await analytics();download('wpay-analytics.csv',csv(state.analytics.channels));});
$('#txFilter').onchange=()=>run(null,()=>ledger('transactions',0));
$('#openCreateLink').onclick=()=>{$('#linkRef').focus();$('#linkForm').scrollIntoView({behavior:'smooth',block:'center'});};
bindForm('linkForm',async()=>{const body={reference:$('#linkRef').value.trim(),amountMinor:minor($('#linkAmount').value),currency:'INR',description:$('#linkDescription').value.trim()};try{const r=await idempotent('gateway/create',body),detail=await post('gateway/get',{id:r.id});$('#linkPreview').innerHTML=linkDetails(detail);await orderHistory('links',0);toast('Payment link created.');}catch(e){if(e.code==='NO_ROUTE'){const d=await post('gateway/route-status',{amountMinor:body.amountMinor});throw Error(errors.NO_ROUTE+' '+d.reasons.map(human).join(', '));}throw e;}});
$('#payoutTabs').onclick=e=>{const n=e.target.closest('[data-payout-tab]');if(!n)return;$$('[data-payout-tab]').forEach(b=>b.classList.toggle('active',b===n));const bulk=n.dataset.payoutTab==='bulk';$('#singlePayoutPanel').classList.toggle('hidden',bulk);$('#bulkPayoutPanel').classList.toggle('hidden',!bulk);};
bindForm('payoutForm',async()=>{await idempotent('payout/create',{reference:$('#poRef').value.trim(),beneficiaryName:$('#poName').value.trim(),bankName:$('#poBank').value.trim(),accountNumber:$('#poAccount').value.trim(),ifsc:$('#poIfsc').value.trim().toUpperCase(),upiId:$('#poUpi').value.trim(),amountMinor:minor($('#poAmount').value),note:''});$('#payoutForm').reset();await payouts(0);toast('Payout request created; principal and fees reserved.');});
$('#downloadBulkTemplate').onclick=()=>run($('#downloadBulkTemplate'),async()=>{const d=await request('payout/template');download(d.name,Uint8Array.from(atob(d.data),c=>c.charCodeAt(0)),'application/octet-stream');});
$('#bulkPayoutFile').onchange=()=>run(null,async()=>{state.bulk=null;$('#createBulkPayouts').disabled=true;const file=$('#bulkPayoutFile').files[0];if(!file)return;if(file.size>1048576)throw Error('The file must be 1 MB or smaller.');text('#bulkUploadStatus','Validating all rows and current balance…');const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const body={idempotencyKey:crypto.randomUUID(),file:{name:file.name,data:btoa(raw)}};const d=await post('payout/bulk/validate',body);state.bulk=d.valid?body:null;text('#bulkRowCount',d.rows.length);text('#bulkTotal',money(d.batchReserveMinor));text('#bulkAvailableBalance',money(d.availableMinor));text('#bulkBalanceBadge',d.valid?'Validated · fees included':'Fix errors before creating');text('#bulkUploadStatus',d.valid?'All rows valid. Remaining balance after reservation: '+money(d.remainingMinor):[...d.errors.map(r=>'Row '+(r.row||'—')+': '+human(r.error)),...(d.exceedsAvailable?['Insufficient available balance including fees.']:[])].join('\n'));rows('bulkPreviewRows',d.rows,(r)=>cells([esc(r.row??'—'),esc(r.beneficiaryName),esc(r.bankName),esc(r.accountNumber),esc(r.ifsc),esc(r.upiId),money(r.amountMinor),esc(r.reference),r.existingReference?'Existing reference':'Reserve '+money(r.reserveMinor)]));$('#createBulkPayouts').disabled=!d.valid;});
$('#createBulkPayouts').onclick=()=>run($('#createBulkPayouts'),async()=>{if(!state.bulk)throw Error('Validate the file first.');const d=await mutate('payout/bulk',state.bulk);if(d.errors?.length)throw Error(d.errors.map(r=>'Row '+r.row+': '+human(r.error)).join('\n'));state.bulk=null;$('#bulkPayoutFile').value='';text('#bulkUploadStatus','Bulk payout requests created.');await payouts(0);toast('Bulk payout requests created.');}).then(()=>{$('#createBulkPayouts').disabled=!state.bulk;});
$('#createApiKey').onclick=()=>promptForm('Create API credential',field('keyLabel','Label')+'<label><input id="keyRead" type="checkbox" checked> Read orders</label><br><label><input id="keyWrite" type="checkbox"> Create orders</label>',async()=>{const scopes=[$('#keyRead').checked?'orders:read':null,$('#keyWrite').checked?'orders:write':null].filter(Boolean);if(!scopes.length)throw Error('Select at least one scope.');const d=await mutate('gateway/keys/create',{label:$('#keyLabel').value.trim(),scopes});modal('Save API credential','Shown once. Store it on your server.', '<pre class="secret">'+esc(d.key||d.secret)+'</pre>');await keys();});
bindForm('webhookForm',async()=>{const d=await mutate('gateway/webhooks/configure',{url:$('#webhookUrl').value.trim()});modal('Save webhook signing secret','Shown once. Update your webhook signature verifier.', '<pre class="secret">'+esc(d.secret)+'</pre>');await webhooks();});
$('#merchantUsdtInr').oninput=quoteUsdt;$('#useFullBalance').onclick=()=>{if(state.settlement?.available!==undefined){$('#merchantUsdtInr').value=decimal(state.settlement.available);quoteUsdt();}};
bindForm('merchantUsdtWithdrawForm',async()=>{if(state.settlement?.creationDisabled)throw Error('Admin must configure your USDT rate first.');await idempotent('payout/merchant-usdt/create',{amountMinor:minor($('#merchantUsdtInr').value),network:state.settlement.network,address:$('#merchantUsdtAddress').value.trim()});$('#merchantUsdtWithdrawForm').reset();await settlement();toast('Withdrawal requested; INR reserved.');});
$('#downloadReport').onclick=()=>run($('#downloadReport'),()=>exportReport('ledger'));
$('#markAllRead').onclick=()=>run($('#markAllRead'),async()=>{const latest=Math.max(0,...(state.notifications||[]).map(r=>+new Date(r.created_at)));localStorage.setItem('wpay:merchant:'+state.account.id+':read',String(latest));await notifications();toast('Marked read on this browser.');});
$('#newTicket').onclick=()=>promptForm('New support ticket',field('ticketSubject','Subject')+'<div class="field"><label for="ticketMessage">Message</label><textarea id="ticketMessage" class="control" maxlength="2000" required></textarea></div>',async()=>{await idempotent('panel/support/create',{subject:$('#ticketSubject').value.trim(),message:$('#ticketMessage').value.trim()},'requestId');closeModal();await support();toast('Support ticket created.');},'Create ticket');
bindForm('passwordForm',async()=>{checkPassword($('#newPassword').value);const s=state.security||await request('security');const d=await post('security/password',{password:$('#currentPassword').value,newPassword:$('#newPassword').value,...(s.enabled?{code:$('#passwordCode').value}:{})});$('#passwordForm').reset();invalidate();if(d.stage)await authStage(d);else await security();toast('Password changed. Other sessions were invalidated.');});
bindForm('profileForm',async()=>{const d=await mutate('panel/profile/update',{name:$('#businessName').value.trim()});state.account.name=d.name;text('.sidebar-foot strong',d.name);text('.merchant-chip strong',d.name);toast('Profile saved.');});
bindForm('prefsForm',async()=>{await post('panel/preferences',{inAppNotifications:$('#inAppNotifications').checked});await post('locale',{locale:$('#locale').value});state.account.locale=$('#locale').value;invalidate();toast('Preferences saved.');});
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});$('#reportTo').value=today;$('#reportFrom').value=new Date(Date.now()-6*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(p!==state.page&&$('#page-'+p))navigate(p);});
let lastActivity=Date.now();for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{lastActivity=Date.now();},{passive:true});setInterval(()=>{if(state.account&&document.visibilityState==='visible'&&Date.now()-lastActivity<300000)post('refresh').catch(e=>{if(e.code==='AUTH_FAILED')showLogin();});},300000);
start().catch(e=>{showLogin();if(e.code!=='AUTH_FAILED')text('#loginMessage',message(e));});
}};
