"use strict";
(function(root){
 const format=(n,currency='INR')=>{const scale=currency==='USDT'?6:2,b=BigInt(n),s=(b<0n?-b:b).toString().padStart(scale+1,'0');return (b<0n?'-':'')+s.slice(0,-scale)+'.'+s.slice(-scale);};
 const minor=(value,currency='INR')=>{const scale=currency==='USDT'?6:2;if(!new RegExp('^(0|[1-9][0-9]*)(\\.[0-9]{1,'+scale+'})?$').test(value))throw new Error('error.INVALID_INPUT');const [whole,fraction='']=value.split('.');return (BigInt(whole)*10n**BigInt(scale)+BigInt(fraction.padEnd(scale,'0'))).toString();};
 async function file(input){const f=input.files[0];if(!f||f.size>1048576)throw new Error('error.INVALID_INPUT');const bytes=new Uint8Array(await f.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name:f.name,data:btoa(raw)};}
 function download(name,bytes){const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function render(args){
  const {account,locale,request,post,action,el,container,title,destination}=args,t=k=>root.WPayPayoutLocales.text(locale,k),page=destination.split('.').at(-1),merchant=account.accountType==='merchant',user=account.accountType==='user',admin=!user&&!merchant;
  title.textContent=t(page);container.replaceChildren();const card=el('section',undefined,'card business-card');container.append(card);card.append(el('p',t('notice'),'notice'));
  const button=(key,fn)=>{const b=el('button',t(key));b.type='button';b.onclick=()=>action(fn);return b;};
  const field=(form,key,type='text',required=true)=>{const label=el('label',t(key)),node=el('input');node.type=type;node.required=required;node.maxLength=key==='note'||key==='reason'?300:120;node.setAttribute('aria-label',t(key));label.append(node);form.append(label);return node;};
  const select=(form,key,options)=>{const label=el('label',t(key)),node=el('select');node.setAttribute('aria-label',t(key));for(const [id,label]of options){const o=el('option',label);o.value=id;node.append(o);}label.append(node);form.append(label);return node;};
  const submit=(form,key,fn)=>{const b=el('button',t(key));b.type='submit';form.append(b);form.onsubmit=e=>{e.preventDefault();action(fn);};};
  const facts=(root,values)=>{const d=el('dl',undefined,'facts');for(const [key,value]of Object.entries(values))d.append(el('dt',t(key)),el('dd',String(value)));root.append(d);};
  async function history(route,key,states,show){let offset=0;const filter=el('form'),status=select(filter,'all',[['',t('all')],...states.map(s=>[s,t(s)])]),reference=key==='orders'?field(filter,'reference','text',false):null,currency=key==='withdrawals'?select(filter,'currency',[['',t('all')],['INR','INR'],['USDT','USDT']]):null,records=el('div');submit(filter,'filter',async()=>{offset=0;await refresh();});if(args.view==='payout-review'&&key==='orders')status.value='submitted';card.append(el('h2',t('history')),filter,records);async function refresh(){const data=await post(route,{offset,limit:10,...(status.value?{state:status.value}:{}),...(reference?.value?{reference:reference.value}:{}),...(currency?.value?{currency:currency.value}:{})});records.replaceChildren();for(const row of data[key])await show(records,row);if(!data[key].length)records.append(el('p',t('empty')));if(offset)records.append(button('previous',async()=>{offset=Math.max(0,offset-10);await refresh();}));if(data.hasMore)records.append(button('next',async()=>{offset+=10;await refresh();}));}await refresh();}
  async function orderDetails(id){const p=await post('payout/get',{id}),box=el('article',undefined,'card');detailBox.replaceChildren(box);box.append(el('h2',p.reference),el('p',t(p.status)));facts(box,{amount:format(p.amountMinor),transferMode:p.transferMode||'bank',deadline:p.deadlineAt||'—',...(p.beneficiary?Object.fromEntries(Object.entries(p.beneficiary).filter(([,v])=>v)): {})});
   if(p.proof){box.append(el('p',p.proof.name+' · '+t(p.proof.scanState)));if(p.proof.downloadAllowed)box.append(button('download',async()=>{const f=await post('payout/proof',{id,proofId:p.proof.id});download(f.name,Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)));}));}if(p.evidence)facts(box,{utr:p.evidence.utr});
   if(p.dispute){const d=p.dispute;box.append(el('h3','Post-approval dispute'),el('p',d.status+' · '+d.reason),el('p','Capacity held: INR '+format(d.amountMinor)+' · Commission held: INR '+format(d.commissionMinor)));if(d.resolutionReason)box.append(el('p','Decision: '+d.resolutionReason));for(const r of d.responses||[])box.append(el('p','User response: '+r.reason));
    if(admin&&d.downloadAllowed){for(const proofId of [d.statementId,...(d.responses||[]).map(r=>r.proofId).filter(Boolean)])box.append(button('download',async()=>{const f=await post('payout/proof',{id,proofId});download(f.name,Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)));}));box.append(el('p','Verify the receiving statement covers '+d.coverageFrom+' through '+d.coverageThrough+'. Check the recipient, payment and statement contents before deciding.','notice'));}
    if(d.status==='pending'&&(admin||user)){const f=el('form'),reason=field(f,'reason');if(admin){for(const [decision,label]of [['payment_valid','Payment valid — release holds'],['payment_invalid','Payment invalid — reverse and refund']]){const b=el('button',label);b.type='button';b.onclick=()=>{if(f.reportValidity())action(async()=>{await post('payout/dispute/resolve',{id,action:decision,reason:reason.value});await orderDetails(id);});};f.append(b);}}else{const proof=field(f,'proof','file',false);proof.accept='.pdf,.png,.jpg,.jpeg';submit(f,'submit',async()=>{await post('payout/dispute/respond',{id,reason:reason.value,...(proof.files.length?{proof:await file(proof)}:{})});await orderDetails(id);});}box.append(f);}
   }
   if(p.status==='merchant_rejected_review')box.append(el('p',t('dispute'),'notice'));
   const form=el('form');if(merchant&&['open','submitted'].includes(p.status)||admin&&p.status==='merchant_rejected_review'){
    const reason=field(form,'reason');const decide=async chosen=>{if(!form.reportValidity())return;await post(admin?'payout/resolve':'payout/review',{id,action:chosen,reason:reason.value});await render({...args,selectedId:id});};
    if(merchant){if(p.status==='open')form.append(button('cancel',()=>decide('cancel')));else form.append(button('approve',()=>decide('approve')),button('reject',()=>decide('reject')));}else form.append(button('paid',()=>decide('paid')),button('notPaid',()=>decide('not_paid')));box.append(form);
   }
   if(user&&p.status==='claimed'){
    const amount=field(form,'amount'),utr=field(form,'utr'),proof=field(form,'proof','file'),note=field(form,'note','text',false);amount.value=format(p.amountMinor);proof.accept='.pdf,.png,.jpg,.jpeg';box.append(el('p',t('claimOnly'),'notice'));
    submit(form,'submit',async()=>{await post('payout/submit',{id,amountMinor:minor(amount.value),utr:utr.value,proof:await file(proof),note:note.value});await render({...args,selectedId:id});});box.append(form,button('release',async()=>{await post('payout/release',{id});await render(args);}));
   }
   if(admin){facts(box,{merchantId:p.merchantId});for(const claim of p.claims||[])facts(box,{userId:claim.user_id,claimedAt:claim.created_at,claimExpiresAt:claim.expires_at});for(const event of p.audit||[])box.append(el('p',t(event.state)+' · '+event.reason+' · '+event.created_at));}
   box.append(button('hide',async()=>detailBox.replaceChildren()));
  }
  const detailBox=el('div');
  if(page==='merchant-usdt'){
   const s=await request('payout/merchant-usdt');if(s.creationDisabled){card.append(el('h2',t('unconfigured')),el('p',s.status==='rate_not_configured'?t('unconfigured'):(s.message||t('unconfigured')),'notice'));return;}card.append(el('h2','USDT Withdrawal'),el('p','Admin-set rate · '+s.rate+' INR/USDT · '+s.rounding,'notice'));
   facts(card,{available:format(s.available),reserved:format(s.reserved),rate:s.rate,rateVersion:s.rateVersion,network:s.network,maxUsdt:format(s.maxUsdtMinor,'USDT')});
   const form=el('form'),amount=field(form,'amount'),network=select(form,'network',[[s.network,s.network]]),address=field(form,'address'),key=crypto.randomUUID();amount.inputMode='decimal';
   const quote=el('p','0.000000 USDT','hint');amount.addEventListener('input',()=>{try{const inr=BigInt(minor(amount.value||'0')),rate=BigInt(Math.round(Number(s.rate)*1000000));quote.textContent=(inr*10000000000n/rate/1000000n)+'.'+(inr*10000000000n/rate%1000000n).toString().padStart(6,'0')+' USDT';}catch{quote.textContent='—';}});
   submit(form,'requestUsdt',async()=>{await post('payout/merchant-usdt/create',{idempotencyKey:key,amountMinor:minor(amount.value),network:network.value,address:address.value});await render(args);});card.append(form,quote);
   for(const r of s.requests){const row=el('article',undefined,'business-row');facts(row,{id:r.id,state:r.state,inr:format(r.inrMinor),usdt:format(r.usdtMinor,'USDT'),rate:r.rate,network:r.network,createdAt:r.createdAt});if(['requested','review'].includes(r.state)){const cancel=el('form'),reason=field(cancel,'reason');submit(cancel,'cancel',async()=>{await post('payout/merchant-usdt/transition',{id:r.id,action:'cancel',reason:reason.value});await render(args);});row.append(cancel);}card.append(row);}return;
  }
  if(page==='merchant-usdt-admin'){
   const data=await request('payout/merchant-usdt-admin');card.append(el('h2','Merchant USDT Withdrawals'));
   for(const r of data.requests){const row=el('article',undefined,'business-row');facts(row,{merchant:r.merchantName,id:r.id,state:r.state,inr:format(r.inrMinor),usdt:format(r.usdtMinor,'USDT'),rate:r.rate,network:r.network,createdAt:r.createdAt});
    if(!['completed','rejected','cancelled'].includes(r.state)){const form=el('form'),reason=field(form,'reason'),send=async(action,extras={})=>{await post('payout/merchant-usdt/transition',{id:r.id,action,reason:reason.value,...extras});await render(args);};
     if(r.state==='requested')form.append(button('reviewWithdrawal',()=>send('review')));
     if(['requested','review'].includes(r.state))form.append(button('approveWithdrawal',()=>send('approve')));
     if(r.state==='approved')form.append(button('process',()=>send('process')));
     if(['requested','review','approved'].includes(r.state))form.append(button('rejectWithdrawal',()=>send('reject')));
     if(r.state==='processing'){const reference=field(form,'completionReference'),time=field(form,'completedAt');time.placeholder='2026-09-20T12:00:00Z';form.append(button('complete',()=>send('complete',{reference:reference.value,network:r.network,completedAt:time.value})));}
     row.append(form);
    }card.append(row);
   }return;
  }
  if(page==='orders'&&admin){
   const review=el('section',undefined,'card'),wrap=el('div',undefined,'table-wrap');review.append(el('h2','Payout requests awaiting Admin approval'),el('p','Approve or reject the complete upload once. Each approved order appears separately to Users. Orders with less than 15 minutes remaining fail and their reservation is released.','notice'),wrap);card.append(review);
   let offset=0;async function approvals(){const d=await post('payout/approval/search',{offset,limit:25});wrap.replaceChildren();const table=el('table'),head=el('tr');for(const h of ['Request / Merchant','Orders','Total INR','Reserved with fees','Available INR','Earliest deadline','Action'])head.append(el('th',h));table.append(head);
    for(const r of d.requests){const tr=el('tr');for(const value of [r.id+' / '+r.merchant_name,r.order_count,format(r.volume_minor),format(r.reserve_minor),format(r.available_minor),r.earliest_deadline?new Date(r.earliest_deadline).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'—'])tr.append(el('td',String(value)));
     const td=el('td'),form=el('form'),reason=field(form,'reason');const decide=async choice=>{if(!form.reportValidity())return;for(const b of form.querySelectorAll('button'))b.disabled=true;try{const result=await post('payout/approval/decide',{id:r.id,action:choice,reason:reason.value});await approvals();review.append(el('p','Approved: '+result.approved+' · Failed: '+result.failed+' · Rejected: '+result.rejected));}finally{for(const b of form.querySelectorAll('button'))b.disabled=false;}};
     form.append(button('approve',()=>decide('approve')),button('reject',()=>decide('reject')));td.append(form);tr.append(td);table.append(tr);
    }wrap.append(table);if(!d.requests.length)wrap.append(el('p','No requests awaiting approval.'));if(offset)wrap.append(button('previous',async()=>{offset-=25;await approvals();}));if(d.hasMore)wrap.append(button('next',async()=>{offset+=25;await approvals();}));
   }await approvals();
  }
  if(page==='orders'&&merchant&&args.view!=='payout-review'){const summary=await request('payout/summary');facts(card,Object.fromEntries(['available','reserved','principal','fees','held'].map(k=>[k,format(summary[k])])));
   const form=el('form'),reference=field(form,'reference'),name=field(form,'beneficiaryName'),bankName=field(form,'bankName'),number=field(form,'accountNumber'),ifsc=field(form,'ifsc'),upiId=field(form,'upiId','text',false),amount=field(form,'amount'),note=field(form,'note','text',false),requestId=crypto.randomUUID();
   reference.maxLength=100;number.inputMode='numeric';number.pattern='[0-9]{6,24}';ifsc.pattern='[A-Z]{4}0[A-Z0-9]{6}';amount.inputMode='decimal';
   submit(form,'create',async()=>{const result=await post('payout/create',{idempotencyKey:requestId,reference:reference.value,beneficiaryName:name.value,bankName:bankName.value,accountNumber:number.value,ifsc:ifsc.value,upiId:upiId.value,amountMinor:minor(amount.value),note:note.value});await render({...args,selectedId:result.id});});card.append(el('h2',t('single')),form);
   const bulk=el('form'),fileInput=field(bulk,'file','file'),errors=el('p'),preview=el('div'),batchId=crypto.randomUUID(),validate=el('button','Validate Excel'),createBatch=el('button','Create Bulk Payouts');
   fileInput.accept='.csv,.xls,.xlsx';validate.type='submit';createBatch.type='button';createBatch.disabled=true;bulk.append(validate,createBatch);let preparedFile=null;
   bulk.onsubmit=e=>{e.preventDefault();action(async()=>{preparedFile=await file(fileInput);const result=await post('payout/bulk/validate',{idempotencyKey:batchId,file:preparedFile});preview.replaceChildren();errors.textContent='';
    facts(preview,{available:format(result.availableMinor),batchReserve:format(result.batchReserveMinor),remainingAfterBatch:format(result.remainingMinor)});
    for(const row of result.rows){const item=el('article',undefined,'business-row');facts(item,{reference:row.reference,beneficiaryName:row.beneficiaryName,bankName:row.bankName,accountNumber:row.accountNumber,ifsc:row.ifsc,upiId:row.upiId||'—',amount:format(row.amountMinor),fees:format((BigInt(row.percentageFeeMinor)+BigInt(row.fixedFeeMinor)).toString()),reserve:format(row.reserveMinor),status:row.existingReference?'Existing reference':'Valid'});preview.append(item);}
    if(result.errors.length)errors.textContent=t('bulkErrors')+' '+result.errors.map(e=>e.row?('row '+e.row):e.error).join(', ');
    if(result.exceedsAvailable)errors.textContent=(errors.textContent?errors.textContent+' · ':'')+'Batch reserve exceeds current available balance.';
    createBatch.disabled=!result.valid;
   });};
   createBatch.onclick=()=>action(async()=>{if(!preparedFile||createBatch.disabled)return;const result=await post('payout/bulk',{idempotencyKey:batchId,file:preparedFile});if(result.errors.length){errors.textContent=t('bulkErrors')+' '+result.errors.map(e=>e.row).join(', ');return;}await render(args);});
   const template=button('template',async()=>{const result=await request('payout/template');download(result.name,Uint8Array.from(atob(result.data),c=>c.charCodeAt(0)));});card.append(el('h2',t('bulk')),el('p',t('bulkHelp'),'hint'),el('p','Available Merchant balance: INR '+format(summary.available)+' · Excel is validated server-side before creation; the complete batch is atomic.','notice'),template,bulk,errors,preview);
  }
  if(page==='disputes'){await history('payout/dispute/search','orders',['pending','payment_valid','payment_invalid'],async(root,p)=>{const row=el('article',undefined,'business-row');row.append(el('h3',p.reference),el('p','INR '+format(p.amountMinor)+' · '+p.status+' · '+p.reason),button('details',()=>orderDetails(p.id)));root.append(row);});card.append(detailBox);return;}
  if(page==='jobs'){
   const queue=await request('payout/queue'),form=el('form'),bank=select(form,'bankId',queue.banks.map(b=>[b.id,b.id]));card.append(el('h2',t('queue')),form);
   if(!queue.orders.length)card.append(el('p',t('empty')));
   for(const p of queue.orders){const item=el('article',undefined,'business-row');item.append(el('p','INR '+format(p.amountMinor)),el('p',p.id),button('claim',async()=>{await post('payout/claim',{id:p.id,...(p.bankRequired===false?{}:{bankId:bank.value})});await render({...args,selectedId:p.id});}));card.append(item);}
  }
  if(['orders','jobs'].includes(page)){
   await history('payout/search','orders',['pending_admin','open','claimed','submitted','merchant_rejected_review','successful','reversed','failed','rejected','cancelled','not_paid'],async(root,p)=>{const row=el('article',undefined,'business-row');row.append(el('h3',p.reference),el('p','INR '+format(p.amountMinor)+' · '+t(p.status)),el('p',p.createdAt));if(merchant)row.append(el('p',t('fees')+': '+format((BigInt(p.percentageFeeMinor)+BigInt(p.fixedFeeMinor)).toString())));for(const key of ['claimedAt','submittedAt','completedAt'])if(p[key])row.append(el('p',t(key==='completedAt'?'completedAtLabel':key)+': '+p[key]));row.append(button('details',()=>orderDetails(p.id)));root.append(row);});card.append(detailBox);if(args.selectedId)await orderDetails(args.selectedId);
  }
  if(page==='commission'){
   const data=await request('payout/commission'),b=data.balance;card.append(el('p',t('shared'),'notice'));facts(card,{...Object.fromEntries(['payin','payout','adjustments','gross','held','reserved','withdrawn','available'].map(k=>[k,format(b[k])])),usdtEquivalentMinor:format(b.usdtEquivalentMinor,'USDT'),inrPerUsdt:b.inrPerUsdt});
   let offset=0;const rows=el('div'),filter=el('form'),reference=field(filter,'transactionReference','text',false);submit(filter,'filter',async()=>{offset=0;await history();});async function history(){const d=await post('payout/commission/search',{offset,limit:20,...(reference.value?{reference:reference.value}:{})});rows.replaceChildren();for(const e of d.entries)rows.append(el('p',t(({user_commission:'payin',user_payout_commission:'payout',user_commission_adjustment:'adjustments',user_commission_hold:'held',user_commission_reserved:'reserved',user_commission_withdrawn:'withdrawn'})[e.ledger_type])+' · '+t(e.direction)+' · INR '+format(e.amount_minor)+' · '+e.created_at));if(offset)rows.append(button('previous',async()=>{offset=Math.max(0,offset-20);await history();}));if(d.hasMore)rows.append(button('next',async()=>{offset+=20;await history();}));}card.append(filter,rows);await history();
  }
  if(page==='withdrawals'){
   if(user){const summary=await request('payout/commission'),b=summary.balance;card.append(el('p',t('shared'),'notice'));facts(card,{available:format(b.available),usdtEquivalentMinor:format(b.usdtEquivalentMinor,'USDT'),inrPerUsdt:b.inrPerUsdt});
    const inr=el('form'),amount=field(inr,'amount'),bankName=field(inr,'bankName'),holder=field(inr,'beneficiaryName'),number=field(inr,'accountNumber'),ifsc=field(inr,'ifsc'),inrKey=crypto.randomUUID(),quote=el('p',undefined,'notice');
    number.inputMode='numeric';number.pattern='[0-9]{6,24}';ifsc.pattern='[A-Z]{4}0[A-Z0-9]{6}';
    const showQuote=()=>{try{const gross=BigInt(minor(amount.value)),fee=(gross*5n+500n)/1000n;quote.textContent=t('fee')+': INR '+format(fee)+' (0.5%) · '+t('netTransfer')+': INR '+format(gross-fee);}catch{quote.textContent=t('withdrawalFeeHelp');}};
    amount.oninput=showQuote;inr.append(button('useAvailable',async()=>{amount.value=format(b.available);showQuote();}),quote);showQuote();
    submit(inr,'requestInr',async()=>{await post('payout/withdrawal/create',{idempotencyKey:inrKey,currency:'INR',amountMinor:minor(amount.value),bankDetails:{bankName:bankName.value,beneficiaryName:holder.value,accountNumber:number.value,ifsc:ifsc.value.toUpperCase()}});await render(args);});
    const usdt=el('form'),ua=field(usdt,'amountUsdt'),network=select(usdt,'network',[[b.network,b.network]]),address=field(usdt,'address'),usdtKey=crypto.randomUUID();usdt.append(button('useAvailable',async()=>{ua.value=format(b.usdtEquivalentMinor,'USDT');}));
    submit(usdt,'requestUsdt',async()=>{await post('payout/withdrawal/create',{idempotencyKey:usdtKey,currency:'USDT',amountMinor:minor(ua.value,'USDT'),network:network.value,address:address.value});await render(args);});card.append(el('h2',t('requestInr')),inr,el('h2',t('requestUsdt')),el('p',t('manual'),'hint'),usdt);
   }
   await history('payout/withdrawal/search','withdrawals',['requested','review','approved','processing','completed','rejected','cancelled'],async(root,w)=>{
    const row=el('article',undefined,'business-row');row.append(el('h3',w.currency+' '+format(w.amountMinor,w.currency)),el('p',t(w.state)+' · '+w.id),el('p',t('reserved')+': '+format(w.entitlementMinor)));if(admin)row.append(el('p',t('userId')+': '+w.userId));if(w.rate)row.append(el('p',t('inrPerUsdt')+': '+w.rate));row.append(el('p',t('fee')+': '+format(w.feeMinor||'0')+' INR · '+t('netTransfer')+': '+format(w.netMinor||w.amountMinor,w.currency)+' '+w.currency));if(w.reason)row.append(el('p',t('reason')+': '+w.reason));
    row.append(button('details',async()=>{const d=await post('payout/withdrawal/get',{id:w.id}),box=el('div');row.append(box);facts(box,d.destination);if(d.completion)facts(box,d.completion);box.append(button('hide',async()=>box.remove()));}));
    const form=el('form'),reason=field(form,'reason');const transition=async(action,extras={})=>{if(!form.reportValidity())return;await post('payout/withdrawal/transition',{id:w.id,action,reason:reason.value,...extras});await render(args);};
    if(user&&['requested','review'].includes(w.state))form.append(button('cancel',()=>transition('cancel')));
    if(admin){if(w.state==='requested')form.append(button('reviewWithdrawal',()=>transition('review')));if(['requested','review'].includes(w.state))form.append(button('approveWithdrawal',()=>transition('approve')));if(w.state==='approved')form.append(button('process',()=>transition('process')));if(['requested','review','approved'].includes(w.state))form.append(button('rejectWithdrawal',()=>transition('reject')));
     if(w.state==='processing'){const reference=field(form,'completionReference'),time=field(form,'completedAt'),network=w.currency==='USDT'?field(form,'network'):null;time.placeholder='2026-09-16T12:00:00Z';form.append(button('complete',()=>transition('complete',{reference:reference.value,completedAt:time.value,...(network?{network:network.value}:{})})));row.append(el('p',t('manual'),'notice'));}
    }
    if(!['completed','rejected','cancelled'].includes(w.state))row.append(form);root.append(row);
   });
  }
  if(page==='holds'){
   if(admin){const form=el('form'),owner=field(form,'userId'),amount=field(form,'amount'),ref=field(form,'holdReference'),reason=field(form,'reason'),id=crypto.randomUUID();submit(form,'hold',async()=>{await post('payout/hold/manage',{id,userId:owner.value,amountMinor:minor(amount.value),reference:ref.value,reason:reason.value,release:false});await render(args);});card.append(form);}
   let offset=0;const rows=el('div'),filter=el('form'),reference=field(filter,'holdReference','text',false);submit(filter,'filter',async()=>{offset=0;await refreshHolds();});card.append(el('h2',t('history')),filter,rows);
   async function refreshHolds(){const h=await post('payout/hold/search',{offset,limit:10,...(reference.value?{reference:reference.value}:{})});rows.replaceChildren();for(const row of h.holds){const item=el('article',undefined,'business-row');item.append(el('p',row.reference+' · INR '+format(row.amount_minor)),el('p',row.reason),el('p',t(row.released_at?'released':'active')),el('p',row.created_at));if(admin)item.append(el('p',t('userId')+': '+row.user_id));if(admin&&!row.released_at)item.append(button('releaseHold',async()=>{await post('payout/hold/manage',{id:row.id,userId:row.user_id,amountMinor:row.amount_minor,reference:row.reference,reason:'Commission review completed',release:true});await render(args);}));rows.append(item);}if(!h.holds.length)rows.append(el('p',t('empty')));if(offset)rows.append(button('previous',async()=>{offset=Math.max(0,offset-10);await refreshHolds();}));if(h.hasMore)rows.append(button('next',async()=>{offset+=10;await refreshHolds();}));}await refreshHolds();
  }
  if(page==='capabilities'){
   card.append(el('p',t('capacityHint')));for(const b of (await request('payout/capabilities')).banks){const row=el('article',undefined,'business-row'),form=el('form'),reason=field(form,'reason');row.append(el('h3',b.id),el('p',b.owner_id+' · v'+b.version+' · '+b.status),el('p',t(b.payout_capable?'payoutCapable':'notCapable')));submit(form,b.payout_capable?'disable':'enable',async()=>{await post('payout/capability',{bankId:b.id,version:b.version,enabled:!b.payout_capable,reason:reason.value});await render(args);});row.append(form);card.append(row);}
  }
  card.append(button('refresh',()=>render(args)));
 }
 root.WPayPayoutPage={render};
})(globalThis);
