"use strict";
(function(root){
 const words={
 transactionReference:['Transaction reference','Номер операции','交易参考号'],credit:['Credit','Начисление','贷记'],debit:['Debit','Списание','借记'],released:['Released','Разблокировано','已解除'],active:['Active','Активно','有效'],
 merchantId:['Merchant account ID','ID продавца','商户账号 ID'],claimExpiresAt:['Claim expiry','Истечение задания','领取有效期'],
 group:['Payouts & Commission','Выплаты и вознаграждение','付款与佣金'],claimedAt:['Claimed at','Время назначения','领取时间'],submittedAt:['Submitted at','Время отправки','提交时间'],completedAtLabel:['Completed at','Время завершения','完成时间'],
 orders:['INR Payouts','Выплаты INR','INR 付款'],jobs:['INR Payout Jobs','Задания на выплату INR','INR 付款任务'],commission:['Commission','Вознаграждение','佣金'],withdrawals:['Commission Withdrawals','Вывод вознаграждения','佣金提现'],holds:['Commission Holds','Блокировки вознаграждения','佣金冻结'],capabilities:['Payout Bank Capabilities','Банки для выплат','付款银行权限'],'merchant-usdt':['USDT Withdrawal','Вывод USDT','USDT 提现'],'merchant-usdt-admin':['Merchant USDT Withdrawals','Вывод USDT продавцов','商户 USDT 提现'],
 notice:['Local acceptance — no real payout provider or blockchain sender is connected.','Локальная проверка — реальный провайдер выплат и отправка в блокчейн не подключены.','本地验收 — 未连接真实付款服务商或区块链发送服务。'],
 unconfigured:['USDT settlement rate not configured','Курс расчётов USDT не настроен','未配置 USDT 结算汇率'],single:['Single INR payout','Одиночная выплата INR','单笔 INR 付款'],create:['Create payout','Создать выплату','创建付款'],reference:['Merchant reference','Номер выплаты продавца','商户付款编号'],beneficiaryName:['Beneficiary name','Имя получателя','收款人姓名'],bankName:['Bank name','Название банка','银行名称'],upiId:['UPI ID (optional)','UPI ID (необязательно)','UPI ID（选填）'],accountNumber:['Account number','Номер счёта','银行账号'],ifsc:['IFSC','IFSC','IFSC'],amount:['Amount INR','Сумма INR','INR 金额'],amountMinor:['Amount in paise','Сумма в пайсах','金额（派士）'],amountUsdt:['Amount USDT','Сумма USDT','USDT 金额'],note:['Note (optional)','Примечание (необязательно)','备注（选填）'],bulk:['Bulk upload','Массовая загрузка','批量上传'],file:['CSV / XLS / XLSX file','Файл CSV / XLS / XLSX','CSV / XLS / XLSX 文件'],template:['Download Excel template','Скачать шаблон Excel','下载 Excel 模板'],upload:['Validate and create batch','Проверить и создать пакет','验证并创建批次'],bulkHelp:['Up to 100 rows / 1 MiB. Account numbers must be text. All rows must be valid; the batch is atomic.','До 100 строк / 1 МиБ. Номера счетов — текст. Все строки должны быть корректны; пакет выполняется целиком.','最多 100 行／1 MiB。银行账号须为文本。所有行均须有效；批次操作为原子操作。'],bulkErrors:['Batch rejected; no payouts created. Invalid rows:','Пакет отклонён; выплаты не созданы. Ошибки в строках:','批次被拒绝；未创建付款。无效行：'],
 open:['Open','Открыта','待领取'],claimed:['Claimed','Назначена','已领取'],submitted:['Submitted for review','На проверке','已提交审核'],merchant_rejected_review:['Dispute review — reserve protected','Спор — резерв защищён','争议审核 — 保留预留资金'],successful:['Successful','Успешна','成功'],cancelled:['Cancelled','Отменена','已取消'],not_paid:['Confirmed not paid','Подтверждено: не оплачено','已确认未付款'],requested:['Pending Admin Processing','Ожидает обработки администратором','等待管理员处理'],review:['Under review','На рассмотрении','审核中'],approved:['Approved','Одобрено','已批准'],processing:['Processing','Обрабатывается','处理中'],completed:['Completed (manual record)','Завершено (ручная запись)','已完成（人工记录）'],rejected:['Rejected','Отклонено','已拒绝'],
 available:['Available INR','Доступно INR','可用 INR'],reserved:['Reserved INR','Зарезервировано INR','预留 INR'],fees:['Payout fees INR','Комиссия за выплаты INR','付款费用 INR'],principal:['Settled principal INR','Выплаченная основная сумма INR','已结算本金 INR'],held:['Held INR','Заблокировано INR','冻结 INR'],payin:['Pay-in commission INR','Вознаграждение за приём INR','收款佣金 INR'],payout:['Payout commission INR','Вознаграждение за выплаты INR','付款佣金 INR'],adjustments:['Adjustments INR','Корректировки INR','调整 INR'],gross:['Total entitlement INR','Всего вознаграждения INR','总佣金权益 INR'],withdrawn:['Withdrawn INR','Выведено INR','已提现 INR'],usdtEquivalentMinor:['Available USDT equivalent','Доступный эквивалент USDT','可用 USDT 等值'],inrPerUsdt:['Fixed INR per USDT','Фиксированный курс INR за USDT','每 USDT 固定 INR 汇率'],shared:['INR and USDT use one commission entitlement. A reservation in either currency reduces both views.','INR и USDT используют единое вознаграждение. Резерв в любой валюте уменьшает оба представления.','INR 与 USDT 共用同一佣金权益。任一币种的预留均减少两个视图的可用余额。'],
 history:['History','История','历史记录'],all:['All states','Все статусы','全部状态'],filter:['Apply filters','Применить фильтры','应用筛选'],next:['Next page','Следующая страница','下一页'],previous:['Previous page','Предыдущая страница','上一页'],refresh:['Refresh','Обновить','刷新'],empty:['No records','Нет записей','暂无记录'],details:['Open details','Открыть детали','查看详情'],hide:['Hide details','Скрыть детали','隐藏详情'],approve:['Approve payout','Одобрить выплату','批准付款'],reject:['Reject into dispute review','Отклонить и открыть спор','拒绝并进入争议审核'],cancel:['Cancel','Отменить','取消'],reason:['Review reason','Причина решения','审核原因'],paid:['Confirm Paid','Подтвердить оплату','确认已付款'],notPaid:['Confirm Not Paid','Подтвердить отсутствие оплаты','确认未付款'],dispute:['Reserve stays protected until an authorized Admin resolves the dispute. No commission or capacity restoration yet.','Резерв защищён до решения администратора. Вознаграждение и восстановление лимита пока не начислены.','管理员解决争议前，预留资金保持锁定。尚未计入佣金或恢复额度。'],
 queue:['Eligible open payouts','Доступные выплаты','符合条件的待领取付款'],claim:['Create Payout','Создать выплату','创建付款'],bankId:['Your verified payout bank','Ваш проверенный банк для выплат','您已验证的付款银行'],release:['Release unsubmitted claim','Освободить задание без подтверждения','释放尚未提交的任务'],utr:['UTR / payment reference','UTR / номер платежа','UTR／付款参考号'],proof:['Proof PDF / PNG / JPEG (1 MiB max)','Подтверждение PDF / PNG / JPEG (до 1 МиБ)','付款凭证 PDF／PNG／JPEG（最大 1 MiB）'],submit:['Submit payment claim','Отправить подтверждение платежа','提交付款申报'],claimOnly:['Create Payout locks the order to you for 10 minutes. If you release it or the timer expires, it stays hidden for a 5-minute cooldown before returning to other Users. A submitted reference is a claim only until reviewed.','Создание выплаты блокирует заказ за вами на 10 минут. При освобождении или истечении таймера заказ остаётся скрытым ещё 5 минут, затем снова доступен другим пользователям. Отправленный номер остаётся заявлением до проверки.','创建付款后订单将由您独占 10 分钟。若释放或超时，订单会继续隐藏 5 分钟冷却期，之后才重新对其他用户可见。提交的参考号在审核前仅为申报。'],download:['Download proof','Скачать подтверждение','下载凭证'],unscanned:['Unscanned','Не проверено сканером','未扫描'],clean:['Scanner accepted','Проверено сканером','扫描通过'],
 requestInr:['Request INR withdrawal','Запросить вывод INR','申请 INR 提现'],requestUsdt:['Request USDT withdrawal','Запросить вывод USDT','申请 USDT 提现'],currency:['Currency','Валюта','币种'],network:['Network','Сеть','网络'],address:['Wallet address','Адрес кошелька','钱包地址'],reviewWithdrawal:['Move to review','На рассмотрение','转入审核'],approveWithdrawal:['Approve withdrawal','Одобрить вывод','批准提现'],process:['Mark processing','Отметить обработку','标记处理中'],complete:['Record manual completion','Записать завершение вручную','记录人工完成'],rejectWithdrawal:['Reject before processing','Отклонить до обработки','在处理前拒绝'],completionReference:['Transaction hash / reference','Хеш / номер транзакции','交易哈希／参考号'],completedAt:['Completion time (UTC ISO)','Время завершения (UTC ISO)','完成时间（UTC ISO）'],manual:['Manual Admin record only. No blockchain confirmation or automated send.','Только ручная запись администратора. Подтверждения блокчейна и автоматической отправки нет.','仅为管理员人工记录。无区块链确认或自动发送。'],userId:['User account ID','ID пользователя','用户账号 ID'],hold:['Place commission hold','Заблокировать вознаграждение','冻结佣金'],releaseHold:['Release commission hold','Снять блокировку вознаграждения','解除佣金冻结'],holdReference:['Hold reference','Номер блокировки','冻结参考号'],enable:['Approve payout capability','Разрешить выплаты','批准付款权限'],disable:['Revoke payout capability','Запретить выплаты','撤销付款权限'],payoutCapable:['Payout capability approved','Выплаты разрешены','已批准付款权限'],notCapable:['Payout capability not approved','Выплаты не разрешены','尚未批准付款权限'],capacityHint:['A current bank version requires explicit payout capability approval.','Текущая версия счёта требует отдельного разрешения на выплаты.','当前银行账户版本须获得明确付款权限。']
 };
 Object.assign(words,{fee:['Fee','Комиссия','手续费'],netTransfer:['Net transfer','К получению','实际到账'],useAvailable:['Use full available balance','Весь доступный баланс','使用全部可用余额'],withdrawalFeeHelp:['INR withdrawal fee: 0.5%, included in your requested amount.','Комиссия INR: 0,5%, включена в сумму заявки.','INR 提现手续费为 0.5%，包含在申请金额内。']});
 const errors={INSUFFICIENT_BALANCE:['Merchant available balance is insufficient.','Недостаточно доступного баланса продавца.','商户可用余额不足。'],INSUFFICIENT_COMMISSION:['Available commission is insufficient.','Недостаточно доступного вознаграждения.','可用佣金不足。'],PAYOUT_BANK_REQUIRED:['An approved payout-capable bank is required.','Требуется банк с разрешением на выплаты.','需要已批准付款权限的银行。'],PAYOUT_FEE_CURRENCY:['INR payout requires an INR fixed fee configuration.','Для выплаты INR фиксированная комиссия должна быть в INR.','INR 付款要求以 INR 配置固定费用。'],PAYOUT_AMOUNT:['Submitted amount must exactly match the payout.','Отправленная сумма должна точно совпадать с выплатой.','提交金额必须与付款金额完全一致。'],MERCHANT_FX_UNCONFIGURED:words.unconfigured,UPLOAD_REJECTED:['The upload was rejected by the scanner.','Файл отклонён сканером.','扫描器拒绝了该文件。']};
 const pick=(values,locale)=>values[Math.max(0,['en','ru','zh-CN'].indexOf(locale))];
 root.WPayPayoutLocales={text:(locale,key)=>pick(words[key]||[key,key,key],locale),error:(locale,key)=>errors[key.replace(/^error\./,'')]?pick(errors[key.replace(/^error\./,'')],locale):null,hasError:code=>Object.hasOwn(errors,code)};
})(globalThis);
